### ISSUE TITLE
is Integrated Mobile Broadband work

### ISSUE THREAD

**Issue by lxgzmy** [tylernguyen/x1c6-hackintosh#10]
i have the carbon 6 with Integrated Mobile Broadband Fibocom L850-GL device, is this will work when i install mac os x?

**Comment by Romsky** [comment]
No, it will not. I have the same WWAN Hardware in my X1. At the moment only Windows can use this device. Even Linux is not possible. Even for Linux we need a Bios update to use it. And then, but only maybe, we can try to use it in Mac OS X. Of course, a driver is needed too. (Only windows is available atm)

**Comment by tylernguyen** [comment]
Yes, @Romsky is right, currently, WWAN will not work under macOS. Unfortunately, it seems that it will likely never be patched since not too many are invested in making a kext for it.
