### ISSUE TITLE
20 hour batter again in Bigsur

### ISSUE THREAD

**Issue by buyddy** [tylernguyen/x1c6-hackintosh#100]
<img width="524" alt="Screen Shot 2020-11-15 at 3 02 36 PM" src="https://user-images.githubusercontent.com/64387298/99196704-bfe29b00-2753-11eb-9591-6ff7f0ba19f5.png">

Use the SSDT-Battery, Everything else seem to read properly. No AE error in loading.

**Comment by buyddy** [comment]
It seems to be a random issue both with/without Quickpoll.

**Comment by benbender** [comment]
Please open an issue and including logs showing BATX-debug if the issue appears at my repo and close it here. Thanks.

**Comment by buyddy** [comment]
Going back to test V6 now. The issue is very random. I want to see if someone else has the same problem here since I was using the exact ssdt as in this repo.

**Comment by tylernguyen** [comment]
@buyddy 

Please test the latest EFI.

**Comment by buyddy** [comment]
> @buyddy
> 
> Please test the latest EFI.

<img width="608" alt="Screen Shot 2020-11-18 at 12 16 57 PM" src="https://user-images.githubusercontent.com/64387298/99570846-26f09180-2998-11eb-879e-f191ed2a1dce.png">
With your latest, still got 20:00 issue. No SSDT loading error so everything is loaded. The only hardware difference we have is SSD (I am using a second SSD in the WWAN slot) and I am using DW1820A. Not sure if that is related. Are you free of this issue?

**Comment by benbender** [comment]
As asked before: Please provide logs.

**Comment by tylernguyen** [comment]
Closed until proper logs are provided.

**Comment by buyddy** [comment]
I think I understand the problem now. This is probably an issue with iStat menu. The remaining battery time is some kind of moving average from the battery remain time taken from BBIS. The problem is the initial value, after a sleep, the initial value is over 20 hour due to the low power consumption during sleep. Therefore the result become very large. However when BBIS is not enabled, iStat menu probably does the calculation with the power draw and remaining battery. So it won't have the 20 hour issue. It also takes much longer to calculate the first battery remaining time when BBIS is not available.
