### ISSUE TITLE
 Thunderbolt or USB or other things cause the upper left part of the notebook to become very hot

### ISSUE THREAD

**Issue by lucas-www** [tylernguyen/x1c6-hackintosh#106]
When I was using the laptop, I found that the USB port near the left and the thunderbolt charging port was very hot. This was not the case before. It seems that this is caused by the new ACPI patch.
Do you have such a problem? 

X1C6(i7 8550u) with Big Sur, BIOS version:1.50.

@benbender @tylernguyen

**Comment by benbender** [comment]
Nope, not at all.

**Comment by tylernguyen** [comment]
@lucas-www 

Hm.. Mine is hot around the same area as well. Though I don't remember it not being hot before. Which commit are you are you on that it's not happening?

**Comment by benbender** [comment]
@tylernguyen @lucas-www whats your general temperature (as seen in Intel Power Gadget)?

**Comment by velaar** [comment]
@benbender Core MAX holds within 40-49C under low load (browser). Consistent with ~2.6-3W power consumption and liquid metal repaste. Left side is indeed getting quite hot but I thought that it was some of my mods (I'm using the bottom panel as an assertional heatsink) 

<img width="395" alt="image" src="https://user-images.githubusercontent.com/4062230/100239210-1f346e00-2eff-11eb-8d29-acc4aef8ef36.png">


Can it be related to #101 ? We are after all looking for a USB or PCIe device preventing the PKG from going to C7.

**Comment by lucas-www** [comment]
this commit(7c84fa90ea930526ba91c448533ffeb1cc8d6037) was good. @tylernguyen @benbender 

<img width="400" alt="image" src="https://user-images.githubusercontent.com/68903281/100304657-31370f00-2fda-11eb-9b2d-714066a1b70b.png">

**Comment by lucas-www** [comment]
@tylernguyen @benbender the below config.plist screenshot works pretty well for me(No kernel panic, Especially HDMI out works fine, I don't find other problem yet for now.), just for reference. 
<img width="1003" alt="image" src="https://user-images.githubusercontent.com/68903281/100307887-f0db8f00-2fe1-11eb-9d14-f89768fabf4f.png">

**Comment by KirisameMarisaa** [comment]
I experienced the same issue as well, The bottom left of the machine remain warm, which I suppose was because TB3 controller is always on. 

Another observation is, with all TB-3 patches enabled, under BIOS 1.30 (patched), TB-3 assist mode OFF, the TB3 controller can be seen under System Information, and no CPU C-Storm, CPU PKG power can decrease to 0.7w. 

I disabled all TB3 patches due to the existence of that issue, and the problem that USB-3.1 is not supported at all when the patch is applied. Looking forward to see new patches that solves the problem.

**Comment by velaar** [comment]
@KirisameMarisaa unfortunately there is no way to downgrade BIOS back to 1.3. (I can explain in detail but it is blocked because of the persistence mod that they introduced in 1.43)

Can you share your patched image? Can you confirm that with TB patches disabled you can go 0.7w on a more modern BIOS?

**Comment by velaar** [comment]
> @tylernguyen @benbender the below config.plist screenshot works pretty well for me(No kernel panic, Graphics card acceleration is enabled, Especially HDMI out works fine, I don't find other problem yet for now.), Could we adjust our config.plist configurations for UHD 620?, this suggestion is just for reference only.
> <img alt="image" width="1003" src="https://user-images.githubusercontent.com/68903281/100307887-f0db8f00-2fe1-11eb-9d14-f89768fabf4f.png">

With this ig-platform-id I'm getting underscaling issues after sleep: 


<img width="833" alt="image" src="https://user-images.githubusercontent.com/4062230/100385502-c7762f80-2ff0-11eb-8324-8f5f89c99251.png">

**Comment by tylernguyen** [comment]
@velaar Can you revert to commit https://github.com/tylernguyen/x1c6-hackintosh/commit/7c84fa90ea930526ba91c448533ffeb1cc8d6037 and check if the your machine gets hot?

**Comment by lucas-www** [comment]
After a period of observation, What I can be sure of is that the upper left corner will not heat up when using the battery, but it will be very hot when plugging  the TYPE-C power adapter.

**Comment by lucas-www** [comment]
> > @tylernguyen @benbender the below config.plist screenshot works pretty well for me(No kernel panic, Graphics card acceleration is enabled, Especially HDMI out works fine, I don't find other problem yet for now.), Could we adjust our config.plist configurations for UHD 620?, this suggestion is just for reference only.
> 
> With this ig-platform-id I'm getting underscaling issues after sleep:
> 
> <img alt="image" width="833" src="https://user-images.githubusercontent.com/4062230/100385502-c7762f80-2ff0-11eb-8324-8f5f89c99251.png">
@velaar Sorry, this is my mistake, I used a wrong EFI configuration, please use the configuration from the repository,but change AAPL,ig-platform-id and device-id to 00001659 which makes HDMI work Appropriately.

**Comment by tylernguyen** [comment]
@lucas-www 

Use the appropriate HDMI related issue. Off topic comments make it hard to track things down later on .

**Comment by lucas-www** [comment]
> @lucas-www
> 
> Use the appropriate HDMI related issue. Off topic comments make it hard to track things down later on .

I got it, thanks.

**Comment by velaar** [comment]
> @velaar Can you revert to commit [7c84fa9](https://github.com/tylernguyen/x1c6-hackintosh/commit/7c84fa90ea930526ba91c448533ffeb1cc8d6037) and check if the your machine gets hot?

The same behaviours as in the latest commit. 

<img width="396" alt="image" src="https://user-images.githubusercontent.com/4062230/100478418-24d5b380-30b9-11eb-9264-ee2f8e446178.png">

**Comment by vaczi001** [comment]
Hi guys, thank you for hard work, the guide is excellent!
I've got this notebook from second hand and I installed mac on it immediately.😄 

I did experienced power drain issues like you @velaar (but was not hot), I went to bios and enabled Thunderbolt BIOS Assist mode, then it went down to ~0.8W.

![Screenshot 2020-12-18 at 10 51 51](https://user-images.githubusercontent.com/33935034/102600911-b916c180-411f-11eb-9e6b-a88304ea9ef9.png)

But it's a little different here, I use Clover v5127 with a config.plist I created (with your DSDT rename patches and amls)

**Comment by velaar** [comment]
@vaczi001 does thunderbolt work as expected on your setup? eGPU? As it doesn't make much sense as TB state should be reset by SSDTs

**Comment by lucas-www** [comment]
> Hi guys, thank you for hard work, the guide is excellent!
> I've got this notebook from second hand and I installed mac on it immediately.😄
> 
> I did experience power drain issues like you @velaar (but was not hot), I went to bios and enabled Thunderbolt BIOS Assist mode, then it went down to ~0.8W.
> 
> ![Screenshot 2020-12-18 at 10 51 51](https://user-images.githubusercontent.com/33935034/102600911-b916c180-411f-11eb-9e6b-a88304ea9ef9.png)
> 
> But it's a little different here, I use Clover v5127 with a config.plist I created (with DSDT rename patches and amls from this guide, thank you again)

It seemed to have some effect when I enabled Thunderbolt BIOS Assist mode .

**Comment by vaczi001** [comment]
> @vaczi001 does thunderbolt work as expected on your setup? eGPU? As it doesn't make much sense as TB state should be reset by SSDTs

I want to buy an ADT-Link TB3 eGPU adapter somewhere next year, as for now I don't have any TB (or USB 3.1 Type-C) devices. 
Now I re-disabled the Thunderbolt BIOS Assist mode, and the power usage went up to ~3-4W at idle. After re-enabling again, it went down to 0.7-1W just to confirm it.
I also noticed that after enabling BIOS Assist mode, the USB 3.1 disappeared from System Info. 

Verified with Hackintool, indeed the USB 3.1 and Thunderbolt disappeared from PCI devices.
After disabling BIOS Assist, the USB 3.1 appeared again in System Info and I can see from Hackintool too. 

At System Info->Thunderbolt it says "Thunderbolt: no drivers are loaded" in both cases.

**Comment by tylernguyen** [comment]
@vaczi001 

That's documented behavior and to be expected. See:
https://github.com/tylernguyen/x1c6-hackintosh/blob/master/docs/1_README-HARDWAREandBIOS.md
https://github.com/tylernguyen/x1c6-hackintosh/blob/master/docs/3_README-other.md

**Comment by vaczi001** [comment]
I see, thanks! 
Then it's okay. 
As for heat, if hot-plug is enabled (or disabled, doesn't matter) it's not heating up for me.
