### ISSUE TITLE
Perfect WIFI card for both WIN10 and Mac

### ISSUE THREAD

**Issue by buyddy** [tylernguyen/x1c6-hackintosh#107]
Not so much an issue, but I just want to share some knowledge regarding replacing the wifi cards.

I started with the Lenovo version of DW1820A, fits perfectly, Win10 runs flawlessly. Mac is stable, however the card must disable ASPM, which results in much higher power consumption on X1C6. CPU power draw min at 1.4w instead of 0.86w others report.

Finally bite the bullet and bought a $50 Fenvi BCM94360NG, fit ok, the back is too thick but you can manage to squeeze in, the antenna cable is loose but there is a plastic cap you can use to keep it in place. This leads to very slight bent in the back cover when put back. Driver is perfect for Mac, however Win10 on battery freezes in a few minutes. Find out many people have the same issue. Looks like a similar problem with ASPM in WIN10 due to lack of proper driver. I further researched internet and it seems that DW1560 does not have proper WIN10 driver as well, and people are saying only DW1830 works on both (which is expensive and needs to pay for additional antenna too). 

Finally I decided to give Lenovo 04x6020 a try. This is NOT an A/E card, so even though I had it for a long time I never tried it. This card has WIN10 driver and also works perfect with Mac. Luckily, the Key is physically modifiable. Just cut off a piece of small plastic and it works like charm. Stable in both WIN10 and Mac. I found it the best card for X1C6 if wants dual systems. The card currently sells for $35 on eBay. I was actually able to find on Chinese Taobao a pre-cut version after I did my own experiment.

**Comment by velaar** [comment]
Personally using an Apple BCM94602CS via an adaptor. 

Over 1Gbps next to the router thanks to the 3 antennas, didn't have any issues in Windows with Apple bootcamp drivers. 

![image](https://user-images.githubusercontent.com/4062230/100682813-e7855600-3344-11eb-9393-9e4f3afe5860.png)

**Comment by buyddy** [comment]
> Personally using an Apple BCM94602CS via an adaptor.
> 
> Over 1Gbps next to the router thanks to the 3 antennas, didn't have any issues in Windows with Apple bootcamp drivers.
> 
> ![image](https://user-images.githubusercontent.com/4062230/100682813-e7855600-3344-11eb-9393-9e4f3afe5860.png)
> 
> What is the issue about though?

I did not try apple cards, just share some experience that I had. Putting a Lenovo card in Thinkpad is quite nice. I am quite surprised that there is enough room for adapter and this 3-antenna card.  Did you install the WWAN antenna for X1C6?

**Comment by tylernguyen** [comment]
@buyddy 

Thanks for the contribution. From my experience, Apple cards are the best as they work natively without any additional kexts or tinkering. There are you models, which will both require an adapter. Additionally, if your machine didn't come with WWAN, additional antennas can easily be added.
