### ISSUE TITLE
Random reboots on Bios 1.37

### ISSUE THREAD

**Issue by velaar** [tylernguyen/x1c6-hackintosh#11]
Hi, 

Thank you for compiling this. Which Bios version is DSDT for? Is is thunderbolt BIOS assist ON or OFF? 

Also any ETA on that update? :) No pressure. 

p.s. You might want to have a look at [this implementation of T480s](https://github.com/linusyang92/macOS-ThinkPad-T480s) I use thunderbolt SSDT from there and it works with an eGPU just fine.

**Comment by tylernguyen** [comment]
Hello @velaar, I just updated my BIOS to 1.37 and also had a few hardware changes so a big update will come soon! Regarding your concern, my thunderbolt assist is ON, and I do not have the proper hard to test eGPU so maybe you could possibly test it for the repo?

**Comment by velaar** [comment]
Ok. Tested your newer build with my eGPU - works fine :) BIOS 1.38, High Sierra. 

Also can you add to readme that a native BCM943602CS fits X1C6 with an adapter? I run it for a couple months already, continuity/handoff/phone calls work well. Routed the third antenna to the LTE antenna spot and no issues. Can get over 900mbit/s close to the router. Although sometimes bluetooth doesn't wake from sleep.

**Comment by philffm** [comment]
Guys, does your eGPU work with hot plug or just in PCI mode, so needs a reboot before plug/unplug? If hotplug works for you, I will definitly try your config.

**Comment by velaar** [comment]
Needs a reboot, never had the time to figure out the hotplug

**Comment by philffm** [comment]
Thanks for your quick reply! Same here, never had the time to dive that deep to the topic - also using AirDrop while the eGPU is connected, causes the computer to reboot (so I disabled AirDrop for that scenario) - Does this happen to you as well? Apart from the AirDrop case, the computer either reboots very often or just keeps on running for hours. (Don't know why - Thermal conditions / loose connection?) - My old MacBook behaved similarly but did not crash / reboot, but just reconnect the screens.

This might get us futher in the hot plug story:
https://github.com/osy86/HaC-Mini/blob/master/details/thunderbolt-3-fix.md

**Comment by tylernguyen** [comment]
No longer a concern, closing issue.
