### ISSUE TITLE
some changes to go into opencore for note

### ISSUE THREAD

**Issue by jenova384** [tylernguyen/x1c6-hackintosh#110]
Firstly thinks to tylernguyen for this almost perfect EFI. It reduces huge works for hackintosh process of x1c6.

Here is the only one problem I have and the solution.
By fully copy this EFI I cannot go into opencore to install macos, until making the following changes,

Misc-Boot-ShowPicker                         No -> Yes
Misc-Debug-Target                                 3 -> 0
Misc-Security-ScanPolicy           983299 -> 0

Followings are the differences between my hardware and tylernguyen's,

CPU                                                                i7-8550u
SSD (for win10)                                             Samsung 970 EVO    500GB
WWAN (2nd SSD for macOS)                      TOSHIBA-RC100       224GB

**Comment by tylernguyen** [comment]
> Firstly thinks to tylernguyen for this almost perfect EFI. It reduces huge works for hackintosh process of x1c6.
> 
> Here is the only one problem I have and the solution.
> By fully copy this EFI I cannot go into opencore to install macos, until making the following changes,
> 
> Misc-Boot-ShowPicker No -> Yes
> Misc-Debug-Target 3 -> 0
> Misc-Security-ScanPolicy 983299 -> 0
> 
> Followings are the differences between my hardware and tylernguyen's,
> 
> CPU i7-8550u
> SSD (for win10) Samsung 970 EVO 500GB
> WWAN (2nd SSD for macOS) TOSHIBA-RC100 224GB

@jenova384 

Thank you for the compliments.

The main EFI folder is not meant to be used for install. Such is why an Install-EFI exists. The latter is should be used on initial install and configuration, especially since SIP will need to be disabled for certain things during initial setup but should be enabled on daily usage.
