### ISSUE TITLE
Wireless Sidecar and Continuity don't work on latest EFI

### ISSUE THREAD

**Issue by erdemoney** [tylernguyen/x1c6-hackintosh#111]
The Sidecar menu in System Preferences shows "no devices" when trying to connect my iPad wirelessly. However using a usb to lighting cable, the iPad shows up just fine and Sidecar works. Wireless connection also works as expected on an authentic Mac so I'm assuming this is a Hackintosh issue rather than a macOS issue. The iPad being used is an 8th gen iPad.

I'm using BCM94360CS2 card so I'm wondering if this issue is because the Mac that this card is from isn't supported for Sidecar even though the SMBIOS is compatible.

1. Connect iPad to same wifi as hackintosh. Enable bluetooth and handoff on both devices and ensure both devices are using the appleid.
2. Connect iPad to Hackintosh via lighting cable
3. Go to Finder and "trust" iPad
4. Unplug iPad
4. Go to System Preferences -> Sidecar
5. See "no devices" in Connect to menu.

I'm using the most recent EFI with the changes for unmodded bios.

edit: It appears that Continuity does not work for me either.

**Comment by erdemoney** [comment]
I can't receive or send SMS messages either which is a continuity issue as well. I think this may be related to #109 as all the continuity features were working for me up until I did a clean install of Big Sur with the second most recent EFI.

**Comment by tylernguyen** [comment]
@erdemoney 

Sidecar is working fine for me on the latest EFI, macOS, and iPad OS. Tested with an iPad Mini.

The card you are using is native so it is not a Hackintosh issue. Check to make sure that you are signed in to iCloud on both devices using the same account.

https://support.apple.com/en-us/HT210380

```
- Both devices must be signed in to iCloud with the same Apple ID using two-factor authentication.
- To use Sidecar wirelessly, both devices must be within 10 meters (30 feet) of each other and have Bluetooth, Wi-Fi, and Handoff turned on. Also make sure that the iPad is not sharing its cellular connection and the Mac is not sharing its Internet connection.
- To use Sidecar over USB, make sure that your iPad is set to trust your Mac.
```

**Comment by erdemoney** [comment]
Just did yet another clean install and it works now! My bluetooth preference pane seems to constantly show up at boot as well. Not sure what exactly was going on, but glad it works. Thanks for the response and continued work on this repo.
