### ISSUE TITLE
Unlock with Apple Watch

### ISSUE THREAD

**Issue by buyddy** [tylernguyen/x1c6-hackintosh#112]
Does anyone have perfect working unlock with Apple Watch? I can unlock it only if the computer does not go to sleep. 

Seems like a problem that requires disabling serial port in BIOS.

https://www.tonymacx86.com/threads/unlock-with-apple-watch-not-working-in-catalina.287027/page-9#post-2183601

Not sure if there is a way to do it in X1C6 mod bios.

**Comment by tylernguyen** [comment]
@buyddy 

Continuity features are related to your network card, what are you using?

**Comment by buyddy** [comment]
> @buyddy
> 
> Continuity features are related to your network card, what are you using?

I am using BCM94352Z. I can unlock the laptop if I don't go into sleep. Sleep or reboot breaks it. All other Continuity feature seems fine. Although I do have issue with personal hotspot too.

**Comment by usr-sse2** [comment]
The same (Auto Unlock only works until sleep, Personal Hotspot doesn't connect) on Dell Latitude 7490 2-in-1 with BCM94356Z.

**Comment by usr-sse2** [comment]
UPD: I've disabled the serial port using setup_var in modGRUBShell, got no improvements.

**Comment by Hochiss** [comment]
> Does anyone have perfect working unlock with Apple Watch? I can unlock it only if the computer does not go to sleep.
> 
> Seems like a problem that requires disabling serial port in BIOS.
> 
> https://www.tonymacx86.com/threads/unlock-with-apple-watch-not-working-in-catalina.287027/page-9#post-2183601
> 
> Not sure if there is a way to do it in X1C6 mod bios.

same issue here with DW1830/BCM943602BAED, esp. after sleep Airdrop doesn't work anymore. But handsoff w.r.t. webpage from iPhone to macOS popup works. 

Is this related to HW( WiFi or BT) or SW/FW injection? 

anyone has a perfect working e.g HW case to share?  How to debug where the issue comes?

**Comment by tylernguyen** [comment]
Hello,

I never paid much attention to this issue because I'm planing to abandon the native cards and switch to something like the AX200 soon.

So I do not want to invest much time in this issue if I'm going to switch my network card anyway.

Preferably, when OpenIntelWireless 2.0.0 comes out with improved seed, I'll switch to that on my own laptop as well as the repo setup.

Until then (at which point I can make a recommendation), this issue is suspended.
