### ISSUE TITLE
Color binding on FHD touchscreen display

### ISSUE THREAD

**Issue by finisi** [tylernguyen/x1c6-hackintosh#113]
I am experiencing color binding on built-in FHD touchscreen display. However, external monitor connected through HDMI doesn't have this issue. Applied non-touchscreen EDID, but that didn't resolve the issue. I am guessing the issue has something to do with my screen being non-HDR, but I may be wrong. If someone could point me to the direction to research upon I would be grateful.

macOS 11.1, Open Core 0.6.4
up-to-date kexts from here

**Comment by tylernguyen** [comment]
@finisi 

Unfortunately, I do not have this problem and I do not have the same display model to test/tackle this problem. If I'm not mistaken, @benbender also had this issue on his specific display. But I'm not sure what he did/found out. Also, it seems that there are other thinkpads out there that have this issue so you may have better luck looking at other machines' repos. Meanwhile, I'll leave this issue here and mark it as wanted so others can contribute.

Lastly, it would be useful to have a picture of the problem.

**Comment by EETagent** [comment]
Yes, you can encounter colour banding on some Kaby Lake Refresh machines with Full HD screen like my T480 for example. Only working fix at this time is to apply patches for Skylake instead. To make this easier, @benbender modified WhateverGreen so you wouldn't have to force Skylake universally using Lilu's  `-lilucpu`

https://github.com/EETagent/T480-OpenCore-Hackintosh/issues/32

**Comment by tylernguyen** [comment]
@finisi 

Per @EETagent's note, try this `WhateverGreen` build https://github.com/EETagent/T480-OpenCore-Hackintosh/issues/32#issuecomment-709182915

@EETagent Thank you.

**Comment by tylernguyen** [comment]
@finisi 

Any updates?

**Comment by finisi** [comment]
Sorry, for going AWOL. I got corona or some other virus. I tried to spoof Skylake but apparently did something wrong cause everytime I changed values of ig-platform-id and device-id I got kernel panic. I think I'd better ask benbender on the thread the EETagent pointed out. Below is the example of color banding
![image](https://user-images.githubusercontent.com/73966014/105134323-6f533980-5b18-11eb-81a6-52ab3a33d844.png)

**Comment by toshinori8** [comment]
Any updates with this problem? I have thesame situation with S40-40 AIO lenovo on i5-4690S processor HD 4600. Tested on High Sierra to Ventura.

**Comment by Mifaxav** [comment]
i have the FHD touchscreen rn and yeah there are a couple issues... i can test things out if needed

**Comment by mgrimace** [comment]
I have the FHD touchscreen and wondering if anyone has been able to resolve the banding
