### ISSUE TITLE
Adding unmoddedBIOS plist to config.plist?

### ISSUE THREAD

**Issue by kskim7** [tylernguyen/x1c6-hackintosh#114]
Hey bro, thanks for your work,
I'm using an unmodded X1C6 to install Big Sur.
So, following your guide, I must add the lines on the DeviceProperties onto the original config.plist you uploaded,
or should I change the whole DeviceProperties lines with the unmoddedBIOS.plist lines?
please save me bro!!

**Comment by erdemoney** [comment]
Append the lines to the existing DeviceProperties section

**Comment by tylernguyen** [comment]
@kskim7 

@erdemoney is correct. Please merge the two files. You shouldn't need to remove anything from `config.plist`.

**Comment by kskim7** [comment]
Thank you @erdemoney and @tylernguyen !!!
