### ISSUE TITLE
OS selection menu?

### ISSUE THREAD

**Issue by kskim7** [tylernguyen/x1c6-hackintosh#115]
Thanks for your guide and solution to my question regarding merging unmoddedbios.plist to config.plist.
It's working perfectly so far.
I love how it looks and sounds like a real Mac during boot, but somehow it doesn't let me choose which drive I would boot from.
Is this on purpose or something that I can make change to the settings?
Is it possible to change the settings to choose other drives during booting?
And how?? I can't search it on the internet (due to my poor search skills).
Sorry for bothering you.

**Comment by kskim7** [comment]
Oh, and, another thing,
when after sleep and wakes up, the wifi is off and it takes a few minutes until it turns back on.
Do you have that issue too?

**Comment by tylernguyen** [comment]
@kskim7 

Press Esc during boot will take you to boot selection screen.

"when after sleep and wakes up, the wifi is off and it takes a few seconds until it turns back on."

I'm not quite sure about this issue. I would check card you're using and check macOS setings.

**Comment by kskim7** [comment]
Thanks! 
I'll use ESC during boot for boot options. 
And the wifi card, I'm using BCM94360NG.
In fact, the issue appears not every time I wake the computer. 
Let me check in what condition the issue appears.

**Comment by kskim7** [comment]
btw, don't you have any trouble with using trackpoint?
the pointer jumps when moving, making unable to point precisely.
using touchpad is okay, but only the trackpoint.
perhaps a change to voodoops2controller.kext would solve the problem??

**Comment by tylernguyen** [comment]
> 
> 
> Thanks!
> I'll use ESC during boot for boot options.
> And the wifi card, I'm using BCM94360NG.
> In fact, it seems the issue appears not every time I wake the computer.
> when I wrote the last comment on this issue, I saw it happen twice in a row, but now, not anymore.
> Let me check under what condition the issue appears furthermore.

I would switch to a native card with an adapter. They work without any headaches.

**Comment by kskim7** [comment]
afik, bcm94360ng is working almost equivalent to bcm94360cs2.
Anyways, the wifi issue doesn't occur any longer.
Now I just need a more precise movement for trackpoint. 
I guess I'll have to test with different versions of VoodooPS2Controller and VoodooRMI. 
Thanks for your support!
