### ISSUE TITLE
4K UHD with Vanilla BIOS 1.50, 1.49 or 1.43 in 10.15 or 11.2

### ISSUE THREAD

**Issue by adwiens** [tylernguyen/x1c6-hackintosh#117]
I'm new to hackintoshing so I could be missing something obvious. That said, I was able to follow the rest of the directions, and everything else that I care about is working on my machine.

Things I tried:

- Tried the latest Catalina as of 2/13/21, and also Big Sur versions 11.2 and 11.2.1.
- Tried running the command from the original thread and cleared NVRAM, no luck. The command didn't seem to work in 11.2, but did in Catalina. (In 11.2, it returned immediately with a "deprecated" warning.)
- Downgraded BIOS twice to see if that was the issue without luck.
- Tried 3 different 4K monitors via both a USB-C to DP adapter and also a USB-C to HDMI 2.0 adapter.
- With and without HiDPI mod linked from this repo, with and without EDID patch.
- Restarting lots of times throughout the process, plugging and un-plugging the cable to the monitor, etc.
- Used SwitchResX to try to set the resolution but got "Invalid?" for anything res above 2560x1440

For now I'm going to use 2560x1440 but 4K would be much better.

I would mod my BIOS, but I'm hesitant to do that yet in case I missed something else that's the actual problem.

Here is my config.plist: https://gist.github.com/adwiens/516e42238d8c5a0297ee029e1052d096

**Comment by tylernguyen** [comment]
EDID and HiDPI patches do not affect external monitors, they are meant for the internal display.

The patch you are looking for is this:
https://github.com/tylernguyen/x1c6-hackintosh/blob/master/patches/OpenCore%20Patches/4K-Output-wo-BIOSmod.plist

**Comment by adwiens** [comment]
> EDID and HiDPI patches do not affect external monitors, they are meant for the internal display.
> 
> The patch you are looking for is this:
> https://github.com/tylernguyen/x1c6-hackintosh/blob/master/patches/OpenCore%20Patches/4K-Output-wo-BIOSmod.plist
> 
> For external display, refer to the framebuffer section, and keep in mind that the patch above is untested in Big Sur.

Yes of course, I only tried those as a last resort.

That patch you linked to is in my plist already.

And again, I said I tried this in Catalina as well and it didn't work.

**Comment by adwiens** [comment]
I'm no longer on Catalina so I probably won't go back to try making the vanilla BIOS approach work at this point. But I can pretty easily flash the BIOS.

Will BIOS flashing make 4K work for sure? Does that approach rely on other patches as well or all I have to do is flash the BIOS according to the steps? Does the flashing the BIOS make 4K work in Big Sur or just Catalina?

**Comment by tylernguyen** [comment]
> 
> 
> I'm no longer on Catalina so I probably won't go back to try making the vanilla BIOS approach work at this point. But I can pretty easily flash the BIOS.
> 
> Will BIOS flashing make 4K work for sure? Does that approach rely on other patches as well or all I have to do is flash the BIOS according to the steps? Does the flashing the BIOS make 4K work in Big Sur or just Catalina?

https://github.com/tylernguyen/x1c6-hackintosh/blob/master/docs/1_README-HARDWAREandBIOS.md

You will have to change some settings but it should work after that.

**Comment by sarpulas** [comment]
I've stayed on an older revision (https://github.com/tylernguyen/x1c6-hackintosh/commit/7a8e9c74f9ff2ef52512404045b0c43bccc0e03a) as a workaround since I ran into the same issue and I can't flash my BIOS nowadays because I can't open up the machine, the screws are stripped from having done that poorly a few times. That revision is missing a lot of the newer improvements but still works well enough with Catalina & 3840x1600 display.

**Comment by adwiens** [comment]
Closing this since 4K is working for me after flashing the BIOS and it looks like there is a solution for vanilla BIOS - thanks @sarpulas
