### ISSUE TITLE
Linux dual boot issues

### ISSUE THREAD

**Issue by erdemoney** [tylernguyen/x1c6-hackintosh#118]
I installed linux on a separate drive in the WWAN slot as suggested and it’s been working well. However I recently did a macOS upgrade and reset the NVRAM as suggested. Linux now does not show up in the boot (F12) menu (it never showed up in the opencanopy menu) and I can't figure out how to boot it now. 

On doing some research, it seems this is expected behavior as the EFI entries in the boot menu are stored in NVRAM. This guide has instructions on setting up a Linux dual boot and suggests resetting NVRAM before updates so I was hoping that someone has already figured out a solution for this and can give me a hand.

edit: it seems that the docs don’t suggest resetting NVRAM before updates anymore

**Comment by erdemoney** [comment]
Recovered my boot entry by running the efibootmgr command [here](https://github.com/dortania/OpenCore-Multiboot/blob/master/oc/linux.md) from a live usb. Still wondering if anyone has a better solution though. Is there any way to have Linux show up in the OC boot manager?

**Comment by Porco-Rosso** [comment]
I have been running rEFInd as an intermediary, and has worked great with Win/MacOs dualboot, however that's on one drive.
rEFind -> OC or Windows boot manager

**Comment by tylernguyen** [comment]
@erdemoney 

@Porco-Rosso's suggestion may be a better solution for you as clearing NVRAM will remove the boot entry on the WWAN drive. I'll add a note of that behavior into the docs on this repo.

Additionally, dortani's latest docs is updated with multi booting suggestions
https://dortania.github.io/OpenCore-Multiboot/oc/linux.html#method-a-chainloading-a-efi-bootloader-grub2-systemd-boot

I recommend you take a look at that page.

I will also add that resource into the docs on the next repo update.
