### ISSUE TITLE
HDMI port is connected but not displayed.

### ISSUE THREAD

**Issue by HsunGong** [tylernguyen/x1c6-hackintosh#119]
**Describe the bug**
hdmi port does not work.

**Expected behavior**

hdmi port is detected, but not display any color.
I plugin in a monitor with hdmi port, this monitor is detected in `preference`, but not display any color.
However, if I use type-c port, this monitor work correctly.

**Screenshots**

![image](https://user-images.githubusercontent.com/32933986/109596421-31065c80-7b51-11eb-8c36-939d1d145893.png)

**Tried**

Changed `EDID in issue[#60](https://github.com/tylernguyen/x1c6-hackintosh/issues/60)`

**Version**

- OC0.6.1 with macos 10.15.6
- OC 0.6.6.with macos 10.11.1

both versions do not work.

**Comment by tylernguyen** [comment]
@HsunGong 
Which display panel do you have?

The EDID patch depends on that.

**Comment by HsunGong** [comment]
Do not know much about it, I use a type-c to hdmi port, and then it is connected.

**Comment by tylernguyen** [comment]
@HsunGong 

https://github.com/tylernguyen/x1c6-hackintosh/tree/master/patches/Display%20Patches

Apply the appropriate HDMI patch and HDMI hotplug should work.
