### ISSUE TITLE
Unable to get webcam working

### ISSUE THREAD

**Issue by mattbajorek** [tylernguyen/x1c6-hackintosh#12]
Thank you so much for having your EFI folder publicly available.  I have the same laptop as you have and was able to get everything working by just copying your EFI folder. The only issue is the webcam is not working. Do you have any advice on fixing it?

**Comment by matthew-bajorek-fastfin** [comment]
Ended up getting it working by using KextBeast to install BrcmFirmwareRepo.kext, BrcmPatchRAM2.kext, and BrcmFirmWareData.kext (placed on desktop and installed to /System/Library/Extensions)

**Comment by tylernguyen** [comment]
Hi, I'm not sure why those kexts enabled your webcam. Those kexts are meant for wireless and Bluetooth Webcam should be enabled with USBInjectAll and the included dsdt.
