### ISSUE TITLE
Endless reboot after change OpenCore of install USB to Opencore for daily use

### ISSUE THREAD

**Issue by ChipXinhDep** [tylernguyen/x1c6-hackintosh#120]
I successfully install BigSur on SSD at WWAN and make dual boot with rEFInd. But it only work if I use EFI folder of installer USB (your Opencore for installer). If I change that EFI folder to your daily use EFI Opencore folder Bigsur keep crashing at 30% loading of progress bar with Apple Logo above, then my laptop restart to rEFInd screen. 
I have merged 2 files config.plist of unmod and mod bios,  generated my own CPUFriendDataProvider but it is still not work.
My X1C6 has Intel Core i5-8250U, 14.0" FHD 1920x1080 LED IPS, Bcm94360CS2. 
Thanks in advance. 
![ezgif com-gif-maker](https://user-images.githubusercontent.com/67351660/109993181-98353400-7d3e-11eb-9573-3dae33cfa8c1.gif)
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/67351660/109993677-21e50180-7d3f-11eb-957d-81c57d1e6b97.gif)

**Comment by tylernguyen** [comment]
@ChipXinhDep 

Did you figure out what was wrong?

**Comment by ChipXinhDep** [comment]
ah yes I found it. I tried to clear Nvram after replace EFI folder and it worked perfectly. xD
