### ISSUE TITLE
can we use nvram reset in OC?

### ISSUE THREAD

**Issue by Sher1ocks** [tylernguyen/x1c6-hackintosh#121]
hi. i wonder this true.
can we use nvram reset in X1C6 from OC?
i saw some thinkpad model has brick when using OC nvram rest. if happen brick, should be replace motherboad. 

how about this issue un X1C6? No problem?

thanks in advance

**Comment by tylernguyen** [comment]
@Sher1ocks 

It should be safe. I have used it before without any problems. Though I can't guarantee anything.

**Comment by Sher1ocks** [comment]
> @Sher1ocks
> 
> It should be safe. I have used it before without any problems. Though I can't guarantee anything.

thanks
what is your bios version?
x1c6 latest version is 1.50.
