### ISSUE TITLE
Big Sur recovery / updater / installer not working with AppleBacklightSmoother

### ISSUE THREAD

**Issue by b00t0x** [tylernguyen/x1c6-hackintosh#122]
**Describe the bug**
When AppleBacklightSmoother.kext enabled, Big Sur recovery / updater / installer cause reboot loop. After update finished, it becomes fine with this kext.

**To Reproduce**
- Try to update Big Sur to 11.2.3 with AppleBacklightSmoother.kext enabled.
- Try to boot Big Sur 11.2.3 recovery with AppleBacklightSmoother.kext enabled.

**Environment**
modded BIOS 1.49 + March Update (OC0.6.7) + DW1560 patches + Big Sur 11.1 → 11.2.3

**Backgrounds**
AppleBacklightSmoother has some bugs to fail Big Sur booting.
- https://github.com/hieplpvip/AppleBacklightSmoother/issues/12
- https://github.com/acidanthera/bugtracker/issues/1471
- https://github.com/EETagent/T480-OpenCore-Hackintosh/issues/76

**Tried**
I built the AppleBacklightSmoother.kext from [this repo](https://github.com/Ubsefor/AppleBacklightSmoother) but still have same problem.

**Solution**
Workaround is clear, we should disable AppleBacklightSmoother.kext. EFI-install_USB does not contain this kext so installing Big Sur does not have the problem, but it makes trouble when updating Big Sur.

I leave it to you to disable the kext by default or enable it and then add notice to the README.

**Comment by tylernguyen** [comment]
@b00t0x 

Thank you so much for bringing this to my attention. I've verified this bug.

I'll give this kext until the next Acidanthera cycle to update. If not by then, I'll remove this kext from the repo.

Thanks again.

**Comment by tylernguyen** [comment]
Removed from repo as of 17f93f8

Will re-add once the kext's issue is fixed.

**Comment by zhen-zen** [comment]
https://github.com/acidanthera/bugtracker/issues/1471
