### ISSUE TITLE
What's the status of Type-C hot plugging?

### ISSUE THREAD

**Issue by TakaiSaisei** [tylernguyen/x1c6-hackintosh#123]
I am considering purchasing this laptop for the specific purpose of installing a hackintosh. So I want to know if it will be usable in my environment.
At home I have a ThinkVision T24h-20 Type-C monitor. It supports DisplayPort over USB Type-C and has a USB hub.
In README USB 3.1 hotplug marked as WIP - do I understand correctly that I will not get any video or available USB ports after plugging in the cable until I reboot? Will the DisplayPort over USB Type-C work at all? I know that there're no any problems with native Macs, but maybe the situation is different for hackintosh.

**Comment by tylernguyen** [comment]
@TakaiSaisei 

It is strictly USB 3.1 hotplugging that is buggy right now. DisplayPort and USB 3.0 should function normally.

Yes, if you need to transfer data over USB 3.1, you would have it plug it in before boot.

As for ETA, I do not have one. My 3.1 testing peripherals is limited and I don't need it personally so I haven't really focused on it. Secondly, it is connected to Thunderbolt which is a headache in and of itself.

So you should get video and USB over Type-C. Simply, the USB speed will be 3.0, not 3.1
