### ISSUE TITLE
VirtualSMC does not control fans

### ISSUE THREAD

**Issue by HsunGong** [tylernguyen/x1c6-hackintosh#124]
Load VirtualSMC and Lilu correctly, however can not detect fans speed with `Mac Fan Control`.

![image](https://user-images.githubusercontent.com/32933986/112624130-28f7bf00-8e68-11eb-9184-d002a0879ddc.png)

![image](https://user-images.githubusercontent.com/32933986/112624163-390f9e80-8e68-11eb-8543-f5101f636668.png)

**Comment by velaar** [comment]
You need YogaSMC for fan control.

**Comment by tylernguyen** [comment]
As @velaar said,

Fan speed is controlled via YogaSMC App. Please refrain from creating issues until you have throughly read the docs.
