### ISSUE TITLE
Fn Keys does not work properly.

### ISSUE THREAD

**Issue by HsunGong** [tylernguyen/x1c6-hackintosh#125]
Fn+F1~F12 can be designed to control some functions.

However, I update the config.plist, and `F4-F12` does not work at all.
And `F1-F3` can still control the volume.

More interestingly, `F4` aims to `ctrl+space`(Maybe some mapping is set).

### Patches:
![image](https://user-images.githubusercontent.com/32933986/112624687-e84c7580-8e68-11eb-9b78-358f59575e82.png)

### keyboard.aml(remove .txt)

[SSDT-Keyboard.aml.txt](https://github.com/tylernguyen/x1c6-hackintosh/files/6211415/SSDT-Keyboard.aml.txt)

**Comment by velaar** [comment]
Why are you using those patches? You don’t need them with YogaSMC.

**Comment by tylernguyen** [comment]
@HsunGong 

https://github.com/tylernguyen/x1c6-hackintosh/blob/master/docs/3_README-other.md

As @velaar said, you do not need those patches. Use YogaSMC.
