### ISSUE TITLE
Screen backlight don't work

### ISSUE THREAD

**Issue by cralex11** [tylernguyen/x1c6-hackintosh#130]
On apple logo appears screen backlight don't work, I hardly see the logo and sistem have been booted, but brightness is very very low. Does anyone know what's the problem?

**Comment by tylernguyen** [comment]
@cralex11 

Sorry for the late reply,

Can you provide a picture? perhaps a video? 

I would also need a copy of your EFI. and settings. Your particular problem seems unique.

**Comment by ljurcisin** [comment]
I have same issue since last commit

**Comment by tylernguyen** [comment]
It's like related to https://github.com/tylernguyen/x1c6-hackintosh/issues/129

Try the newest commit and let me know.

**Comment by TakaiSaisei** [comment]
@tylernguyen I can confirm that backlight control is still not working.

**Comment by tylernguyen** [comment]
@TakaiSaisei 

Please reset your EFI to the repo and clear CMOS. My backlight is functioning normally.

If not,
Please provide a copy of your EFI and appropriate boot and OpenCore logs

**Comment by lucas-www** [comment]
> @tylernguyen I can confirm that backlight control is still not working.

I also have the problem in The latest update.

**Comment by tylernguyen** [comment]
I can't diagnose the problem myself because backlight control is working on my personal machine.

Please let me know the last working commit.

**Comment by tylernguyen** [comment]
@lucas-www @TakaiSaisei @cralex11 @ljurcisin 

Please try this patch and let me know if that fixes your problem.


[SSDT-PNLF.aml.zip](https://github.com/tylernguyen/x1c6-hackintosh/files/6543500/SSDT-PNLF.aml.zip)

**Comment by lucas-www** [comment]
> @lucas-www @TakaiSaisei @cralex11 @ljurcisin
> 
> Please try this patch and let me know if that fixes your problem.
> 
> [SSDT-PNLF.aml.zip](https://github.com/tylernguyen/x1c6-hackintosh/files/6543500/SSDT-PNLF.aml.zip)

<img width="300" alt="image" src="https://user-images.githubusercontent.com/68903281/119630833-e8a1c680-be41-11eb-98e8-e2494a5aca5d.png">

It still doesn't work.

**Comment by tylernguyen** [comment]
Do you have hidpi patch enabled?

**Comment by lucas-www** [comment]
I just use this tool, the link is https://github.com/xzhih/one-key-hidpi, no others patches are applied.

**Comment by Porco-Rosso** [comment]
Not sure if it is connected, but my ability to control has also disappeared. Hotkeys don't do anything despite Karabiner recording backlight-increment/decrement. And on the display settings no brightness slider is present
I also have used the same script as lucas-www in the past. 

![image](https://user-images.githubusercontent.com/7024527/120077255-2c9b0280-c0b2-11eb-821a-2f72b1b40c32.png)

**Comment by lucas-www** [comment]
<img width="868" alt="image" src="https://user-images.githubusercontent.com/68903281/120878073-a5d3b180-c5ec-11eb-9c56-bc85c6b8ab92.png">

After adding this ACPI section, Everything gets fine for me.  @tylernguyen

**Comment by lucas-www** [comment]
@tylernguyen The latest SSDT-PNLF.aml still has problem for adjusting brightness, But the last SSDT-PNLF.aml works well.  The OpenCore Resource directory path changed in OpenCore 0.7, but latest update doesn't update this directory, I change this for myself.

**Comment by tylernguyen** [comment]
@lucas-www 

Did you remove AppleBacklightSmoother?

**Comment by jkwroi24io9342fsdjklAdf** [comment]
Yes,I remove it.

**Comment by lucas-www** [comment]
@tylernguyen Yes, I do removed AppleBacklightSmoother

**Comment by tylernguyen** [comment]
> 
> 
> @tylernguyen Yes, I did removed AppleBacklightSmoother

Hm..

Can I get a copy of your EFI?

**Comment by lucas-www** [comment]
@tylernguyen Of course, The link is: https://github.com/lucas-www/x1-carbon-gen6.git. I modified some files and configurations base on your repository, if you get this copy and need me to delete this repository , just tell me please. 
thank you.
By the way, I solved the HDMI output(two displays) and black screen problems for myself  by change some parameters. I use this laptop to do my daily work. It's very good at present. thank you for your perfect project.
![image](https://user-images.githubusercontent.com/68903281/121649561-46354480-cacb-11eb-9d88-89f38eb5c95f.png)

![image](https://user-images.githubusercontent.com/68903281/121649621-551bf700-cacb-11eb-8fe7-e37ce86fe82e.png)

**Comment by tylernguyen** [comment]
@lucas-www 

Take a look at the latest commit and let me know.

**Comment by lucas-www** [comment]
Okay, I will verify this update if I have free time.

**Comment by lucas-www** [comment]
I update to the latest commit, It has no problem now.
