### ISSUE TITLE
_PS0 ACPI Question

### ISSUE THREAD

**Issue by 1Revenger1** [tylernguyen/x1c6-hackintosh#131]
I'm porting over the thunderbolt/USB patch set over to my X1 Extreme since they are pretty similar devices. I noticed that the patches [rename _PS0 and _PS3](https://github.com/tylernguyen/x1c6-hackintosh/blob/17f93f8d5eccda6cf35b608526ab4e682785ad1c/patches/OpenCore%20Patches/XHC1.plist#L45-L114) within the \_SB.PCI0.XHC device, but you do not [reimplement them anywhere](https://github.com/tylernguyen/x1c6-hackintosh/blob/master/patches/SSDT-XHC1.dsl#L213-L403). Is this on purpose or am I missing it elsewhere within the patch set?

**Comment by tylernguyen** [comment]
@1Revenger1 

Sorry for the late reply,

I believe it was just some legacy carry over back when we were testing various power states and energy modes. I think you can safely ignore it.
