### ISSUE TITLE
[Question] Is it normal that my ADT-Link Thunderbolt 3 eGPU is NOT considered as an eGPU, but a PCIe device?

### ISSUE THREAD

**Issue by kushwavez** [tylernguyen/x1c6-hackintosh#132]
**Description:**

I am using an ADT-Link Thunderbolt 3 adapter <a href=https://www.aliexpress.com/i/4000340228749.html>(ADT-Link R43SG-TB3 PCIe x16)</a> for my AMD RX 470 4 GB video card. It is working fine, plug & play. 

However it is not popping up on macOS as an External GPU, but a regular PCIe device over Thunderbolt 3. (same on macOS Mojave and Catalina too)
![Screenshot 2021-05-14 at 11 08 07](https://user-images.githubusercontent.com/33935034/118248535-af15a680-b4a4-11eb-86f5-10954d3493f4.png)
![Screenshot 2021-05-14 at 11 08 54](https://user-images.githubusercontent.com/33935034/118248660-de2c1800-b4a4-11eb-9a2e-506ee844d366.png)
![Screenshot 2021-05-14 at 11 09 07](https://user-images.githubusercontent.com/33935034/118248675-e2583580-b4a4-11eb-92e5-7a098c72fb91.png)
![Screenshot 2021-05-14 at 11 09 14](https://user-images.githubusercontent.com/33935034/118248689-e5532600-b4a4-11eb-9ff5-10f9487602d2.png)

I also see the similar result on Windows too:
![winpcie](https://user-images.githubusercontent.com/33935034/118249451-bb4e3380-b4a5-11eb-827d-9404cbd5fb92.PNG)

And because of that, I can't set Applications to use my eGPU, because the "Prefer External GPU" option isn't there in "Get Info". 

The Expected behaviour would be like this:
<img width="281" alt="c14eb776-28f0-4ce7-aba7-5a68cd69a8d0" src="https://user-images.githubusercontent.com/33935034/118249082-4ed33480-b4a5-11eb-890c-08d33cf5a68a.png">

Then you can select "Prefer External GPU"
![macos-mojave-macbookpro-finder-app-info-prefer-external-gpu-selected](https://user-images.githubusercontent.com/33935034/118249168-66aab880-b4a5-11eb-9694-3fa1c18e6622.jpg)
And the app/game will launch on your Internal screen, BUT using the eGPU.

So because of it's looks like the same on Windows (but there I can select Apps to use RX 470), I'm not sure that this is normal or not, and would like to ask people with for example Razer Core X to test it, and see if it's the same or not. If the same, then I think it is not normal, and should be investigated.

If not the same as mine, and their GPU is recognised as eGPU and they can select "Prefer ... " too, then it is normal and it's the way my ADT-Link recognised and works, so it's not a "bug".

The problem with this is that I can only play my games with eGPU IF I have an external monitor plugged in, so I need to set the external monitor as primary display and launch the game on it. If there is no external monitor plugged into the RX 470, then I can't use it since Apps don't have "Prefer External GPU" option. 
However, apps like Final Cut can recognise it and use it just fine.

Another annoyance is that when I unplug it (using the menu, or just simply un-plug it doesn't matter), the notebook will freezes with high CPU usage, and I have to force-restart. So that is another question for all of you with eGPU, to verify that this is normal or not. 
Regular USB-C Gen 2 devices are working, can be removed & re-plugged without the need of a restart. I can't test more because I just don't have any other TB3 devices.

I'm know it's a bit long, but just a quick test would be enough.
Thanks.

**Comment by tylernguyen** [comment]
@kushwavez 

Unfortunately, I do not have that adapter nor an AMD GPU to do any testing. 

It looks like a direct connection to the m.2 so that will always be detected as PCIe.

I would say take a look at the Thunderbolt patch and play around with that, but even then, it seems like a tough issue.

Again, I'm sorry I can't help you much.

**Comment by kushwavez** [comment]
Just a note about this:
Just tested with other notebooks and the result was the same. 
The "issue" is that macOS does not recognise ADT-Link TB adapter as a supported adapter like the Razer Core X, and because of that it'll function the way I mentioned.
