### ISSUE TITLE
USB-C(3.1) hotplug issue + Boot messages

### ISSUE THREAD

**Issue by kskim7** [tylernguyen/x1c6-hackintosh#139]
I assume that this hotplug issue has been almost over, 
but I cannot find it in the closed issues, so I just made a new one.

I got an issue with using a USB-C(3.1) external ssd from samsung.
When unplugged and plugged back on to the machine, it doesn't recognize the drive.
My settings in the BIOS Thunderbolt 3 setting parameters is both 'Disabled'.

I also have a USB 3.0 drive which is USB-A, which is also not recognized when plugged back,
it becomes recognized only when the 'Thunderbolt(TM) Device' is Enabled.

I made no changes to the config.plist except the lines for unmodded bios. 
Any clue??

And one more thing,

I got these messages during boot. Do you know what they are?
<img width="742" alt="스크린샷 2021-07-17 오후 12 16 17" src="https://user-images.githubusercontent.com/78552041/126023770-7fb6513e-ca57-4f2c-a5f7-b81b8af6d404.png">

**Comment by tylernguyen** [comment]
About the boot messages:
The repo is on OC 0.7.0

What OC version are you on?

Regarding 3.1 hot-plug, it will likely never be fixed. It's due to inherent instability of the controller in macOS. 

I recommend you cold boot 3.1 storage if you need it.

**Comment by kskim7** [comment]
I'm using your repo just as is. So it should be OC 0.7.0?

Oh, nope, it says it's 0.6.3. I should update OC. Thanks for the info.

And the Hot-plug issue, I assume it has something to do with power consumption?
When I hot-plug in, a message appears that there's a device that's requiring too much power.


FIY, a user named @kushwavez has solved this issue with his Clover setup. 
(I've been using it so far and had no problem with hot-plug)
Perhaps you could review his files if you need to??
https://github.com/kushwavez/lenovo-x1c6-clover-efi

**Comment by tylernguyen** [comment]
@kskim7 

I checked out his repo and it seems he's using my patches.

As I've stated before, the inherent controller state is unstable. Hence, it may hotplug sometimes fine and not other times. Morevoer, it's a case-by-case issue with different devices. So I cannot exhaustively test everything.

Sorry.

**Comment by kushwavez** [comment]
> FIY, a user named @kushwavez has solved this issue with his Clover setup.
> (I've been using it so far and had no problem with hot-plug)
> Perhaps you could review his files if you need to??
> https://github.com/kushwavez/lenovo-x1c6-clover-efi

Glad it's still working. 
What I did is disable NTFY to XTFY rename patch. That caused non-working or partially working (sometimes working, sometimes not) hot-plug for me and for @kskim7, and significantly slower wake time.

The only problem with this is that now System Info reports that the TB driver isn't loaded, but it's working, and hot-plug also working.

And I also have problems with testing as I have only 1 TB3 device (TB3 eGPU), so I only can test with that one device unfortunately.

**Comment by tylernguyen** [comment]
@kskim7 

Please try out @kushwavez's solution and let me know.

@kushwavez Thank you!
