### ISSUE TITLE
Wifi card model - and MicroSD slot

### ISSUE THREAD

**Issue by outdoormagic** [tylernguyen/x1c6-hackintosh#14]
Hi Tyler,

Thanks for the excellent work on this. I have a DW1560, based on BCM94352Z, in the same laptop as you. It worked for a while and now it prevents booting; do you or anyone else have another card to recommend? DW1560 was finicky to get going, then worked really well, and now suddenly is acting up. Right now, I can’t even boot without removing it from the laptop.

On a different matter, I got the SD slot working. Very awkward location, but I have a 512GB microsd card in there for routine background backups. If you’re interested, I’ll have to look through my notes. I’m pretty sure I found while mapping the USB ports. It is not fast, hard to swap out, but it works for my purpose.

Thanks,

Paul

**Comment by velaar** [comment]
I’m running a native broadcom bcm943602cs with an adapter and a third antenna in the original LTE antenna slot. Can get a link over a gigabit with Bluetooth/continuity/handoff working. And yes, it does fit.

**Comment by outdoormagic** [comment]
Thanks, Vladimir. That’s great news. Stupid question: if I have two wires for the wifi antenna, were do you connect the third? I read good things about the 943602 and assumed that if the X1 had two wires, then I needed two antennas.

**Comment by velaar** [comment]
I’ve just bought a third antenna with a long cable and ran it to the LTE antenna location. Probably suboptimal placing but works fine for me. If you like I can make some pictures of my setup on Monday. (Don’t have the laptop at the moment, away for the weekend)

**Comment by outdoormagic** [comment]
> I’ve just bought a third antenna with a long cable and ran it to the LTE antenna location. Probably suboptimal placing but works fine for me. If you like I can make some pictures of my setup on Monday. (Don’t have the laptop at the moment, away for the weekend)
> […](#)

Thanks for the helps. It looks like I have a deeper issue, not related to the hack part. As my WiFi stopped working (to the point that I had to physically remove the card), my TrackPoint (red one and all 3 buttons) stopped working too, even in Windows. Updated BIOS, reflashed Synoptics, still no go. I’m suspecting a more general hardware issue and will have it checked out when I get back. (Travelling).

**Comment by tylernguyen** [comment]
Hi @outdoormagic, just as @velaar said, it's possible to use the native wifi card via an adapter and additional LTE antennas. In fact, it is what I currently use. I'll update the repo with pictures of my setup. 

In addition, it's great that you got the sd card to work. Please share any files and supporting documentation so I can get it working and committed to the project.

**Comment by xanderyuan** [comment]
> Hi Tyler,
> 
> Thanks for the excellent work on this. I have a DW1560, based on BCM94352Z, in the same laptop as you. It worked for a while and now it prevents booting; do you or anyone else have another card to recommend? DW1560 was finicky to get going, then worked really well, and now suddenly is acting up. Right now, I can’t even boot without removing it from the laptop.
> 
> On a different matter, I got the SD slot working. Very awkward location, but I have a 512GB microsd card in there for routine background backups. If you’re interested, I’ll have to look through my notes. I’m pretty sure I found while mapping the USB ports. It is not fast, hard to swap out, but it works for my purpose.
> 
> Thanks,
> 
> Paul

Hi, how did you get the wifi card BCM94352Z to work in the first place, I tried everything I can and it is not working

**Comment by tylernguyen** [comment]
@xanderyuan try this kext https://github.com/acidanthera/AirportBrcmFixup

**Comment by tylernguyen** [comment]
@outdoormagic If you still have that patch for sdcard reader, can you please share it?

**Comment by outdoormagic** [comment]
@tylernguyen ,
The "patch" is actually to include SS03 in the usb config. That will activate the microSD port. Nothing else needed.

**Comment by tylernguyen** [comment]
> @tylernguyen ,
> The "patch" is actually to include SS03 in the usb config. That will activate the microSD port. Nothing else needed, at least not on Catalina.
> 
> I added it using USB Map.command and created the matching SSDT. Works fine.

Thank you, I will update it in the repo soon.

**Comment by lubixxx96** [comment]
Hello,
does your sd card works after sleep/wake?
I get warning about sd card unplugged after waking up and I dont even see the card in the disk util.

Thanks

**Comment by tylernguyen** [comment]
@lubixxx96 My SD card reader works fine after sleep/wake. Can you try using the latest EFI folder and let me know if you still have this issue?

**Comment by lubixxx96** [comment]
It works with latest repo.
Thanks!
