### ISSUE TITLE
Secure Boot Compatibility

### ISSUE THREAD

**Issue by tylernguyen** [tylernguyen/x1c6-hackintosh#143]
With Windows 11 requiring Secure Boot, it is essential to get it working under macOS for maximum dual boot compatibility.

References:
- https://osy.gitbook.io/hac-mini-guide/details/secure-boot
- https://dortania.github.io/OpenCore-Post-Install/universal/security/vault.html
- https://dortania.github.io/docs/latest/Configuration.html#x1-840002

To-Do:
- [ ] Get Secure Boot working.
- [ ] Write an easy to follow guide how to do so.
- [ ] Get 1, maybe 2 testers to verify said guide.

**Comment by 1Revenger1** [comment]
This is an additional resource listed by the config.pdf (though it is in Russian) which may help as well assuming the other resources aren't enough.
https://habr.com/en/post/273497/

I've noticed that the PC health check app from Microsoft only checked that the Secure Boot *feature* existed, not that Secure Boot was enabled. My X1E1 passed with Secure Boot disabled (but TPM on). I wouldn't be surprised if they tried to make it being enabled required though.

**Comment by tylernguyen** [comment]
It looks like @profzei beat me to it. See https://github.com/profzei/Matebook-X-Pro-2018/wiki/Enable-BIOS-Secure-Boot-with-OpenCore

I've added this under `Tecnical Details` on the docs page. The guide seems very well written and maintained so I will defer to it on the guide.
