### ISSUE TITLE
Battery Loses fast.

### ISSUE THREAD

**Issue by HsunGong** [tylernguyen/x1c6-hackintosh#144]
I've got only 2 hours battery life even if 100% percent is charged.
And I saw that the power goes to 15 Watts per hour, but actually chrome or qq does not require such watts.

![Snipaste_2021-08-18_17-07-20](https://user-images.githubusercontent.com/32933986/130046271-c3837bcb-9e7f-41df-8639-918136e29568.png)
![Snipaste_2021-08-18_17-07-05](https://user-images.githubusercontent.com/32933986/130046278-b0420d3f-5396-443e-a2be-c71ad3f40fe1.png)

**Comment by tylernguyen** [comment]
The number one culprit of power consumption is the TB3 controller. See https://tylernguyen.github.io/x1c6-hackintosh/BIOS/

Addtionally, you may wish to tweak these variales:
- BIOS power profiles
- Mod BIOS to undervolt
- CPUFriend Config
