### ISSUE TITLE
Cannnot wake up by keyboard

### ISSUE THREAD

**Issue by ytlmike** [tylernguyen/x1c6-hackintosh#145]
I'm using your newest efi and it's runing just fine, i appreciate that.
The only question i have is when it fall asleep, i can wake it only by pressing the power button or open the lid.
How can i wake it by keyboard? Thanks if anyone could help.
System: Mojave 10.14.6

**Comment by tylernguyen** [comment]
@ytlmike 

That's the intended behavior, it's done to avoid instant wake issues.

You may wish to experiment by removing lines 264-287 from https://github.com/tylernguyen/x1c6-hackintosh/blob/main/patches/SSDT-Sleep.dsl

Remove those lines should allow you to wake via USB. However, in my experience, it also causes instant wake and random USB wake events during sleep. See https://dortania.github.io/OpenCore-Post-Install/usb/misc/instant-wake.html

Of course, those were the past and I haven't tested it again for a while. So let me know how it goes for you.

**Comment by ytlmike** [comment]
I think i found something to resolve this,
edit the [dsl file](https://github.com/tylernguyen/x1c6-hackintosh/blob/67bf822d5bcdb450d1902cfad862bc64c49516dc/patches/SSDT-Sleep.dsl#L264) :
```
Method (GPRW, 2, Serialized)
        {
            If (OSDW ())
            {
                Local0 = Package (0x02)
                {
                    0x00, 
                    0x00
                }

                Local0[0x00] = Arg0

                If (Arg0 == 0x6D)
                {
                    Local0[0x01] = 0x03
                    Return (Local0)
                }

                If (Arg1 >= 0x04)
                {
                    // Debug = Concatenate ("SLEEP: GPRW patched to 0x00: ", Arg1)

                    Local0[0x01] = 0x00
                }

                Return (Local0)
            }

            Return (ZPRW (Arg0, Arg1))
        }
```
I added a judgement, when arg0=0x6D, change Arg1 to 0x03，this may let external usb device can wake in s3 mode,
it works fine yet, still testing.

**Comment by tylernguyen** [comment]
@ytlmike 

Right, but as I've said. Not being able to wake by USB was done on purpose. There's sleep problems when it's enabled. See https://github.com/tylernguyen/x1c6-hackintosh/issues/84 and https://dortania.github.io/OpenCore-Post-Install/usb/misc/instant-wake.html

**Comment by ytlmike** [comment]
There are indeed some problems.
it works fine sometimes, but it will instant wake or fail to wake the other times.
it so difficult 🙉
