### ISSUE TITLE
Couldnt Get the Installer to wok

### ISSUE THREAD

**Issue by sh0umik** [tylernguyen/x1c6-hackintosh#149]
I have been trying to install `Big Sur 11.5.2` into my X1 Carbon for a day now and I couldn't get past the installation steps. My machine is the exact same machine except it uses `i7-8550U` with 16GB Ram. 

So far I have replaced the stock SSD with [Corsair Force-Series-MP510](https://www.corsair.com/eu/en/Categories/Products/Storage/M-2-SSDs/Force-Series-MP510/p/CSSD-F480GBMP510#tab-tech-specs) and updated the `bios to 1.51`. I don't know how to mod bios and I don't want to go this route.

Each and every time the second phase of the installer ( Install from macOS HD ) gets stuck around `29-24 minutes remaining` on the apple logo. I tried waiting 40 mins and more and more but noticed the machine is getting hotter and hotter ! Then I stopped the installer.
![Untitled](https://user-images.githubusercontent.com/14281876/133237419-93a4cfc1-473e-4594-903d-b4ee3564320d.jpg)

Also is there any way I can check the install log from this screen or from anywhere? if so then please let me know how. I want to submit as much data as possible. 

I was wondering if this is an NVMeFix.kext a problem but tried the installer EFI with and without it and had no luck.
I have also disabled wifi & Bluetooth from the bios but no luck. 

I am currently using the Install EFI from the master branch for this install

**Comment by tylernguyen** [comment]
@sh0umik 

You can go ahead and use the master EFI to install instead. All you need to do is to change `ScanPolicy` to `0`

The install EFI is outdated and I've been meaning to get rid of it for a while now, just waiting on Monterey release.

**Comment by sh0umik** [comment]
@tylernguyen 

I tried the master EFI and it works but after installation, it hangs if I use intel wifi kext(itlwm)

Also, One thing to point out the SSD I changed is also not supported in X1 Carbon 6th gen. It should be because I was using that SSD in my Desktop Hackintosh (Big Sur 11.5.2)!! ( Phison E12 Nvme Controller is also doesn't work in Thinkpad I guess )

I changed that SSD and the installation step is completed using the EFI below.
https://github.com/kushwavez/lenovo-x1c6-clover-efi
I am currently using this EFI because I haven't changed my wifi card and intel wifi kext(itlwm) works fine with this EFI.

Your main EFI works well too but hangs on boot screen if I install itlwn.kext in your EFI (OpenCore 0.7.2). I used OpenCore Configurator to install the kext.

**Comment by tylernguyen** [comment]
@sh0umik 

I don't support OpenCore Configurator nor recommend using it.

Intel Wireless should work without any problems as I am using it myself. See https://github.com/tylernguyen/x1c6-hackintosh/blob/main/patches/Network%20Patches/Intel.plist for the Intel Network patch.
