### ISSUE TITLE
Do I need to replace my SSD?

### ISSUE THREAD

**Issue by dexinthecity** [tylernguyen/x1c6-hackintosh#15]
In the hardware replacement README it states to replace the Samsun PM981, my X1c6 came with INTEL SSDPEKKF256G8L and I was wondering if I should still replace it?

**Comment by outdoormagic** [comment]
Tyler recommends it as APFS plays nicer with that drive. I would suggest it is a trade off based on what you want.

My X1c6, same configuration as Tyler’s, came from Lenovo with a WD drive in it, not a Samsung. No big deal as I wanted a larger drive anyways, so I swapped it for a 2TB Samsung NVMe (not SATA) and haven’t had issues with it. I have it with a small Win10 partition to dual boot when needed.

Tyler did explain that it impacts battery life, but I’m getting a good 4+ hours doing photo editing, so I won’t complain given the larger drive and great data rates. I’m happy with my trade off and I guess Tyler is with his. YMMV.

**Comment by dexinthecity** [comment]
> Tyler recommends it as APFS plays nicer with that drive. I would suggest it is a trade off based on what you want.
> 
> My X1c6, same configuration as Tyler’s, came from Lenovo with a WD drive in it, not a Samsung. No big deal as I wanted a larger drive anyways, so I swapped it for a 2TB Samsung NVMe (not SATA) and haven’t had issues with it. I have it with a small Win10 partition to dual boot when needed.
> 
> Tyler did explain that it impacts battery life, but I’m getting a good 4+ hours doing photo editing, so I won’t complain given the larger drive and great data rates. I’m happy with my trade off and I guess Tyler is with his. YMMV.

so is it the nvme on the samsung that causes the issue or is it just that samsung drive specifically? I don't mind buying another SSD but just want to make sure since I have an intel and its also an nvme

**Comment by dengwxn** [comment]
@outdoormagic So does it just impact the battery? If it can work with the factory disk, I'd rather not buy a new one.

**Comment by tylernguyen** [comment]
@dexinthecity The reason if you have to replace the pm981 is because it is incompatible with macOS. If you machine comes with a different drive and you are able to install macOS normally, it is fine.

**Comment by tylernguyen** [comment]
@dengwxn @dexinthecity Just as @outdoormagic said, the decision to choose SATA m.2 or nvme m.2 is up to you. Obviously, the nvme is faster but the sata drive seems to be more battery efficient for me on macOS.

**Comment by tylernguyen** [comment]
Update on this issue: with advent of [NVMeFix](https://github.com/acidanthera/NVMeFix), power management is now better on NVMe drives. 

Hence, a fast NVMe standard m.2 drive is now the recommended replacement drive.

In addition, the stock PM981 is now also maOS compatible, see [Issue #43](https://github.com/tylernguyen/x1c6-hackintosh/issues/43)
