### ISSUE TITLE
Suggest 1600x900 HiDPI for 1440p screen

### ISSUE THREAD

**Issue by sunrez** [tylernguyen/x1c6-hackintosh#150]
Hi Tyler & all,

First, thanks for your extensive and hard work, just used this repo to get an X1C6/1440p on Mojave.  Having used a variety of guides and machines this was by far one of the fastest and easiest to get going, the hard work is highly appreciated.

One comment for the display I found even when using the 'onekey-hidpi' none of the listed resolution / modes looked very good to my eyes.

I used the guide here which is OUTSTANDING ( https://github.com/bbhardin/A-Guide-to-MacOS-Scaled-Resolutions ) and found that 1600x900 Retina / HiDPI looked the best with my 1440p panel (surprising conclusion IMO).  If you read the guide, you'll have to add 3200x1800 in addition to 1600x900 to the resolution list so you can choose 1600x900 Retina.  I also found RDM for flipping resolutions worked really well.

I also tried the author's 2000 x 1152 (Retina) and experimented with 1920x1080p (Retina) but while the UI and icons looked fine, some text (like in System Report, in the Text editor) had an 'off' look to them.  Frankly Linux / MATE desktop does better with fractional DPI scaling which is also a surprise.

**Comment by sunrez** [comment]
Note:  I am happy to upload the plist I created for this, I don't know if the vendor # / manuf. # is different so that might have to be changed on a machine by machine basis.

**Comment by sunrez** [comment]
``<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>DisplayProductName</key>
  <string>Thinkpad 1440p Display</string>
  <key>DisplayProductID</key>
  <integer>8246</integer>
  <key>DisplayVendorID</key>
  <integer>1711</integer>
  <key>scale-resolutions</key>
  <array>
    <data>AAAKAAAABaAAAAABACAAAA==</data>
    <data>AAAPAAAACHAAAAABACAAAA==</data>
    <data>AAAHgAAABDgAAAABACAAAA==</data>
    <data>AAAPoAAACMoAAAABACAAAA==</data>
    <data>AAAH0AAABGUAAAABACAAAA==</data>
    <data>AAAIAAAABIAAAAABACAAAA==</data>
    <data>AAAQAAAACQAAAAABACAAAA==</data>
    <data>AAAFAAAAAtAAAAABACAAAA==</data>
    <data>AAAGQAAAA4QAAAABACAAAA==</data>
    <data>AAAMgAAABwgAAAABACAAAA==</data>
  </array>
</dict>
</plist>

**Comment by tylernguyen** [comment]
@sunrez 

The plist didn't seem to paste right. Can you upload the file instead?

**Comment by sunrez** [comment]
Manufacturer: 6AF
Model: 2036

Note, all the leading zeros have been stripped off and these numbers are in hex .  The plist file I think has the data in base 10 so the numbers look different.
