### ISSUE TITLE
OC: grabbed zero system-id for SB, this is not allowed.

### ISSUE THREAD

**Issue by whosdev** [tylernguyen/x1c6-hackintosh#153]
Hey there! Dunno if I'm just dumb, but I've made all the BIOS changes and I still can't boot.
I've always get the same bug.
OC: grabbed zero system-id for SB, this is not allowed.
Halting on Critical error
With the deprecated EFI, it used to boot, but whenever I tried to use the Main EFI it gave the same error.
Currently using BIOS 1.53, unmodded.

**Comment by tylernguyen** [comment]
@whosdev 

What macOS version are you on? Are you on Catalina by any chance?

**Comment by yxyshadow** [comment]
I have the same error: OC: grabbed zero system-id for SB, this is not allowed.
Halting on Critical error
bios version 1.51 unmodded. macOS version 12.0.1

**Comment by ljurcisin** [comment]
Same issue, Latest Big Sur, Bios 1.51

**Comment by tylernguyen** [comment]
@whosdev @yxyshadow @ljurcisin 

Which EFI version is giving you this issue, the latest EFI?

Which EFi commit is the last working one?

**Comment by ljurcisin** [comment]
Latest EFI in my case + additional change for unmodded bios + "-v" boot arg + I think 3 additional kexts for enabling wifi on stock wifi-card

**Comment by tylernguyen** [comment]
> Latest EFI in my case + additional change for unmodded bios + "-v" boot arg + I think 3 additional kexts for enabling wifi and bt on stock wifi-card

So the latest is giving you:

```
OC: grabbed zero system-id for SB, this is not allowed.
Halting on Critical error
```

Which is the last commit that does not give this issue?

**Comment by ljurcisin** [comment]
https://github.com/tylernguyen/x1c6-hackintosh/commit/8c83bf2cc906a8616c0db9f9032df132a0dfe334

**Comment by tylernguyen** [comment]
> [8c83bf2](https://github.com/tylernguyen/x1c6-hackintosh/commit/8c83bf2cc906a8616c0db9f9032df132a0dfe334) and yes, this is the issue I have: OC: grabbed zero system-id for SB, this is not allowed. Halting on Critical error

@ljurcisin 

Can you try setting `SecureBootModel` to `Disabled` and let me know if that fixes the problem?

**Comment by yxyshadow** [comment]
The latest EFI  giving this error when update to Mon_12.0.1,   last working:OC_0.7.2 , BigSur11.6.1

**Comment by whosdev** [comment]
> @whosdev
> 
> What macOS version are you on? Are you on Catalina by any chance?

Lastest Big Sur. I also tried to set SecureBootModel to Disabled, it still didnt boot.
Altough the first line of the error was removed.

**Comment by whosdev** [comment]
Also, whenever I tried to "merge" the unmodded EFI to the modded one, by placing 	<dict>
			<key>PciRoot(0x0)/Pci(0x2,0x0)</key>
			<dict>
				<key>framebuffer-fbmem</key>
				<data>AACQAA==</data>
				<key>framebuffer-stolenmem</key>
				<data>AAAwAQ==</data>
			</dict>
after the <key>add
Am I doing something wrong as well?

**Comment by ljurcisin** [comment]
> > [8c83bf2](https://github.com/tylernguyen/x1c6-hackintosh/commit/8c83bf2cc906a8616c0db9f9032df132a0dfe334) and yes, this is the issue I have: OC: grabbed zero system-id for SB, this is not allowed. Halting on Critical error
> 
> @ljurcisin
> 
> Can you try setting `SecureBootModel` to `Disabled` and let me know if that fixes the problem?

Works fine now! 
Thanks!

**Comment by yxyshadow** [comment]
> > [8c83bf2](https://github.com/tylernguyen/x1c6-hackintosh/commit/8c83bf2cc906a8616c0db9f9032df132a0dfe334) and yes, this is the issue I have: OC: grabbed zero system-id for SB, this is not allowed. Halting on Critical error
> 
> @ljurcisin
> 
> Can you try setting `SecureBootModel` to `Disabled` and let me know if that fixes the problem?

Thanks，it works fine now！

**Comment by tylernguyen** [comment]
> 
> 
> Also, whenever I tried to "merge" the unmodded EFI to the modded one, by placing PciRoot(0x0)/Pci(0x2,0x0) framebuffer-fbmem AACQAA== framebuffer-stolenmem AAAwAQ== after the add Am I doing something wrong as well?

Place it in the self top level.

**Comment by noclee** [comment]
SecureBoot Disabled worked for me on x1c6 i7 8Gen

**Comment by handrex12** [comment]
> ¡Hola! No sé si soy tonto, pero hice todos los cambios en el BIOS y todavía no puedo arrancar. Siempre tengo el mismo error. OC: tomó cero system-id para SB, esto no está permitido. Detener en error crítico Con el EFI obsoleto, solía arrancar, pero cada vez que intentaba usar el EFI principal, daba el mismo error. Actualmente usando BIOS 1.53, sin modificar.

Has el intento con la versión de open core 0.6.1 y utiliza el archivo de simple.plist (config.plist) del open core 0.6.1 y verás q te va a funcionar  a mi me sirvió y puedes utilizar la guía 0.8.3 para dicha configuración

**Comment by NyomanMC** [comment]
> > [8c83bf2](https://github.com/tylernguyen/x1c6-hackintosh/commit/8c83bf2cc906a8616c0db9f9032df132a0dfe334) and yes, this is the issue I have: OC: grabbed zero system-id for SB, this is not allowed. Halting on Critical error
> 
> @ljurcisin
> 
> Can you try setting `SecureBootModel` to `Disabled` and let me know if that fixes the problem?

I have tried disabling the Secure Boot, still don't work, is there anything to do with the Serial Ports?

**Comment by NyomanMC** [comment]
> > > [8c83bf2](https://github.com/tylernguyen/x1c6-hackintosh/commit/8c83bf2cc906a8616c0db9f9032df132a0dfe334) and yes, this is the issue I have: OC: grabbed zero system-id for SB, this is not allowed. Halting on Critical error
> > 
> > 
> > @ljurcisin
> > Can you try setting `SecureBootModel` to `Disabled` and let me know if that fixes the problem?
> 
> I have tried disabling the Secure Boot, still don't work, is there anything to do with the Serial Ports?

Unfortunately there is no legacy boot/CSM mode in my PC, so I can't go BIOS boot

**Comment by modtanoii** [comment]
I use X1C6 model 20KG and try to disable Secureboot but have same error

OC: grabbed zero system-id for SB, this is not allowed. Halting on Critical error

anyone have an idea?

**Comment by dclive** [comment]
You need to disable "Securebootmodel" in the OpenCore settings.  Yes, you have to do it in BIOS too, but this part here is referencing OpenCore settings.
