### ISSUE TITLE
A problem with camera and bluetooth(usb)

### ISSUE THREAD

**Issue by YuechenW** [tylernguyen/x1c6-hackintosh#158]
Hi! Thanks for your EFI, especially your docs, that helps me a lot.

I'm using x1c5(not 6), and I had your 'SSDT-XHC1.aml' AML tables successfully loaded. But the camera&bluetooth didn't work.（Neither display in the usb3.0 bus).
I added 'usbinjectall.kext' and solved it. But I think that since you have provided this 'xhc1.aml', the injection should not be necessary. I compared your decompilated DSDT to my own and didn't find any noticeable difference in RHUB.（It is known that the card reader of my model does not use USB bus, but it should have no effect）

Could you please help me modify that ’XHC1. aml‘ or put forward some advice to modify it？Thank you very much！

This is my USB screenshots driven by 'usbinjectall.kext' ：(seems just the same as what you described in the xhc1.dsdt)

<img width="880" alt="截屏2021-11-12 下午5 18 03" src="https://user-images.githubusercontent.com/44115105/141442542-8c9b795a-dc54-4f23-9fe4-1729e09ea06f.png">
<img width="495" alt="截屏2021-11-12 下午5 30 01" src="https://user-images.githubusercontent.com/44115105/141444269-87bbf125-0df1-4d1c-9da7-24bbbfa04354.png">

and my dsdt file:(remove the '.zip')
[DSDT5.dsl.zip](https://github.com/tylernguyen/x1c6-hackintosh/files/7526353/DSDT5.dsl.zip)

**Comment by YuechenW** [comment]
Oh, and that's a usb-map without a 'usbinjectall' kext.
<img width="495" alt="截屏2021-11-12 下午7 34 47" src="https://user-images.githubusercontent.com/44115105/141460830-54f1067f-d6ae-4c42-9500-144946a02dee.png">

**Comment by tylernguyen** [comment]
@YuechenW 

Can I get a copy of the current EFI you're using? One with and without `Usbinjectall.kext`?

**Comment by YuechenW** [comment]
Sure. Since I fail to upload it here, you can get it at my new repository[https://github.com/YuechenW/Hackintosh-x1c5-Monterey](url).And the only difference between these two is the config.plist file, I already have them both uploaded.

**Comment by tylernguyen** [comment]
@YuechenW 

My bluetooth is mapped to HS07 and wemcab is mapped to HS08.

You should do a  USB map on your x1c5 and adjust the ACPI patch accordingly.

**Comment by YuechenW** [comment]
The USB map I customized with Usbinjectall.kext can be used, and  the bluetooth&webcam is also mapped to HS07&HS08.
[USBPorts.kext.zip](https://github.com/tylernguyen/x1c6-hackintosh/files/7533012/USBPorts.kext.zip)
Maybe my usb map is the same as yours?

**Comment by YuechenW** [comment]
I think I know what the problem is.I remember that I modified your origin aml to avoid some acpi error. Now I am sure that it is incorrect.
I will put the acpi error below, could you please help me modify it?

**Comment by YuechenW** [comment]
It seems that the original SSDT-INIT & SSDT-XHC1 is not suitable for my device. 
<img width="597" alt="截屏2021-11-14 上午9 58 00" src="https://user-images.githubusercontent.com/44115105/141664542-46f53f8d-e3f3-48c0-9a65-3e0d5c8abc5f.png">
But I don't know how to correct it properly.
You can get my original ACPI tables(rename to DSDT.dsl)Thanks a lot.
[DSDT.dsl.zip](https://github.com/tylernguyen/x1c6-hackintosh/files/7533062/DSDT.dsl.zip)

**Comment by YuechenW** [comment]
I've just solved problem1,and the problem 2 seems to be just correct.

As for problem3, unless  the SSDT-3-RVP7Rtd3.aml needs to be extracted in a special way(which I doubled), it is not appropriate to consult you because of the hardware differences...

Thank you all the same~
