### ISSUE TITLE
Virtual Machines

### ISSUE THREAD

**Issue by dexinthecity** [tylernguyen/x1c6-hackintosh#16]
I noticed that part of the BIOS requirements was to turn off intel virtualization. Does this prevent you from using VMware or Virtualbox?

**Comment by noclee** [comment]
I have enabled it and its working stable working with VMWare Fusion Mojave, does take it toll on CPU/Battery though when multiple VMs are running but this expected.

**Comment by fbartolini** [comment]
I left VT-d disabled, but against what is recommended [here](https://github.com/tylernguyen/x1c6-hackintosh/blob/master/1_README-HARDWAREandBIOS.md) I reenabled VT-x (in the bios right next to VT-d as "Intel Virtualization Technologies". I also removed the boot flag "dart=0", and for me virtualization works fine now.

**Comment by tylernguyen** [comment]
> I left VT-d disabled, but against what is recommended [here](https://github.com/tylernguyen/x1c6-hackintosh/blob/master/1_README-HARDWAREandBIOS.md) I reenabled VT-x (in the bios right next to VT-d as "Intel Virtualization Technologies". I also removed the boot flag "dart=0", and for me virtualization works fine now.

@fbartolini 's solution should be fine, enabled Virtualization seems to have no drawbacks on my current Catalina and OpenCore configurations. Moving forward, virtualization will be enabled in my config.
