### ISSUE TITLE
[HELP] Can't get my device to go into sleep

### ISSUE THREAD

**Issue by rogerdcarvalho** [tylernguyen/x1c6-hackintosh#160]
Hi there,

So I actually have a different device (Thinkpad X1 Tablet Gen 3 - https://www.notebookcheck.net/Lenovo-ThinkPad-X1-Tablet-2018-i5-3K-IPS-Convertible-Review.394881.0.html), but it was released around the same time with the same generation of motherboard / processor. 

I can't get my sleep/wake to work. When I try to go into sleep, the screen turns off, but the device doesn't actually go into standby. Then when I press a button, the screen gets all garbled (https://preview.redd.it/bglazhvs64581.jpg?width=4032&format=pjpg&auto=webp&s=f11a5a004f25f3975da7f1c770dc1483f7c0367f). 

I tried your SSDT-Sleep.aml (with the OC patch Sleep.plist), but sadly this didn't work for me. Do you have any tips about what could be the cause and what else I could try?

My DSDT and EFI Folder are available to view at https://drive.google.com/drive/folders/1jnJO1u9WC8anA_V_IPnvPNXOzy9J0MBg?usp=sharing. Hope you can help? Thanks in advance!

**Comment by tylernguyen** [comment]
Refer to this: https://dortania.github.io/OpenCore-Post-Install/universal/sleep.html#tsc

You may also be interested in an earlier point of repo: https://github.com/tylernguyen/x1c6-hackintosh/tree/985d3a287ae50b57b19a8dbf8af4df5d41503c69/patches
