### ISSUE TITLE
docs: `config_unmoddedBIOS.plist` should be `Vanilla BIOS.plist` in `docs/BIOS/modding-the-BIOS.md`

### ISSUE THREAD

**Issue by bottycode** [tylernguyen/x1c6-hackintosh#163]
**Describe the bug**

In `docs/BIOS/modding-the-BIOS.md`, it says:

```
If you cannot mod your BIOS or is unwilling to do so, use `config_unmoddedBIOS.plist`.
```

It should be

```
If you cannot mod your BIOS or is unwilling to do so, use `Vanilla BIOS.plist`.
```

Since the file is renamed.

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Appropriate boot and/or debug logs**
N/A

**Comment by tylernguyen** [comment]
Thanks for noticing this. I'll fix it on the next docs update. I'm in the process of reorganizing docs to be a bit more readable.

**Comment by tylernguyen** [comment]
Fixed, due to push on the next docs update.
