### ISSUE TITLE
Wifi card BCM94252Z

### ISSUE THREAD

**Issue by xanderyuan** [tylernguyen/x1c6-hackintosh#17]
Hi, huge thanks for putting up the guide. I got my new Thinkpad yesterday and got it working in several hours!
I have a wifi card issue and have no idea how to deal with it.
My laptop config is the same as you except without HDR and the optional SIM card slot.
I'm running 10.14.6 bios 1.38
I have followed this guide:
https://www.tonymacx86.com/threads/broadcom-wifi-bluetooth-guide.242423/
and by adding the relevant 3 kext (AirportBrcmFixup; BrcmFirmwareRepo.kext; BrcmPatchRAM2.kext) into EFI - other folder (using clover configurator), my laptop does not boot into macOS and gets stuck about half way at the apple loading bar.
I have also tried to follow the Thinkpad x1 gen 5 guide on https://www.tonymacx86.com/threads/99-perfect-sierra-10-12-6-on-thinkpad-x1-carbon-5th-gen-with-dual-boot-unchanged-win7.237922/ and using the same method to drag the files into EFI - other folder and it does not work (the same issues occur)
I don't know if this is relevant but I tried to swap the wifi card straight away and it doesn't install windows properly, I had to move the intel wifi card back to get into windows to update bios.
Thanks!

**Comment by ESJai** [comment]
@xanderyuan You meant BCM94352Z? I just installed a DW1560 with just installing the three kext you mentioned above, it's working perfectly fine. Which card did you get exactly? Have you done the ACPI patching yet as it seems to matter as mentioned in the Wifi Guide post?

**Comment by xanderyuan** [comment]
Thx for the reply! Yes, it’s DW1560. Confirmed it is hardware issue on windows, got a bad card. :( Now deciding whether to buy another one or broadcom bcm943602cs as mentioned in another post but they didn’t upload pictures, not so confident it would fit in the slot

**Comment by ESJai** [comment]
yeah, i don't know how that would fit either as it requires 47mm in length i believe which would overlap with the ssd and I have no idea how I should run the third antenna. It would be nice if there is at least some information on how to run the WWAN antenna on the internet, but I don't seem to have luck on that. If all can be fixed somehow, the native wifi cards are way cheaper.

**Comment by ESJai** [comment]
An update to my thinkintosh. I'm running dual boot Mac and Windows with a SN520 ssd on WWAN slot. DW1560 works perfectly with mac os, but it freezes up after like 30s in Windows. 

After some research, I believe there is no easy workaround for it, so I bought a BCM94360CS2 with an adapter (The 2 antenna one), it works perfectly on both OSes. No kext required for Mac OS, just need to install a specific driver on Windows.

To install the adapter, I had to cut the card so you won't be able to mount the card with screw.
The actual card is gonna overlap with the ssd but you can add a layer of electrical tape in between to prevent shorts.
To mount the card more securely, you can just use some more electrical tape

Here is some pictures:
https://imgur.com/a/e119JOb

**Comment by xanderyuan** [comment]
Thanks for sharing!
Looks fantastic, ordering now, hopefully fast delivery

**Comment by ESJai** [comment]
Another update, I bought a bcm943602cs and installed it using the same method, it seems to be working fine with only J0 and J2 antenna connected. I'm probably just gonna return the cs2 card and get an extra antenna for that faster speed.

Comparison:
CS2(2antenna) + adapter = $40 for 867Mbps, work on both Mac and Windows
2CS(3antenna) + adapter = $45 for 1300Mbps, work on both Mac and Windows
DW1560 = $65 for 867Mbps, only work on Mac for this laptop, need extra kext patches.

I also ordered a DW1830 off aliexpress, will see if that's an option also, but it costs like $75, so prob not.

**Comment by Porco-Rosso** [comment]
> An update to my thinkintosh. I'm running dual boot Mac and Windows with a SN520 ssd on WWAN slot. DW1560 works perfectly with mac os, but it freezes up after like 30s in Windows.

How were you able to use the WWAN m.2 slot to run the SSD? I bought a smaller SSD to run mac os from, thinking I could use windows on the stock drive and mac on the new one, but afterwards discovered it did not work. The drive and interface is not present in mac or windows. Some digging online revealed that the slot does not support memory devices...

**Comment by ESJai** [comment]
> > An update to my thinkintosh. I'm running dual boot Mac and Windows with a SN520 ssd on WWAN slot. DW1560 works perfectly with mac os, but it freezes up after like 30s in Windows.
> 
> How were you able to use the WWAN m.2 slot to run the SSD? I bought a smaller SSD to run mac os from, thinking I could use windows on the stock drive and mac on the new one, but afterwards discovered it did not work. The drive and interface is not present in mac or windows. Some digging online revealed that the slot does not support memory devices...

The WWAN slot support pci-e(x2 i think) only, so only NvME drives are supported, meaning no SATA drives.
There is one little problem with this setup tho. You must install MacOS on the main 2280 drive because Clover cannot boot from the 2242 drive. It’s something coded in the BIOS, and clover doesn’t add boot option to BiOS by default like Windows Boot Manager does.
You can boot Windows directly from 2242 drive with no problem, but for my laptop, I just use clover to handle it.

**Comment by Porco-Rosso** [comment]
That's a shame. I purchased a SATA m.2 drive because I read it was more easily compatible with the MacOS drivers. I guess I will go back to hoping for the PM981 to be compatible...

**Comment by ESJai** [comment]
> That's a shame. I purchased a SATA m.2 drive because I read it was more easily compatible with the MacOS drivers. I guess I will go back to hoping for the PM981 to be compatible...

I personally have a WD Balck SN750 NVMe running as my main drive. Zero issues with APFS. I don’t know anything performance wise tho but it works.

**Comment by velaar** [comment]
I have SN520 (NVMe, 512GB) clover/MacOS are installed on this drive and it runs perfectly. All you have to do is to manually add a boot option.

**Comment by ESJai** [comment]
> I have SN520 (NVMe, 512GB) clover/MacOS are installed on this drive and it runs perfectly. All you have to do is to manually add a boot option.
> […](#)

That’s great news. Any tutorials I can borrow? Thanks in advance!

**Comment by xanderyuan** [comment]
> That's a shame. I purchased a SATA m.2 drive because I read it was more easily compatible with the MacOS drivers. I guess I will go back to hoping for the PM981 to be compatible...

I think PM981 does not work at all, as far as I know and you would need to change that for an alternative drive

**Comment by dexinthecity** [comment]
> An update to my thinkintosh. I'm running dual boot Mac and Windows with a SN520 ssd on WWAN slot. DW1560 works perfectly with mac os, but it freezes up after like 30s in Windows.
> 
> After some research, I believe there is no easy workaround for it, so I bought a BCM94360CS2 with an adapter (The 2 antenna one), it works perfectly on both OSes. No kext required for Mac OS, just need to install a specific driver on Windows.
> 
> To install the adapter, I had to cut the card so you won't be able to mount the card with screw.
> The actual card is gonna overlap with the ssd but you can add a layer of electrical tape in between to prevent shorts.
> To mount the card more securely, you can just use some more electrical tape
> 
> Here is some pictures:
> https://imgur.com/a/e119JOb

I bought this same one and I can only get bluetooth working for some reason..tried without kexts and with kext still the same issue

**Comment by xanderyuan** [comment]
> > An update to my thinkintosh. I'm running dual boot Mac and Windows with a SN520 ssd on WWAN slot. DW1560 works perfectly with mac os, but it freezes up after like 30s in Windows.
> > After some research, I believe there is no easy workaround for it, so I bought a BCM94360CS2 with an adapter (The 2 antenna one), it works perfectly on both OSes. No kext required for Mac OS, just need to install a specific driver on Windows.
> > To install the adapter, I had to cut the card so you won't be able to mount the card with screw.
> > The actual card is gonna overlap with the ssd but you can add a layer of electrical tape in between to prevent shorts.
> > To mount the card more securely, you can just use some more electrical tape
> > Here is some pictures:
> > https://imgur.com/a/e119JOb
> 
> I bought this same one and I can only get bluetooth working for some reason..tried without kexts and with kext still the same issue

Mine arrived today and it worked without anything, at first it only had wifi, but after a reboot it had bluetooth, it should require nothing to get it working

**Comment by dexinthecity** [comment]
> > > An update to my thinkintosh. I'm running dual boot Mac and Windows with a SN520 ssd on WWAN slot. DW1560 works perfectly with mac os, but it freezes up after like 30s in Windows.
> > > After some research, I believe there is no easy workaround for it, so I bought a BCM94360CS2 with an adapter (The 2 antenna one), it works perfectly on both OSes. No kext required for Mac OS, just need to install a specific driver on Windows.
> > > To install the adapter, I had to cut the card so you won't be able to mount the card with screw.
> > > The actual card is gonna overlap with the ssd but you can add a layer of electrical tape in between to prevent shorts.
> > > To mount the card more securely, you can just use some more electrical tape
> > > Here is some pictures:
> > > https://imgur.com/a/e119JOb
> > 
> > 
> > I bought this same one and I can only get bluetooth working for some reason..tried without kexts and with kext still the same issue
> 
> Mine arrived today and it worked without anything, at first it only had wifi, but after a reboot it had bluetooth, it should require nothing to get it working

There must be something wrong with my configuration, if it was a defective card it wouldn’t work at all right? Which version did you get exactly? Also mind uploading your efi?

**Comment by xanderyuan** [comment]
> > > > An update to my thinkintosh. I'm running dual boot Mac and Windows with a SN520 ssd on WWAN slot. DW1560 works perfectly with mac os, but it freezes up after like 30s in Windows.
> > > > After some research, I believe there is no easy workaround for it, so I bought a BCM94360CS2 with an adapter (The 2 antenna one), it works perfectly on both OSes. No kext required for Mac OS, just need to install a specific driver on Windows.
> > > > To install the adapter, I had to cut the card so you won't be able to mount the card with screw.
> > > > The actual card is gonna overlap with the ssd but you can add a layer of electrical tape in between to prevent shorts.
> > > > To mount the card more securely, you can just use some more electrical tape
> > > > Here is some pictures:
> > > > https://imgur.com/a/e119JOb
> > > 
> > > 
> > > I bought this same one and I can only get bluetooth working for some reason..tried without kexts and with kext still the same issue
> > 
> > 
> > Mine arrived today and it worked without anything, at first it only had wifi, but after a reboot it had bluetooth, it should require nothing to get it working
> 
> There must be something wrong with my configuration, if it was a defective card it wouldn’t work at all right? Which version did you get exactly? Also mind uploading your efi?

My efi folder is nothing but the newest drives linked in the preparation of the installation media, and then I just added the additional efi provided under this guide if I don't have it already.
I bought the wifi card on taobao, it only says BCM94360CD2 and everything else is in Chinese which will not be a help to you. I've read reviews on this card and people had the same issues and they resolved this by using an eraser to clean it and it worked for some reason.

**Comment by outdoormagic** [comment]
@ESJai , I have all NVMe; Samsung EVO 2280 and Lexar NM520 2242.

Booting from EVO 2280 no problem. When I insert 2242, it shows up, I can format as APFS, but system is unstable and randomly reboot. Sometimes a few seconds after boot, sometimes a few minutes.

Tried enabling WWAN, but doesn't make a difference.

Am I missing a setting or do I possibly have a bad drive?

**Comment by ESJai** [comment]
> @ESJai , I have all NVMe; Samsung EVO 2280 and Lexar NM520 2242.
> 
> Booting from EVO 2280 no problem. When I insert 2242, it shows up, I can format as APFS, but system is unstable and randomly reboot. Sometimes a few seconds after boot, sometimes a few minutes.
> 
> Tried enabling WWAN, but doesn't make a difference.
> 
> Am I missing a setting or do I possibly have a bad drive?

I would guess it is the drive that is not playing well with mac, just like issues with evo plus before (idk if its been fixed yet). I personally used the WD SN520, which runs perfectly.

**Comment by outdoormagic** [comment]
Yeah, I had a feeling. I'll swap under warranty and see if it was a dud or that design. Stay tuned.

As for EVO, I have 970 EVO 2TB. No issues. Love it.

Next step is to try to install Catalina...

**Comment by tylernguyen** [comment]
> > An update to my thinkintosh. I'm running dual boot Mac and Windows with a SN520 ssd on WWAN slot. DW1560 works perfectly with mac os, but it freezes up after like 30s in Windows.
> > After some research, I believe there is no easy workaround for it, so I bought a BCM94360CS2 with an adapter (The 2 antenna one), it works perfectly on both OSes. No kext required for Mac OS, just need to install a specific driver on Windows.
> > To install the adapter, I had to cut the card so you won't be able to mount the card with screw.
> > The actual card is gonna overlap with the ssd but you can add a layer of electrical tape in between to prevent shorts.
> > To mount the card more securely, you can just use some more electrical tape
> > Here is some pictures:
> > https://imgur.com/a/e119JOb
> 
> I bought this same one and I can only get bluetooth working for some reason..tried without kexts and with kext still the same issue

#dexinthecity, just as others have said, the  BCM94360CS2 should work natively, without any kexts. If you still have issues, I suggest getting another one as the one you have may be defective.

**Comment by tylernguyen** [comment]
> Yeah, I had a feeling. I'll swap under warranty and see if it was a dud or that design. Stay tuned.
> 
> As for EVO, I have 970 EVO 2TB. No issues. Love it.
> 
> Next step is to try to install Catalina...

Were you able to get macOS working on the 2242 drive?

**Comment by outdoormagic** [comment]
> Were you able to get macOS working on the 2242 drive?

No. When I install the 2242, I get random shutdowns. I'm having an exchange underway with Lexar.

Catalina 10.15.1 works fine on the 2280, though.

**Comment by velaar** [comment]
Works on 2242 (WD SN520), no shutdowns. Runs hot though (WD Drive is at 50C at idle)

**Comment by tylernguyen** [comment]
> > Were you able to get macOS working on the 2242 drive?
> 
> No. When I install the 2242, I get random shutdowns. I'm having an exchange underway with Lexar.
> 
> Catalina 10.15.1 works fine on the 2280, though.
 Just as @velaar , my WD SN520 works fine without any shutdowns. Have you tried installing windows on the 2242 and seeing if it has the same shutdown problems with Windows?

**Comment by Porco-Rosso** [comment]
Hi everyone, just here to report on my results. I purchased a BCM94360CS2 as well as a "Wireless card to A/E m.2 NGFF adaptor card". I also bought a 1TB WD Black SN750, which works with no problems. Sourcing these parts was by far the hardest part of this hackingtosh process thus far. I also needed to cut the adaptor in order for the card to lay flat enough to comfortably close the bottom laptop cover.

After a quick software update on Windows, the card worked on Win10. Although I did have to track down a bluetooth driver to make the BT part work. Unfortunately I did also discover the card does not seem to support BT Low Energy. This is a pain, as it means I cannot use my MX Master 3 mouse without the dongle, either in MacOS or Windows.

On the MacOS side of things, it "just worked" and I don't seem to be having any problems. Airdrop works. Unfortunately, as said, my BT LE mouse also fails to appear, so it really does seem to be the card does not support BT LE on a hardware level. I guess it is too old.

Here are some images from my build:
[https://imgur.com/a/R54v9vJ](https://imgur.com/a/R54v9vJ) 

Thank you in particular to you @ESJai for posting the pictures and the detailed research on the cards. It gave me the confidence to go out and hunt for the right things.

Unrelated:
@tylernguyen I seem to have an identical x1c build as yours, so if you need help testing/debugging let me know. Thanks for all the detailed notes, and updates. It's made a big difference!

Also to all: Does anyone have any clue how to dual-boot on one drive using OC? I rather not have to go buy a secondary drive, as i've already sunk a lot of money into this build.

**Comment by dragoncode** [comment]
> An update to my thinkintosh. I'm running dual boot Mac and Windows with a SN520 ssd on WWAN slot. DW1560 works perfectly with mac os, but it freezes up after like 30s in Windows.
> 
> After some research, I believe there is no easy workaround for it, so I bought a BCM94360CS2 with an adapter (The 2 antenna one), it works perfectly on both OSes. No kext required for Mac OS, just need to install a specific driver on Windows.
> 
> To install the adapter, I had to cut the card so you won't be able to mount the card with screw. The actual card is gonna overlap with the ssd but you can add a layer of electrical tape in between to prevent shorts. To mount the card more securely, you can just use some more electrical tape
> 
> Here is some pictures: https://imgur.com/a/e119JOb

Hi, may I ask which specific adapter you bought and where?

**Comment by Porco-Rosso** [comment]
I bought it in person at an electronics market in Asia, but your best bet is to just order something similar on Aliexpress, or potentially amazon.
I couldn't find the exact same one, but something like this: https://www.aliexpress.com/item/1005004711422885.html Just compare with the pictures I shared on imgur.
