### ISSUE TITLE
OC: grabbed zero system-id for SB, this is not allowed.

### ISSUE THREAD

**Issue by BAndersonMatjik** [tylernguyen/x1c6-hackintosh#171]
i get message OC: grabbed zero system-id for SB, this is not allowed. and cant boot EFI in version bos 1.55

**Comment by tylernguyen** [comment]
@BAndersonMatjik 

Refer to this issue #153 

Set `SecureBootModel` to `Disabled` unless you plan on creating custom secure boot keys.
