### ISSUE TITLE
Battery draining issues

### ISSUE THREAD

**Issue by dexinthecity** [tylernguyen/x1c6-hackintosh#18]
When I'm not usig my X1C6 I typically just close the display. I've noticed that it is considerably draining power faster than when I was on Linux. I left for about 4-5 hours today and when I left it was at 90% and now its at 32%. Anyway to fix tihis? I have also noticed that the red dot on the Thinkpad logo stays on the entire time instead of glowing like normal.

**Comment by nickwong680** [comment]
I have mine Sleep State on Linux that helped considerably 
![image](https://user-images.githubusercontent.com/1698569/64061414-cd2e6b00-cc1d-11e9-8a50-db548776c8ee.png)

**Comment by tylernguyen** [comment]
@dexinthecity 

Currently, there are only a few solutions to this:
1. Set the sleep state to Linux in the bios just as @nickwong680 mentioned.
2. Undervolt the machine.
3. Compiling and tweaking CPUFriend Data Provider

Option 1 is straight forward and the easiest, the two latter options are specific to every machine and cannot be share. You will have to go through trials and errors to determine the settings that are best for your specific machine.

**Comment by AutinMitra** [comment]
I don't know if this has been covered yet, and I know that this issue has been closed, but setting "thunderbolt assist mode" to enabled in BIOS has drastically reduced my power usage. Instead of idling @ 10-12W, it idles at 5-6W. With this, I am reaching 8-10 hours (and I am using a NVME drive, not SATA)

**Comment by velaar** [comment]
Can you share your DSDT and firmware version? Doesn’t seem to be the case for me.
