### ISSUE TITLE
No audio [fixed; likely due to Ventura + older AppleALC].  Keyboard/mouse issues after first poweron boot in OC83 [FIXED in OC87].  HiDPI explanation/details.

### ISSUE THREAD

**Issue by dclive** [tylernguyen/x1c6-hackintosh#183]
**Describe the bug**

1. No audio, even with AppleALC present.  Is there an alcid= argument we can use in nvram settings?  [audio worked in Windows] Screen just flashes if a beep happens; no speaker icons.  alcid=11 and alcid=21 don't work, even though per the wiki for applealc they should.  Hmm.   Is something else set for audio besides in nvram?   The Apple bong at OC83 startup is audible. [FIXED:  Jumped to latest AppleALC 1.77 and sound now fully works]. Microphone now works too, at least in MacOS Sound : INPUT clearly sees sound inputs.  Must test more soon. 
2. During first bootup, first powerup, keyboard works fine to change OC83 boot options (say, to disable SIP).  After that first boot (after MacoS restart, say), keyboard no longer works in OC.  Keyboard works fine once booted into MacOS, Linux, Win11.   Only an issue with OC83.   FIXED: Once I updated to OC87 and corresponding KEXTs, all issues like this went away immediately. 
3. More detail is needed on HiDPI settings.  No work to mount drive to RW in Ventura appears to be required; I simply disabled SIP, ran the script, and then enabled SIP.  The behavior of the icons is a bit odd, and opposite what I'd have expected (small text one gives me the largest text), but it clearly installed.  [EDIT:  SIP disable appears not to be required; I rebuilt everything to check my process & docs, and without disabling SIP, I was able to run HiDPI and have it function.] 
4. Exactly which (link possible?) NGFF adapter did you find and use with your BCM94360CS2 card?  What I see on Amazon all says not for laptops, too big/too thick.  (Mostly) FIXED:  There's so little room for an adapter that I simply got an old DW1830 (yes, with 3 antenna ports), attached two of the 3 antenna ports, and it's working with Wifi now.  Trying to get BT going results in spinny MacOS busy circles, so BT is out on a DW1830 at the moment.
5. NOTE:  OC88 works as well on this, with the 3 updated kexts (AppleALC, Lilu, WhateverGreen.]

BIOS=1.58.  

Great work with the site; thank you so much for sharing the details and work!

**To Reproduce**
[opencore-2022-12-31-001840.txt](https://github.com/tylernguyen/x1c6-hackintosh/files/10326595/opencore-2022-12-31-001840.txt)

See above

**Expected behavior**
See above

**Screenshots**
See above

I hit the 25MB limit, so I had to zip within the OC directory, and I omitted the resources folder completely.  

[Archive.zip](https://github.com/tylernguyen/x1c6-hackintosh/files/10326576/Archive.zip)

**Comment by tylernguyen** [comment]
- 1 & 2 should be fixed now that the EFI is updated for Venture.
- For hiDPI on Ventura, use this fork instead https://github.com/yurhett/one-key-hidpi
- Some NGFF adapter are breakable at the end to fit the laptop space, otherwise, it's mostly safe to simply cut/saw away the extra bits.
