### ISSUE TITLE
Installation Problem - Toggle SIP

### ISSUE THREAD

**Issue by itayg43** [tylernguyen/x1c6-hackintosh#184]
Hi!

First of all, thank you for all the hard work!

Now, I have a problem when trying to start and install macOS. I created the installer, edited bios settings, merged the vanilla bios file with the config file, changed the show picker to true, and finally set SecureBootModel to Disabled... But when trying to boot into the installer I get this:

![IMG_0043](https://user-images.githubusercontent.com/93944494/214573062-3f0525b0-8c20-4295-aff9-6632a79f11d8.jpg)

**Comment by dclive** [comment]
> Hi!
> 
> 
> 
> First of all, thank you for all the hard work!
> 
> 
> 
> Now, I have a problem when trying to start and install macOS. I created the installer, edited bios settings, merged the vanilla bios file with the config file, changed the show picker to true, and finally set SecureBootModel to Disabled... But when trying to boot into the installer I get this:
> 
> 
> 
> ![IMG_0043](https://user-images.githubusercontent.com/93944494/214573062-3f0525b0-8c20-4295-aff9-6632a79f11d8.jpg)
> 
> 

https://github.com/dclive/Lenovo-X1-Carbon-Gen-6-Hackintosh

You might try this one.  It's a mildly updated version that's based on Tyler's work, with the right settings already integrated in (for most people).  Read the readme's for the details.
