### ISSUE TITLE
Missing installation entry from boot menu

### ISSUE THREAD

**Issue by ChocolateDave** [tylernguyen/x1c6-hackintosh#187]
**Describe the bug**
No entry for the MacOS system or MacOS installer in the bootloader menu.

**To Reproduce**
Follow the installation instructions.

**Expected behavior**
You should expect an entry for an installed system or system installer.

**Appropriate boot and/or debug logs**
Changing the `ScanPolicy` field in `config.plist` to `0` helped resolve the issue.

**Comment by mwaldrich** [comment]
is this merged in the repo? I faced this issue too. Searched all over the internet for fixes that don't work, but this one does! macOS Ventura 13.3.1
