### ISSUE TITLE
Internet access from recovery

### ISSUE THREAD

**Issue by TQMatvey** [tylernguyen/x1c6-hackintosh#189]
Hello and thanks for this awesome project! I just got my new thinkpad x1 gen 6 carbon a few days ago, and having some hackintosh experience, i came across this repo, after placing the EFI and monterey recovery to a usb drive, configuring STOCK bios 1.59 and booting, i came across an annoying issue, no internet... on Desktop ethernet, here no. i dont have any ways to make a full image of Mac as i dont have access to any MacOS or hackintosh devices currently, i tried tethering from phone, but laptop doesnt pick it up from recovery....

**Comment by TQMatvey** [comment]
https://file.io/bQzWoQfRjL1P

**Comment by TQMatvey** [comment]
After adding [itlwm](https://github.com/OpenIntelWireless/itlwm/), wifi in installer works

**Comment by TQMatvey** [comment]
Sadly having to reopen the issue, as the driver doesnt work properly on Mac Os Ventura installed... it only works on monterey

**Comment by Johannes-ece** [comment]
Did you find a fix? Why did you close it?

**Comment by TQMatvey** [comment]
> Did you find a fix? Why did you close it?

[AirportItlwm](https://github.com/OpenIntelWireless/itlwm/releases/tag/v2.2.0) was updated fully and now works with Ventura properly, previously i just installed Monterey, swithed to itlwm + heliport, and user MacOS built-in updater to update to Ventura

**Comment by Johannes-ece** [comment]
I just tried if with that for a bit, but when I try to use the ventura usb with thr airporttlwm it gets stuck booting into the recovery.
Did you first install Monterey and then upgraded?

**Comment by TQMatvey** [comment]
Yes

**Comment by Johannes-ece** [comment]
Did you use this [patches/Network Patches/Intel Airportltlwm.plist](https://github.com/tylernguyen/x1c6-hackintosh/blob/main/patches/Network%20Patches/Intel%20Airportltlwm.plist) for the airporttlwm  in the Monterey recovery?

Sorry for all the questions, am a bit new to Hackintosh

**Comment by TQMatvey** [comment]
No
