### ISSUE TITLE
Not a request- Kudos!

### ISSUE THREAD

**Issue by KennethThompson** [tylernguyen/x1c6-hackintosh#199]
I was able to get my x1c6 hackintosh working with your repo!  My first try was a failure as the x1c6 I bought had a bad motherboard (which would reboot instead of shutting down, even when using windows).  So I ordered another from ebay and bam, working!  Wifi, sleep, everything is working as expected.  I get a solid 4+ hours on battery, which is perfect for me.  Thank you!

**Comment by tylernguyen** [comment]
Thank you for your kind words!
