### ISSUE TITLE
Outdated Setup Instructions

### ISSUE THREAD

**Issue by manooll** [tylernguyen/x1c6-hackintosh#20]
Hello and first of all - thank you for taking the time to put this repository together! 
I really appreciate the work and time you have put into this.

I have the same machine as you do, the same exact model number and components. 
Replaced the SSD and the WIFI card as you have specified but the setup still fails for me.
Updated the BIOS settings as well (I have the latest version of BIOS thought so that might be causing issues as well).
![IMG_20191008_191437](https://user-images.githubusercontent.com/16244686/66499823-88081f00-ea8e-11e9-8dc9-38933e08e461.jpg)

Here are more details and some constructive feedback:
1. default options within Clover seem to match the items you have outlined. But the new version of clover has a slightly different item layout and the "-64" endings are gone.
2. In the step #5 you have mentioned "Rename "config_HD615_620_630_640_650.plist" to "config.plist" and replace the stock "config.plist"." I can't find the target file for this on the flash drive. Can you please provide a full path?

I think because of the issue above(the wrong plist is being used) I am getting the error you can see on the photo and can't proceed any further. 

Please clarify the steps.

**Comment by outdoormagic** [comment]
@manooll same here. 

You have to mount the EFI folder first, for example with Clover Configurator.
When mounted, go to EFI:EFI/CLOVER/confg.plist

The -64 endings are gone, but the drivers are installed in the EFI:EFI/CLOVER/confg.plist/drivers64UEFI/ folder.

Tyler's excellent instructions worked for me until now, but since updating to 1.41, I have had issues. When booting with my old clover (but with a newly patched DSDT), the system in unstable and randomly reboots. I tried updating to the latest Mojave, and now have the issue you outline. On a different drive, I tried installing Catalina. Installer works, but then fails after reboot to complete the installation.

I'm sure it is a small setting change. They guys here are pretty buttoned up. I'll keep looking into it as well.

**Comment by manooll** [comment]
@outdoormagic thank you,
actually, I was able to find that .plist file yesterday after all and got it working and booted up Catalina! 
Woohoo!! The install went ok, I have installed the Clover on the hard drive and am now having two main issues: Tyler has specified a compatible Wifi card to use that would work with OSX...but I don't see a driver for it or how to activate it. I have mine installed and it should be working but even after enabling it in BIOS the machine does not pick it up.
Lastly: I will probably need to somehow figure out the display resolution. The WQHD screen that came with my laptop is causing everything to look very tiny and the resolution options within OSX make things blurry when you change the resolution to anything bu default.

That wifi card is a #1 priority though, please let me know if you can help or point me in the right direction to look

Thank you!

**Comment by outdoormagic** [comment]
I had a DW1560 which eventually failed me. Recently got a BCN94360CS2 (two antennae) with adapter, per others' suggestion here. Works well, no kext, no drivers.

To make it work, I had to install it, then disable WLAN in BIOS, boot (obviously no WiFi then), then reboot, enable in WLAN, and it worked OOB. I'm guessing my MB still had the old details stored somewhere. Either way, that worked for me.

**Comment by tylernguyen** [comment]
@manooll I'm glad you got the installer booted and working. Just as @outdoormagic said, the best option, it seems, is to get a native mac wifi card and use an adapter. As far as your original is concerned, I am working to move the system to OpenCore boot instead of Clover, which will hopefully reduce headaches in the near future.

**Comment by Colton-Ko** [comment]
I have wrote a guide for X1C6, with Thunderbolt 3, SD Card Reader, DW1560 WLAN working. 
The configuration works fine, despite of minor DSDT errors (displayed on verbose boot).
Boot time is fair (around 30 seconds)
Feel free to check it out.
https://github.com/Colton-Ko/macOS-ThinkPad-X1C6

**Comment by tylernguyen** [comment]
> I have wrote a guide for X1C6, with Thunderbolt 3, SD Card Reader, DW1560 WLAN working.
> The configuration works fine, despite of minor DSDT errors (displayed on verbose boot).
> Boot time is fair (around 30 seconds)
> Feel free to check it out.
> https://github.com/Colton-Ko/macOS-ThinkPad-X1C6

Thank you so much for contributing!

Your README layout looks great, especially the features page, I will change mine to the same format.
Regarding boot time, that is something limited by Clover. I'm in the process of transitioning to OpenCore right now, and that should decrease the boot time. 

Also, what is your experience with the IOElectrify kext? it seems that the kext has not been updated for a long time.

**Comment by Colton-Ko** [comment]
> Regarding boot time, that is something limited by Clover. I'm in the process of transitioning to OpenCore right now, and that should decrease the boot time.

I see, I had heard of OpenCore before, but I thought it is complicated to setup. (Compared to Clover) Looking for your contribution!

>Also, what is your experience with the IOElectrify kext? it seems that the kext has not been updated for a long time.

IOElectrify.kext and SSDT-TB3.aml enables full hot-plug support (even after sleep) for ThinkPad X1 C6. However, only the thunderbolt 3 port near the built-in ethernet port is working. The thunderbolt port for charging is not working. 

I found IOElectrify.kext useful when I saw a blogpost about Hackintosh on ThinkPad in a Chinese Forum.
The link is attached below.
https://zhuanlan.zhihu.com/p/75536927

Thank you for your compliment! Looking forward for your updated Readme! :)

**Comment by velaar** [comment]
For me both TB3 ports are working with your setup. Testing with Razer Core X eGPU.

**Comment by Colton-Ko** [comment]
@velaar What is your model type? Mine is 20KH CTO1WW. I cannot get Thunderbolt 3 on the front to have display signal output for the charging port, also that port does not support hot-plugging.

**Comment by velaar** [comment]
@Colton-Ko I have 20KH002HUS both ports work as expected for eGPU both charging and thunderbolt. For display stream I didn't have a chance to test. Which ig-platform-id do you use for the built-in gpu?

**Comment by Colton-Ko** [comment]
@velaar I used whatever green and left ig-platform-id blank, maybe I should inject a valid one and try again.

**Comment by tylernguyen** [comment]
Closing this issue as the original problem is fixed. Moving all Thunderbolt 3 discussion to a new thread: https://github.com/tylernguyen/x1c6-hackintosh/issues/24
