### ISSUE TITLE
OpenCore not showing any drives but only "Toggle SIP"

### ISSUE THREAD

**Issue by szsong** [tylernguyen/x1c6-hackintosh#204]
Model: 20KH
BIOS: 1.56 vanilla
EFI: only merged key from "vanilla BIOS.plist", and set "showPicker" to True

After entering OC, there is no options showing up except for "Toggle SIP".
![Screenshot 2023-10-17 at 12 04 36 AM](https://github.com/tylernguyen/x1c6-hackintosh/assets/3055084/5c1579e3-ccdb-4b52-ad88-72cf30116c0a)

**Comment by szsong** [comment]
found solution from #187 
Changing the ScanPolicy field in config.plist to 0 helped resolve the issue.
Sorry if this is rookie question:
Why is the "ScanPolicy" not set to 0 by default?

**Comment by cmantsch** [comment]
@szsong Did starting the setup work afterwards? I get shown the installer, but after selecting it if returns to the bootloader selection again after a few seconds of black screen

Tried with macOS 14 Sonoma
