### ISSUE TITLE
[HELP] bios dump needed!

### ISSUE THREAD

**Issue by TQMatvey** [tylernguyen/x1c6-hackintosh#207]
tldr. i need a stock bios dump for 20KG model.

i own the laptop for a year, in that period i used macos monterey, ventura, linux, windows, and even Android. now i am back to windows an i need TPM 2.0 to work for some apps i use that require it.

since i did modified bios for MacOS, i am now stuck with broken TPM since it needs fully stock bios
even upgrading bios via official Lenovo tool doesnt fully revert the changes and i dont have any backups left... i am stuck now..

i really hope someone could share stock bios for x1c6 20KG...

**Comment by Porco-Rosso** [comment]
I don't feel comfortable posting my BIOS publicly (I think it has a preinstalled win OS license in it?), but send me an email and I can send you the file.
smart.cat47544@fastmail.com

**Proceed with Extreme caution, (Dump your bios twice and diff the images before!)**
This should be the N23ET74 1.49 BIOS for 20KH002FUS
