### ISSUE TITLE
Help please! Can't compile a DSDT

### ISSUE THREAD

**Issue by manooll** [tylernguyen/x1c6-hackintosh#21]
Hi, 
thank you again for the instructions! My only wish is that the instructions would be a bit more complete.
I am battling an issue with a MaciASL: I was able to edit the DSDT and ad patches into it. The compiler summary gives me zero errors and yet when I try to save the file into the ACPI format I keep getting an error that "Compiler returned one or more errors" I think my MaciASL is glitching out since it is not showing me ANY compiler issues. Can somebody please try to compile the DSDT for me please?
Or point me in the direction to look to find the errors.

Here is the raw, edited (.dsl) file attached, it includes the patches I made.
[DSDT.zip](https://github.com/tylernguyen/x1c6-hackintosh/files/3721418/DSDT.zip)

**Comment by Colton-Ko** [comment]
Here you are
[DSDT.zip](https://github.com/tylernguyen/x1c6-hackintosh/files/3775695/DSDT.zip)
