### ISSUE TITLE
BCLM

### ISSUE THREAD

**Issue by amlboeton** [tylernguyen/x1c6-hackintosh#212]
@tylernguyen Does the battery charging limit working? I have T480s i5-8350u with Ventura 13.6.7 and the battery charging limit is not working, even already set to 80% it's still charging beyond 80% all the time.

Previously on Windows through the Lenovo Vantage already set the threshold to 80% as well

**Comment by johnwtt** [comment]
It unfortunately does not, at least for my X1C6. So you have to stick with full charge for the time being

**Comment by amlboeton** [comment]
> It unfortunately does not, at least for my X1C6. So you have to stick with full charge for the time being

Finally fixed it by using Linux Live Ubuntu to set the TLP

**Comment by amlboeton** [comment]
TLP set under live linux Ubuntu solved the issue
