### ISSUE TITLE
Please test the new AAPL,ig-platform

### ISSUE THREAD

**Issue by velaar** [tylernguyen/x1c6-hackintosh#22]
Hi, 

I've found an ig-platform that works perfectly for my 20KH (04002759). The screen sleep problems are gone! The screen also properly restores after sleep (no weird resolution issues). 

Here is what I have: 

```
<dict>
	<key>AddProperties</key>
	<array>
		<dict>
			<key>Device</key>
			<string>IntelGFX</string>
			<key>Disabled</key>
			<false/>
			<key>Key</key>
			<string>AAPL,GfxYTile</string>
			<key>Value</key>
			<data>AQAAAA==</data>
		</dict>
	</array>
	<key>Audio</key>
	<dict>
		<key>Inject</key>
		<string>No</string>
		<key>ResetHDA</key>
		<true/>
	</dict>
	<key>Properties</key>
	<dict>
		<key>PciRoot(0)/Pci(0x02,0)</key>
		<dict>
			<key>AAPL,ig-platform-id</key>
			<data>BAAnWQ==</data>
			<key>AAPL,slot-name</key>
			<string>Internal</string>
			<key>device-id</key>
			<data>FlkAAA==</data>
			<key>device_type</key>
			<string>VGA compatible controller</string>
			<key>enable-hdmi20</key>
			<data>AQAAAA==</data>
			<key>framebuffer-con0-enable</key>
			<data>AQAAAA==</data>
			<key>framebuffer-con0-pipe</key>
			<data>EgAAAA==</data>
			<key>framebuffer-con0-type</key>
			<data>AAQAAA==</data>
			<key>framebuffer-con1-enable</key>
			<data>AQAAAA==</data>
			<key>framebuffer-con1-flags</key>
			<data>hwEAAA==</data>
			<key>framebuffer-con1-pipe</key>
			<data>EgAAAA==</data>
			<key>framebuffer-con1-type</key>
			<data>AAgAAA==</data>
			<key>framebuffer-con2-enable</key>
			<data>AQAAAA==</data>
			<key>framebuffer-con2-flags</key>
			<data>hwEAAA==</data>
			<key>framebuffer-con2-pipe</key>
			<data>EgAAAA==</data>
			<key>framebuffer-con2-type</key>
			<data>AAgAAA==</data>
			<key>framebuffer-con3-enable</key>
			<data>AQAAAA==</data>
			<key>framebuffer-con3-flags</key>
			<data>hwEAAA==</data>
			<key>framebuffer-con3-pipe</key>
			<data>EgAAAA==</data>
			<key>framebuffer-con3-type</key>
			<data>AAgAAA==</data>
			<key>framebuffer-fbmem</key>
			<data>AACQAA==</data>
			<key>framebuffer-patch-enable</key>
			<integer>1</integer>
			<key>framebuffer-stolenmem</key>
			<data>AAAwAQ==</data>
			<key>hda-gfx</key>
			<string>onboard-1</string>
		</dict>
		<key>PciRoot(0)/Pci(0x1f,3)</key>
		<dict>
			<key>#PinConfigurations</key>
			<data></data>
			<key>hda-gfx</key>
			<string>onboard-1</string>
			<key>layout-id</key>
			<integer>11</integer>
			<key>no-controller-patch</key>
			<integer>1</integer>
		</dict>
	</dict>
	<key>USB</key>
	<dict>
		<key>AddClockID</key>
		<true/>
		<key>FixOwnership</key>
		<true/>
		<key>Inject</key>
		<true/>
	</dict>
	<key>UseIntelHDMI</key>
	<false/>
</dict>
</plist>
```

**Comment by AutinMitra** [comment]
Can confirm! AAPL, ig-platform BAAnWQ== has fixed some graphics glitches when waking from sleep, and fixed an under-scaling issue with one-key-hidpi (I think, hopefully I didn't speak to soon)

**Comment by benbender** [comment]
Works also on UHD 620, pci-id 5917 / Thinkpad T480 \o/

**Comment by outdoormagic** [comment]
I had followed rehabman's instructions to disable sleep and hibernation, namely running:
```
sudo pmset -a hibernatemode 0
sudo rm /var/vm/sleepimage
sudo mkdir /var/vm/sleepimage
sudo pmset -a standby 0
sudo pmset -a autopoweroff 0

```
I switched the 0s back to 1 and removed the sleepimage dir, but it still doesn't sleep. Any ideas how to reactivate sleep?

Thanks.

**Comment by AutinMitra** [comment]
> I had followed rehabman's instructions to disable sleep and hibernation, namely running:
> 
> ```
> sudo pmset -a hibernatemode 0
> sudo rm /var/vm/sleepimage
> sudo mkdir /var/vm/sleepimage
> sudo pmset -a standby 0
> sudo pmset -a autopoweroff 0
> ```
> 
> I switched the 0s back to 1 and removed the sleepimage dir, but it still doesn't sleep. Any ideas how to reactivate sleep?
> 
> Thanks.
I think what the fix does is fix graphics/resolution issues after suspend, not hibernate. I think it's best to set those back to 0s, since apple hibernation/sleep may corrupt the SSD

**Comment by tylernguyen** [comment]
> Hi,
> 
> I've found an ig-platform that works perfectly for my 20KH (04002759). The screen sleep problems are gone! The screen also properly restores after sleep (no weird resolution issues).
> 
> Here is what I have:
> 
> ```
> <dict>
> 	<key>AddProperties</key>
> 	<array>
> 		<dict>
> 			<key>Device</key>
> 			<string>IntelGFX</string>
> 			<key>Disabled</key>
> 			<false/>
> 			<key>Key</key>
> 			<string>AAPL,GfxYTile</string>
> 			<key>Value</key>
> 			<data>AQAAAA==</data>
> 		</dict>
> 	</array>
> 	<key>Audio</key>
> 	<dict>
> 		<key>Inject</key>
> 		<string>No</string>
> 		<key>ResetHDA</key>
> 		<true/>
> 	</dict>
> 	<key>Properties</key>
> 	<dict>
> 		<key>PciRoot(0)/Pci(0x02,0)</key>
> 		<dict>
> 			<key>AAPL,ig-platform-id</key>
> 			<data>BAAnWQ==</data>
> 			<key>AAPL,slot-name</key>
> 			<string>Internal</string>
> 			<key>device-id</key>
> 			<data>FlkAAA==</data>
> 			<key>device_type</key>
> 			<string>VGA compatible controller</string>
> 			<key>enable-hdmi20</key>
> 			<data>AQAAAA==</data>
> 			<key>framebuffer-con0-enable</key>
> 			<data>AQAAAA==</data>
> 			<key>framebuffer-con0-pipe</key>
> 			<data>EgAAAA==</data>
> 			<key>framebuffer-con0-type</key>
> 			<data>AAQAAA==</data>
> 			<key>framebuffer-con1-enable</key>
> 			<data>AQAAAA==</data>
> 			<key>framebuffer-con1-flags</key>
> 			<data>hwEAAA==</data>
> 			<key>framebuffer-con1-pipe</key>
> 			<data>EgAAAA==</data>
> 			<key>framebuffer-con1-type</key>
> 			<data>AAgAAA==</data>
> 			<key>framebuffer-con2-enable</key>
> 			<data>AQAAAA==</data>
> 			<key>framebuffer-con2-flags</key>
> 			<data>hwEAAA==</data>
> 			<key>framebuffer-con2-pipe</key>
> 			<data>EgAAAA==</data>
> 			<key>framebuffer-con2-type</key>
> 			<data>AAgAAA==</data>
> 			<key>framebuffer-con3-enable</key>
> 			<data>AQAAAA==</data>
> 			<key>framebuffer-con3-flags</key>
> 			<data>hwEAAA==</data>
> 			<key>framebuffer-con3-pipe</key>
> 			<data>EgAAAA==</data>
> 			<key>framebuffer-con3-type</key>
> 			<data>AAgAAA==</data>
> 			<key>framebuffer-fbmem</key>
> 			<data>AACQAA==</data>
> 			<key>framebuffer-patch-enable</key>
> 			<integer>1</integer>
> 			<key>framebuffer-stolenmem</key>
> 			<data>AAAwAQ==</data>
> 			<key>hda-gfx</key>
> 			<string>onboard-1</string>
> 		</dict>
> 		<key>PciRoot(0)/Pci(0x1f,3)</key>
> 		<dict>
> 			<key>#PinConfigurations</key>
> 			<data></data>
> 			<key>hda-gfx</key>
> 			<string>onboard-1</string>
> 			<key>layout-id</key>
> 			<integer>11</integer>
> 			<key>no-controller-patch</key>
> 			<integer>1</integer>
> 		</dict>
> 	</dict>
> 	<key>USB</key>
> 	<dict>
> 		<key>AddClockID</key>
> 		<true/>
> 		<key>FixOwnership</key>
> 		<true/>
> 		<key>Inject</key>
> 		<true/>
> 	</dict>
> 	<key>UseIntelHDMI</key>
> 	<false/>
> </dict>
> </plist>
> ```

Thank you so much for bringing this to my attention! I am currently very busy, hence why the repo has not been updated for a while. But I will test it and update the repo as soon as I have the time.

**Comment by tylernguyen** [comment]
@velaar I can attest that `BAAnWQ==` is indeed the better `AAPL,ig-platform`. Moving forward, this will be the ig-platform for my configuration. Thank you for bringing this to my attention. Looking forward to your next contribution!
