### ISSUE TITLE
Trackpad not working after kext updates (VoodooPS2?)

### ISSUE THREAD

**Issue by outdoormagic** [tylernguyen/x1c6-hackintosh#23]
Hi All,

I updated VoodooPS2, Lilu and all others a few days ago. When browsing in Safari, if I used the Trackpoint/middle button to scroll down, it would close the current tab into dozens of new tabs. Very annoying.

Today, I updated all kexts again, including a new version of Voodoo. Now the tab cloning issue is gone, but the Trackpad itself doesn't work.

EDIT: Spoke too soon; the tab spawning issue is still there. So now, I can't scroll in a browser :(

Current versions shown below, per Kext Updater.

Any ideas?

Last check
Tuesday, 03.12.2019, 08:09:30
 
Checking  AppleALC ...
👍🏼 You are up to date (1.4.4)
─────────────────
Checking  Clover ...
☝🏼 Update available!

    Your Version..... = 5093
    Server Version... = 5099

    Downloading File.
─────────────────

Checking  IntelMausi ...
👍🏼 You are up to date (1.0.2)
─────────────────
Checking  Lilu ...
👍🏼 You are up to date (1.4.0)
─────────────────
Checking  USBInjectAll ...
👍🏼 You are up to date (0.7.1)
─────────────────
Checking  VirtualSMC ...
👍🏼 You are up to date (1.0.9)
─────────────────
Checking  VoodooPS2 ...
👍🏼 You are up to date (2.1.0)
─────────────────
Checking  WhateverGreen ...
👍🏼 You are up to date (1.3.5)
─────────────────

👍🏼 Done.

**Comment by benbender** [comment]
VoodooPS2 2.1.0 needs VoodooInput (https://github.com/kprinssu/VoodooInput/tree/master/VoodooInput) as companion. 

(Details here: https://github.com/acidanthera/VoodooPS2/releases)

**Comment by outdoormagic** [comment]
Yes, even with Voodooinput, trackpad doesn't work with 2.1.0. I currently use 2.0.1.

I'll leave an issue with @vandroly2013.

**Comment by benbender** [comment]
If you on Mojave, you need to use VoodooInput 1.0.1. Version 1.0.0 was only built for Catalina.

**Comment by outdoormagic** [comment]
I have Catalina 10.15.1 (19B88). VoodooInput 1.0.1 (latest release), and VoodooPS2 2.0.1, as 2.1.0 won't work. I haven't tried 2.0.4.

Might be a DSDT patch issue, though I doubt it. I'll have to look into this more tomorrow.

**Comment by notthebee** [comment]
Yes, trackpad doesn't work with the latest acidanthera's VoodooPS2Controller + VoodooInput, it's a known issue: https://github.com/acidanthera/bugtracker/issues/600
This is a patched version that works (doesn't need VoodooInput): https://github.com/acidanthera/bugtracker/issues/418#issuecomment-547674864
However, acidanthera's VoodooPS2Controller doesn't have any kind of palm rejection (at least on my X1C6) and the PrintScreen button disables both trackpoint and trackpad. So I prefer using RehabMan's version for now since I only use trackpoint most of the time.

**Comment by tylernguyen** [comment]
> I have Catalina 10.15.1 (19B88). VoodooInput 1.0.1 (latest release), and VoodooPS2 2.0.1, as 2.1.0 won't work. I haven't tried 2.0.4.
> 
> Might be a DSDT patch issue, though I doubt it. I'll have to look into this more tomorrow.

Is your trackpad working now? If not:
Have you disabled the trackpad with PrintSc?
Do you have any conflicting VoodooPS2 and/or trackpad ssdt configurations?

**Comment by Porco-Rosso** [comment]
Hi, I ran into some rather odd issues with the trackpad as well.
After a windows synaptics trackpad driver/firmware update. Booting into MacOs made the trackpad act strangely.

Two fingers were needed to use the trackpad at all, acting as one "finger"
"Two finger" gestures required three fingers etc..

Updating to your newest EFI OC files and a reboot seems to have fixed it. @outdoormagic you could try again. I am on Catalina BTW.

**Comment by outdoormagic** [comment]
@Porco-Rosso I saw the kextcache suggestion you made on another issue. That worked great. Thank you.

A weird consequence is that during boot, boot hangs for 20-30 seconds on bluetooth, then boots. However, WiFi doesn't show up and the network panel is empty... for about 1 minute or 2. Then all network interfaces appears and WiFi works fine.

Any ideas?

**Comment by Porco-Rosso** [comment]
What Wifi card are you using? 
Perhaps you can try updating the firmware of the card on windows?
Otherwise, this is just a shot in the dark, but you can try masking some of the contacts as suggested [here](https://www.tonymacx86.com/threads/solved-windows-driver-for-bcm94360cs2.222646/page-4), but you shouldn't have to.

**Comment by tylernguyen** [comment]
@outdoormagic Since the trackpad issue has been resolve, I will close this issue. If you still have the network problem, please open a new issue.
