### ISSUE TITLE
Battery capacity not detected correctly

### ISSUE THREAD

**Issue by velaar** [tylernguyen/x1c6-hackintosh#25]
It seems the battery capacity is not detected correctly (after the move to OC setup. It shows the cycles correctly though. Any leads? 

![image](https://user-images.githubusercontent.com/4062230/71496746-18463c80-2812-11ea-8abc-85a29986cf24.png)

**Comment by tylernguyen** [comment]
@velaar I'm sorry but what about the battery capacity is wrong?

**Comment by velaar** [comment]
Sorry, my bad. Got confused with mAh instead of Wh. Checked the battery, 11.52V at 4.95 Ah. All as expected.
