### ISSUE TITLE
x1c7 compatibility

### ISSUE THREAD

**Issue by tylernguyen** [tylernguyen/x1c6-hackintosh#26]
I started this repo to track my progress:
https://github.com/acoutts/x1c7-hackintosh

I have in there my stock DSDT files and so far a minimum working clover config where I'm able to get to the Clover bootloader, but so far unable to boot to macOS installer.

I had to steal the drivers folder from this repository to get to where I am now:
https://github.com/daliansky/XiaoXinPro-13-2019-hackintosh

So far I'm stuck here. It loads the kexts and then pauses on the last one where it says it's waiting for 5s:
```
83:598  0:057  SetStartupDiskVolume:
83:631  0:032    * Volume: 'Install macOS Catalina'
83:664  0:032    * LoaderPath: '\System\Library\CoreServices\boot.efi'
83:704  0:039    * DevPath: Install macOS Catalina
83:739  0:034    * GUID = E4388F94-FAD0-4120-A5A6-6E2A88C938CF
83:771  0:032    * efi-boot-device: <array><dict><key>IOMatch</key><dict><key>IOProviderClass</key><string>IOMedia</string><key>IOPropertyMatch</key><dict><key>UUID</key><string>E4388F94-FAD0-4120-A5A6-6E2A88C938CF</string></dict></dict></dict></array>
83:839  0:068  Custom boot screen not used because entry has unset use graphics
83:872  0:032  Closing log
```

_Originally posted by @acoutts in https://github.com/tylernguyen/x1c6-hackintosh/issues/13#issuecomment-569950037_

**Comment by tylernguyen** [comment]
@sunrez @acoutts Whilst I appreciate and welcome your discussions, please move to a new thread specifically for x1c7 compatibility. I want to keep this repo as organized as possible.

@acoutts Try booting in verbose mode and seeing the output. A lot of the drivers you have seem unnecessary, start off with only the recommended Clover drivers, use https://github.com/RehabMan/OS-X-Clover-Laptop-Config as a base.

**Comment by tylernguyen** [comment]
Relevant comments from the other thread:
https://github.com/tylernguyen/x1c6-hackintosh/issues/13#issuecomment-569559519
https://github.com/tylernguyen/x1c6-hackintosh/issues/13#issuecomment-569844509
https://github.com/tylernguyen/x1c6-hackintosh/issues/13#issuecomment-569865968
https://github.com/tylernguyen/x1c6-hackintosh/issues/13#issuecomment-569910687
https://github.com/tylernguyen/x1c6-hackintosh/issues/13#issuecomment-569915305
https://github.com/tylernguyen/x1c6-hackintosh/issues/13#issuecomment-569954693

**Comment by acoutts** [comment]
Thanks for this. There is also discussion going on here, where others are struggling to get the 10th gen i7 to boot into the installer as well:
https://www.tonymacx86.com/threads/laptop-compatibility.106791/page-85#post-2053021

I've been trying with it all day, learning as I go here. But no luck so far.

**Comment by acoutts** [comment]
Update: i'm giving up on this endeavor. I found there is a whitelist in place so nothing can be plugged into the spare m.2 slot, which means wifi is completely out the window. On top of that I never managed to get the macOS installer to boot and it's likely due to the unsupported CPU.

**Comment by Jamesxxx1997** [comment]
I thought the cpu is supported.
Here is the repo of an cometlake laptop : https://github.com/daliansky/XiaoXinPro-13-2019-hackintosh
