### ISSUE TITLE
Is this project on going?

### ISSUE THREAD

**Issue by JackokieZhao** [tylernguyen/x1c6-hackintosh#27]
Thanks for your contribution to the hackintosh for thinkpad carbon 6th. \(^o^)/~
But I'm interested in whether this project be updated in the following? Because I want a stable system to run for my work. 
Thanks agin for your contributions.

**Comment by tylernguyen** [comment]
Yes, it is actively maintained. The X1 Carbon 6th Gen with macOS is my daily driver. I will continue to update and improve this repo until I no longer use my x1c6. Even then, I'm sure the community will keep supporting the project.
