### ISSUE TITLE
A big thanks from x1 yoga 2018 

### ISSUE THREAD

**Issue by Jamesxxx1997** [tylernguyen/x1c6-hackintosh#30]
Hello @tylernguyen !
Thank you so much for the detailed guide on this machine ; For x1 yoga and x1 carbon is similar in hardware(alc285 ,2 thunderbolt...) , and your hotpatch works great on x1 yoga!

For there are few people using x1 yoga hackintosh  , I’ve encounter some problems on x1 yoga but don’t know where to seek for help.
For many problems may also be found on x1 carbon 2018 , can I ask you for help?

Thank you very much.

**Comment by tylernguyen** [comment]
@Jamesxxx1997 Thank you for checking out repository. As long as it's also a problem with the Thinkpad X1 6th gen, I would love to look into and help. However, since I do not own an X1 Yoga 2018, I cannot help issues specifically with that laptop.
