### ISSUE TITLE
[Audio] Built-in output doesn't work

### ISSUE THREAD

**Issue by RyoIkarashi** [tylernguyen/x1c6-hackintosh#32]
## Issues

- Only the built-in output doesn't work whereas the built-in input and the headphone port input/output work fine.

- The built-in speaker/microphone seem to be recognized properly but I cannot hear any sound even though I put the volume up to the maximum.

![Screen Shot 2020-02-05 at 20 34 34](https://user-images.githubusercontent.com/5750408/73838405-f3a0a400-4856-11ea-9c3f-a5876012e238.png)

## Bootloader I use

OpenCore

## EFI

[Here is my EFI](https://github.com/RyoIkarashi/hackintosh-x1c6)

Anybody run into this issue?

**Comment by tylernguyen** [comment]
@RyoIkarashi You need to figure out which sound codec you have and adjust the OpenCore config.plist accordingly. If you have the same codec as me and it still does not work, I suggest you move on the a different AppleALC layout.

**Comment by RyoIkarashi** [comment]
@tylernguyen Thanks for the quick reply!
I figured out that my sound codec is `Realtek ALC 285` which may be the same as yours.
I'll try different layout numbers(`21` or `31`) other `11` as this [doc](https://github.com/acidanthera/AppleALC/wiki/Supported-codecs) describes.

**Comment by RyoIkarashi** [comment]
@tylernguyen 
I tried another layout number, 21 (`15000000`), and it worked like a charm!
Thanks for your advice :)

## FYI
Change `layout-id` to `15000000` (21) or `1F000000` (31) if `0B000000` (11) doesn't work.
