### ISSUE TITLE
Trackpad Irregularities

### ISSUE THREAD

**Issue by Porco-Rosso** [tylernguyen/x1c6-hackintosh#35]
Hello, thanks again for putting up this guide and maintaining it!

I've been experiencing some puzzling errors. Sometimes when I boot into macOS, my trackpad only works with two fingers. That is, two fingers are needed next to each other to move the cursor. Three fingers are needed for two finger scrolling, four fingers for three finger gestures etc...

Rebooting the computer seems to make this go away, but I would like to figure this out, as it is an inconvenience.

**Comment by velaar** [comment]
Happens to me as well. If I had to guess its about the PS2 and there is a race condition somewhere.

**Comment by tylernguyen** [comment]
@Porco-Rosso @velaar I think this is an issue with VoodooPS2 and VoodooInput. I used to have these problems but after the mention kexts are updated, the issue went away. Please try updating those two kexts.

**Comment by AzureWolf** [comment]
Can confirm that the Trackpad hasn't failed since updating these kexts from the official repo. The only hiccup is the trackpad stops working if you accidentally press the PrtSc button. Pressing it again fixes it. It's just something to be aware of and I don't know how to disable or change that key.

**Comment by Porco-Rosso** [comment]
I can concur, haven't had any issues. Would love to disable PrtSc, but I assume this is being managed at a BIOS level? 
I was unsuccessful remapping (or even receiving key presses with [keypirinha](https://keypirinha.com/)

**Comment by tylernguyen** [comment]
@AzureWolf @Porco-Rosso If you wish, you can modify this SSDT from RehabMan to turn the PrtSc button into F13 and remap it from there.

**Comment by AzureWolf** [comment]
"This SSDT"? I am pretty bad at the post-install instructions and I can't even tell if any of them worked, so I have no idea how to modify them either... If you can share one that is already modified and where to put it, I'd be really grateful.

Sorry, I've been trying (without luck) to transition to OpenCore but OpenCore has yet to work for me so I'm still on Clover and still pretty much clueless on getting those modifications to actually work.

**Comment by tylernguyen** [comment]
@AzureWolf Sorry, I forgot to attach the file's link. Here it is: https://github.com/RehabMan/OS-X-Voodoo-PS2-Controller/blob/master/SSDT-PrtSc-F13.dsl

I'm fairly busy atm so I can't make any promises but I think I should be able to get it to work on my machine in the next 2 weeks, then I'll update the repo with it.

**Comment by AzureWolf** [comment]
So yeah, I put it in my EFI loader disk (in ACPI --> Patched) and the trackpad went screwy again. I'll just wait for a fix from people more competent for me.

Thanks for everything you've done. I've been a macbook user since 2010 and this is the best macbook I've had lol

**Comment by Porco-Rosso** [comment]
Hi, all. So despite what I said above, it seems all the issues were not resolved. I am still having the two-finger touch problem I described after putting my laptop to sleep and waking it.

Haven't had a chance to try the PrtSc patch out yet.

**Comment by AutinMitra** [comment]
Maybe try clearing kextcache after installing updated kexts? They only didn't work for me during the install process, worked perfectly fine post-install

**Comment by Porco-Rosso** [comment]
@tylernguyen 
Like @AzureWolf I've tried to compile the .dsl file into an .aml file, but can't figure it out. I'm afraid to say I am a bit out of my depth on this one.
If you could either clarify your instructions on the READMEs or post the compiled aml here, when you have time I would be grateful.

Regarding the trackpad, I will rebuild the kextcahe and see if the error appears again.

**Comment by Porco-Rosso** [comment]
@AzureWolf I've successfully disabled the PrtSc button, by modifying SSDT-Keyboard-X1C6.dsl compiling it to .aml and making sure the reference is correct in the config.plist ( I renamed it to SSDT-Keyboard-X1C6-PrtSc-Mod), however it doesn't seem to be triggering any other keycode.
Does `"e037=64", // PrtSc=F13` really translate to the F13 key? Am I doing something wrong? 

Here are my dsl and aml files:
[SSDT-Keyboard-X1C6-PrtSc-Mod.zip](https://github.com/tylernguyen/x1c6-hackintosh/files/4316970/SSDT-Keyboard-X1C6-PrtSc-Mod.zip)

**Comment by tylernguyen** [comment]
@Porco-Rosso @AzureWolf Good news! Being quarantined has left me with a lot of time. Please check the latest OpenCore EFI folder. The new SSDT-Keyboard.aml includes PrtSc to F13 remap and other Fn key tweaks.

**Comment by velaar** [comment]
@tylernguyen 
Any chance we can keep a changelog somewhere? 
Seen that you've updated a bunch of other AMLs as they are binary so no comparison available.

**Comment by tylernguyen** [comment]
@velaar My apologies, I'm good at making changes but bad at documenting them. There's already a CHANGELOG.md file at the repo's root directory. I will update it right now with all the changes I've made. As far as comparisons goes, the compiled AML are identical to their DSL counterparts in the /patches folder. You can use those to compare ACPI.
