### ISSUE TITLE
Headphone Problem after sleep for while

### ISSUE THREAD

**Issue by mohamedspicer** [tylernguyen/x1c6-hackintosh#36]
can anyone confirm this issue.
i have a problem with Headphone sound after sleep or turn down the screen for about 15 minutes after that the sound is horrible in the Headphone it's noisy and low not normal.
note: built in sound works just fine in any state 
anyone faced this issue or issue like it, i would appreciate the help.

**Comment by mohamedspicer** [comment]
note: i use clover v5104

**Comment by AutinMitra** [comment]
I had this problem earlier, using Clover. I haven't had time to test with OpenCore (laptop is currently being serviced), but I believe that I had to use CodecCommander to fix it, but I had to run a script on every wakeup (I'll try to dig up what I actually did once my laptop is unbricked). 

Also, switching layout-id to another valid one may fix the issue, but I wouldn't bet on it.

**Comment by mohamedspicer** [comment]
@AutinMitra whatever solution i'll accept it comment your solution as soon as you get the laptop,
i use layout-id 11 and it works for me i had also CodecCommander but still same, if get the script i will appreciate it, Thanks man.

**Comment by tylernguyen** [comment]
@mohamedspicer Try using OpenCore EFI, my Clover folder has not been updated for a while.

**Comment by mohamedspicer** [comment]
@tylernguyen i don't know what's wrong with opencore EFI folder but it gives me a big apple logo in the middle of the screen and nothing happened, beside that i updated everything in clover file.

**Comment by AutinMitra** [comment]
@mohamedspicer 
This is not the script I use, but I think it'll do the job.
[ALCPlugFix](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/tree/master/ALCPlugFix)

If it doesn't work, let me know

**Comment by mohamedspicer** [comment]
@AutinMitra i do some research and found this https://github.com/chris1111/VoodooHDA-2.9.2-Clover-V15 i installed it and add this kext https://sourceforge.net/projects/voodoohda/files/latest/download and also install ALCPlugFix and it works but i don't now which of them solve it

**Comment by AutinMitra** [comment]
@mohamedspicer If it works, it works, but VoodooHDA is known to be worse than AppleALC due to issues such as reduced audio/mic quality, and non-working components (mic). I'd recommend reverting from VoodooHDA and try using ALCPlugFix, but if you are fine with the current audio quality feel free to close the issue.

**Comment by tylernguyen** [comment]
@mohamedspicer Just as stated above, I recommend switching back to AppleALC if you can. In addition, I just added a modified ALCPlugFix for the x1c6 so I would I recommend you give it a try.

**Comment by mohamedspicer** [comment]
> @mohamedspicer Just as stated above, I recommend switching back to AppleALC if you can. In addition, I just added a modified ALCPlugFix for the x1c6 so I would I recommend you give it a try.

hey @tylernguyen a would appreciate it but mine is ALC257 with layout-id 11 and what is the hda-verb number for mine, i took your ALCPlugFix and waiting to know the hda-verb number for mine in your fixAudio() function

**Comment by mohamedspicer** [comment]
@tylernguyen Thank you man your modified ALCPlugFix work without editing any thing :D

**Comment by tylernguyen** [comment]
@mohamedspicer To edit the fixAudio function, use Hackintool and compare your audio pin config with mine. Thought it has worked for your machine, I recommend that you double check the fixAudio function with your pin config anyway.

**Comment by mohamedspicer** [comment]
@tylernguyen where is the scetion in Hackintool that i can find Pin Config i just looked in every section and i can't find it

**Comment by tylernguyen** [comment]
@mohamedspicer See "Pin Configuration" under the Sound section. Compare it to my settings, see https://github.com/tylernguyen/x1c6-hackintosh/blob/master/docs/references/alc285_pin.png

Also, make sure that you're on the latest version of [Hackintool](https://github.com/headkaze/Hackintool/releases)

**Comment by mohamedspicer** [comment]
@tylernguyen it's the same to yours so i'll use it as it's, Thank u
