### ISSUE TITLE
Possible Support for Intel WiFi & Bluetooth

### ISSUE THREAD

**Issue by AutinMitra** [tylernguyen/x1c6-hackintosh#37]
Seems like someone has created working (but unstable) Intel wifi drivers for macOS. The kext seems to be WIP and closed source, but it's at least a partially working driver. I haven't been able to test it though, since my X1C6 is currently being serviced.

[XiaoMi Pro Intel Wifi - daliansky](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/330)

**Comment by tylernguyen** [comment]
@AutinMitra Thank you for bringing this to my attention. I don't have an Intel WiFi card on hand right now but I will keep this in mind and test this soon!

**Comment by AutinMitra** [comment]
Found the source for the WiFi driver: [zxystd](https://github.com/zxystd/AppleIntelWifiAdapter/tree/feature-rewrite-all)

According to XiaoMi users, you can connect to the internet, but heavy tasks like downloading or running tests will lead to a restart/panic.

**Comment by tylernguyen** [comment]
Watching:  
https://intelwifi.0xcc.pw/ and https://github.com/AppleIntelWifi/adapter

**Comment by tylernguyen** [comment]
https://github.com/tylernguyen/x1c6-hackintosh/issues/67
