### ISSUE TITLE
cfg lock and native power management

### ISSUE THREAD

**Issue by freedom95** [tylernguyen/x1c6-hackintosh#38]
Battery management is not available on my machine with opencore. Then i found that it is related to the BIOS's CFG Lock. I tried many ways, but all failed. Is there any way to open CFG Lock on x1c? Or is this machine restricted from enabling this option. Thanks!

**Comment by velaar** [comment]
Looked into it quite a bit. To the best of my knowledge there is no way. There are rumours of unlocked machines in existence but those are limited to developer units and were never sold to public.

**Comment by tylernguyen** [comment]
@freedom95 When you say battery management, what do you mean specifically? I would love to look more into this issue.

**Comment by FlasHRender** [comment]
Wait. Why can't you use setup_var to unlock cfg lock?

**Comment by velaar** [comment]
Bios is checksummed and you don’t have wrote access to that area.

**Comment by PhantomZNeuroX** [comment]
Hey guys, you might be able to use "ru.efi" to unlock cfg lock. i am not a x1c user but stumbled upon this issue through google. I own a Mi notebook 14 Horizon edition and was able to unlock my CFG lock through this tool. Here is a guide for the same. 

https://www.reddit.com/r/hackintosh/comments/hz2rtm/cfg_lockunlocking_alternative_method/
