### ISSUE TITLE
Clover is not showing OS X installations

### ISSUE THREAD

**Issue by harshach** [tylernguyen/x1c6-hackintosh#4]
@tylernguyen Thanks for putting together this guide.
I followed the Steps but when I boot it doesn't show the installation options except the UEFI Shell, options, Reboot, exit etc.. . I tried using high sierra and mojave both are exhibiting the same issue.
Any suggestions from you. Is it related to usb disk?

**Comment by harshach** [comment]
Looks like adding HFSPlus.efi solved it. I can see the boot option and once I boot into it the os x is restarting

**Comment by harshach** [comment]
Once USB os x Installer finishes and reboots I can see the two options one with Internal and External. To complete the installation when I click Internal and the installer continues with the Apple logo. Once the installation reaches "About 15 minutes remaining" it keeps restarting. I tried verbose mode it doesn't show any specific errors and boots into Apple logo and gets into the restart the loop. I am using the exact hardware as your except I am still on NVME SSD.

**Comment by tylernguyen** [comment]
Hello,

The reason is most likely because you're still using the stock NVME that comes with the laptop. That drive is incompatible with macOS. I suggest you replace with either a SAMSUNG M.2 NVME or a SAMSUNG M.2 SATA. 
See --> 1_README-HARDWAREandBIOS.md. 
*Stock PM981 support is an ongoing issue, see https://www.tonymacx86.com/threads/x1-carbon-2017-5th-cant-install-high-sierra-due-to-the-ssd-pm981.243126/.

**Comment by harshach** [comment]
Thanks @tylernguyen . Did you try installing Mojave? and does it work with existing instructions

**Comment by harshach** [comment]
@tylernguyen with SATA M.2 I am able to install Mojave and once I come to the second step. I am copying Kexts from your repo under Library/Extensions using KextBeast. Once I reboot through the ssd it restarts but if I use the USB its able to boot. I tried with HighSierra same issue. Any ideas? looks like kext copying is not working

**Comment by harshach** [comment]
@tylernguyen manage to install Mojave. Thank for your guide. Except sound everything is working. Which part of the steps will enable sound

**Comment by mattbajorek** [comment]
I also had a similar issue as @harsarch. For clarity download HFSPlus.efi from:

https://github.com/JrCs/CloverGrowerPro/blob/master/Files/HFSPlus/X64/HFSPlus.efi?raw=true

Place the file in EFI/CLOVER/driver64UEFI
