### ISSUE TITLE
Slow Quicklook

### ISSUE THREAD

**Issue by Porco-Rosso** [tylernguyen/x1c6-hackintosh#41]
Hi, I was wondering if any of you are also experiencing this bug. 
I am using the latest Opencore EFI, as of now and Quicklook is extremely slow.
It takes about seconds to load a simple png, jpg or heic. PDFs are still working almost instantly on the other hand.

some searching turned up this: https://www.tonymacx86.com/threads/quicklook-doesnt-preview-jpgs-mp3-nor-mp4.255133/page-35
So I thought I best ask here, to see if it is a hardware config issue, or if it is something unique to my software setup. Any tips on how to debug would be appreciated.

**Comment by tylernguyen** [comment]
@Porco-Rosso I'm not experiencing this problem. Did you have this problem prior to updating to the latest EFI folder? If possible, can you please provide the file you're having trouble with so I test it on my machine.

**Comment by Porco-Rosso** [comment]
I've managed to fix the issue - Catalina is really not making it easy with all these bugs...
At the end I followed [these instructions](https://apple.stackexchange.com/questions/338215/mojave-quicklook-stuck-at-loading), which not only fixed the quicklook issue, but also magically fixed my MX Mouse 3 problems (Logitech Options would not open correctly).

**Comment by tylernguyen** [comment]
@Porco-Rosso I'm happy that it's a macOS bug and not a hackintosh one. Thanks for updating on how you solved the problem.
