### ISSUE TITLE
I installed macOS on my factory PM981

### ISSUE THREAD

**Issue by zacharysalvatore** [tylernguyen/x1c6-hackintosh#43]
After tried several days and countless failures, I managed to install macOS 10.15.4 on my factory PM981.
Here's how i achieve this.
1. Do a fresh macOS installation on a supported ssd. (note: do not enter system for now)
2. Back up the volume partition using paragon hard disk manager. 
3. Restore that backup image to PM981
4. Put "ssdt-nvme.aml" and "HackrNVMeFamily-10_12_6_sec2018-001.kext" to its corresponding folder and add those aml and kext to your config.plist.(Note: replace your nvme controller's ID to your own which can be found on Windows device manager).
5. Instert your bootable USB which containing opencore EFI to boot your system.
![IMG_8449](https://user-images.githubusercontent.com/14255685/78518070-e1f56180-77f1-11ea-8dde-b9f69dde3df0.JPG)
![Snipaste_2020-04-06_02-27-34](https://user-images.githubusercontent.com/14255685/78518002-a0fd4d00-77f1-11ea-8fe3-91689c3a6752.png)
![MaciASL 2020-04-06 at 10 18 33@2x](https://user-images.githubusercontent.com/14255685/78518006-a3f83d80-77f1-11ea-8cb5-1510a82c69bb.png)

**Comment by tylernguyen** [comment]
@zacharysalvatore Thanks again for your contribution! It's a lot to ask after you have a stable system going. But it seems that the new NVMeFix should support installing macOS on the PM981. Could you please try going through the install again with NVMeFix and seeing if that also fixes the problem?

**Comment by tylernguyen** [comment]
See [NVMeFix](https://github.com/acidanthera/NVMeFix) README.md line #6 for more details.

**Comment by zacharysalvatore** [comment]
> @zacharysalvatore Thanks again for your contribution! It's a lot to ask after you have a stable system going. But it seems that the new NVMeFix should support installing macOS on the PM981. Could you please try going through the install again with NVMeFix and seeing if that also fixes the problem?

One thing I could confirm is that using NVMEFix1.0.2 without ssdt-nvme.aml and HackrNVMeFamily.kext result in failure installation. 

I think I could try reinstall the whole OS after a full disk backup.

**Comment by tylernguyen** [comment]
> > @zacharysalvatore Thanks again for your contribution! It's a lot to ask after you have a stable system going. But it seems that the new NVMeFix should support installing macOS on the PM981. Could you please try going through the install again with NVMeFix and seeing if that also fixes the problem?
> 
> One thing I could confirm is that using NVMEFix1.0.2 without ssdt-nvme.aml and HackrNVMeFamily.kext result in failure installation. 
> 
> I think I could try reinstall the whole OS after a full disk backup.

NVMeFix arable is currently on 1.0.1

Did you compile your own NVMeFix?

**Comment by zacharysalvatore** [comment]
> > > @zacharysalvatore Thanks again for your contribution! It's a lot to ask after you have a stable system going. But it seems that the new NVMeFix should support installing macOS on the PM981. Could you please try going through the install again with NVMeFix and seeing if that also fixes the problem?
> > 
> > 
> > One thing I could confirm is that using NVMEFix1.0.2 without ssdt-nvme.aml and HackrNVMeFamily.kext result in failure installation.
> > I think I could try reinstall the whole OS after a full disk backup.
> 
> NVMeFix stable release is currently on 1.0.1
> 
> Did you compile your own NVMeFix?
> 
> Also, keep in mind that NVMeFix requires at least Lilu 1.4.1

I use your Lili which is 1.4.2.
In [Anti-Hackintosh Buyers Guide](https://khronokernel-5.gitbook.io/anti-hackintosh-buyers-guide/storage) says PM981 has been fixed with NVMeFix ver. 1.0.2.
I download NVMeFix ver 1.0.2 in OpenCore Vanilla Guide recommended [Kext repo ](http://kexts.goldfish64.com/)

**Comment by zacharysalvatore** [comment]
I think we could make it clear only by replica the whole installation process. As you say I'm now having a stable system going, it's a tough decision to do it again. But I think I could try backup my whole disk and try reinstall macOS when it's possible. I'll let you know after I get a final conclusion. Before that i think i'll close this issue.

**Comment by tylernguyen** [comment]
@zacharysalvatore Thank you again for your input! I would test it myself but I no longer have a PM981. Once you get the chance to reinstall with NVMeFix 1.0.2, please update the issue.

**Comment by Porco-Rosso** [comment]
I still have my PM981, although I am reluctant to switch back. What would I have to do besides clone my drive over to get this working? Used "ssdt-nvme.aml" and "HackrNVMeFamily-10_12_6_sec2018-001.kext" ?
One the flip side, I now feel stupid for not having waited a little longer. I could have saved a few hundred dollars :(

**Comment by zacharysalvatore** [comment]
> I still have my PM981, although I am reluctant to switch back. What would I have to do besides clone my drive over to get this working? Used "ssdt-nvme.aml" and "HackrNVMeFamily-10_12_6_sec2018-001.kext" ?
> One the flip side, I now feel stupid for not having waited a little longer. I could have saved a few hundred dollars :(

If you only have one ssd installed in your device then switch back your pm981 add ssdt-nvme.aml and HackrNvme***.kext and edit config.plist to your Opencore EFI bootable USB drive. I don'ts konw if your Nvme controller's ID is the same with mine. If so just use the file driectly, change to your Nvme controller's ID otherwise. I installed my macOS by restoring a successfuly installed pure system backup image to PM981. I don't know if it is working for fresh install on PM981 directly.

**Comment by tylernguyen** [comment]
@Porco-Rosso If you would, try a fresh install using NVMeFix 1.0.2 without "ssdt-nvme.aml" and "HackrNVMeFamily-10_12_6_sec2018-001.kext" and see if that is sufficient.

**Comment by zacharysalvatore** [comment]
> @Porco-Rosso If you would, try a fresh install using NVMeFix 1.0.2 without "ssdt-nvme.aml" and "HackrNVMeFamily-10_12_6_sec2018-001.kext" and see if that is sufficient.

I tried before. It results a failure.

**Comment by tylernguyen** [comment]
@zacharysalvatore Do you have the specific log output?

**Comment by zacharysalvatore** [comment]
> @zacharysalvatore Do you have the specific log output?

Unfortunately I forgot to save log files.

**Comment by tylernguyen** [comment]
@zacharysalvatore If you can, please try to capture the kernel panic logs when trying to install with NVMeFix 1.0.2

If we have the kernel panic logs, we can open an issue with dev team to have it fixed.

**Comment by zacharysalvatore** [comment]
With the release of NVMeFix ver 1.0.2 (not dev version), I tried it out and the result is that with this i could boot successfully to OS without the help of `ssdt-nvme.aml` and `HackrNVMeFamily-10_12_6_sec2018-001.kext`. 
In [README](https://github.com/acidanthera/NVMeFix/blob/master/README.md) of NVMeFix states that 
> If active power management initialisation is successful, an `NVMePMProxy` entry will be created in the IOPower IORegistry plane with IOPowerManagement dictionary.
However I can't find `NVMePMProxy` entry in my IOPower IORegisty plane. And my APST state is `true` **as I don't know where to and how to specify `ps-max-latency-us = 0` correctly**. I think with the lack of `NVMePMProxy` is the reason why high PKG > 2 when idle. 
![CleanShot 2020-04-10 at 07 30 02@2x](https://user-images.githubusercontent.com/14255685/78949491-4704cc00-7afe-11ea-8baa-cb80fe1bd654.png)
I tried to specify this property here but in vain.
![Python 2020-04-10 at 07 38 59@2x](https://user-images.githubusercontent.com/14255685/78949544-6bf93f00-7afe-11ea-8627-ceca43b004dc.png)
sorry about this screenshot. it should be under IONVMeController and there's a apst = true in that plane:
![IORegistryExplorer 2020-04-09 at 19 11 12@2x](https://user-images.githubusercontent.com/14255685/78949663-c98d8b80-7afe-11ea-9ab6-d1fdef9a81b3.png)
This is NVMe state with the help of `ssdt-nvme.aml` and `HackrNVMeFamily-10_12_6_sec2018-001.kext`:
![IORegistryExplorer 2020-04-10 at 07 35 30@2x](https://user-images.githubusercontent.com/14255685/78949717-00fc3800-7aff-11ea-8415-7b40117b8968.png)

**Comment by tylernguyen** [comment]
@zacharysalvatore I'm glad that PM981 finally boot without anything else. I will modify the guide to note that a drive replacement is no longer necessary. 

Regarding `NVMePMProxy`, per NVMeFix 1.0.2 changelog:
**"Only enable active NVMe power management for controllers that do not support APST"**
Since apst is true for the PM981, `NVMePMProxy` will not appear.

If apst is working properly, I suggest that you do not swtich to active NVMe power management. However, should you wish to, you need to find the device path of the PM981, then creating a dictionary for it under Device Properties, similar to the video and audio device. This is where you can set `ps-max-latency-us = 0`.

**Comment by zacharysalvatore** [comment]
> @zacharysalvatore I'm glad that PM981 finally boot without anything else. I will modify the guide to note that a drive replacement is no longer necessary.
> 
> Regarding `NVMePMProxy`, per NVMeFix 1.0.2 changelog:
> **"Only enable active NVMe power management for controllers that do not support APST"**
> Since apst is true for the PM981, `NVMePMProxy` will not appear.
> 
> If apst is working properly, I suggest that you do not swtich to active NVMe power management. However, should you wish to, you need to find the device path of the PM981, then creating a dictionary for it under Device Properties, similar to the video and audio device. This is where you can set `ps-max-latency-us = 0`.

I've found where to add `ps-max-latency-us = 0` property. However, APST is still on.
![iTerm 2020-04-10 at 13 22 49@2x](https://user-images.githubusercontent.com/14255685/78965494-cced3b00-7b2f-11ea-8d2f-7e40d02ab94b.png)
![Python 2020-04-10 at 13 23 54@2x](https://user-images.githubusercontent.com/14255685/78965525-de364780-7b2f-11ea-80d6-bcc0bc3488b7.png)
![IORegistryExplorer 2020-04-10 at 13 34 01@2x](https://user-images.githubusercontent.com/14255685/78965605-13429a00-7b30-11ea-8ef4-458ef7ab80ba.png)
![IORegistryExplorer 2020-04-10 at 13 34 26@2x](https://user-images.githubusercontent.com/14255685/78965611-163d8a80-7b30-11ea-993c-136c688cec04.png)

**Comment by tylernguyen** [comment]
@zacharysalvatore  Maybe I am reading NVMeFix's documentation wrong. But that seems like a bug with NVMeFix. Please open an issue with acidanthera's bugtracker https://github.com/acidanthera/bugtracker/issues

**Comment by zacharysalvatore** [comment]
> @zacharysalvatore Maybe I am reading NVMeFix's documentation wrong. But that seems like a bug with NVMeFix. Please open an issue with acidanthera's bugtracker https://github.com/acidanthera/bugtracker/issues

[issues #830](https://github.com/acidanthera/bugtracker/issues/830) is created.

**Comment by 07151129** [comment]
> @zacharysalvatore I'm glad that PM981 finally boot without anything else. I will modify the guide to note that a drive replacement is no longer necessary.

Note that prior testing is still recommended: some users report that the patch does not help them. However, it always worked on our test machines.

**Comment by zacharysalvatore** [comment]
> @tylernguyen 
> 
> 
> 
> > @zacharysalvatore I'm glad that PM981 finally boot without anything else. I will modify the guide to note that a drive replacement is no longer necessary.
> 
> 
> 
> Note that prior testing is still recommended: some users report that the patch does not help them. However, it always worked on our test machines.
> 
> 
> 
> 

With NVMeFix alone will boot macOS on PM981 doesn’t mean it could help during fresh installation. I’ll test a fresh installation next week when I got time.

**Comment by antoniomcr96** [comment]
I have a laptop (Lenovo L390) with PM981 drive. I tried to do a fresh install of Catalina with NVMeFix. I attached the result.
I can't even get it to boot with SSDT-Nvme and HackrNvme Kext. So I'm not sure this is the main problem but it's the only option.
![verbose](https://user-images.githubusercontent.com/63928525/79671071-c877f080-81c7-11ea-9f98-bbe7c5b1f8e5.jpg)

**Comment by 07151129** [comment]
@antoniomcr96 are you sure this is caused by the disk?

**Comment by antoniomcr96** [comment]
> @antoniomcr96 are you sure this is caused by the disk?

Tried different versions of CLOVER and OC, with the help of someone certainly more experienced than me but we haven't found any possible reason. I manage to solve "AppleNVMe Assert failed" with SSDT-NVMe but it doesn't boot. It's the only explanation at the moment, but if someone succed to install Catalina with just NVMeFix.kext I'll be sure my problem is another one. Unfortunally nobody have ever done a project on this laptop

**Comment by 07151129** [comment]
My question was if this issue is specific to PM981, so does swapping to another NVMe model work? "Fixing" the failing assert does not make sense, it's not an error and is expected for non-apple computers.

**Comment by antoniomcr96** [comment]
> My question was if this issue is specific to PM981, so does swapping to another NVMe model work? "Fixing" the failing assert does not make sense, it's not an error and is expected for non-apple computers.

Thanks for the excellent clarification. It’s my second hackintosh project so I don’t have a lot of experience, and I have been trying to “fix” things for days . Unfortunately at the moment I don’t have another NVMe but I’m planning to buy. Discovering if this is the real problem could help me to make a choice, so I’m waiting for news by someone else who tries a fresh install :)

**Comment by zacharysalvatore** [comment]
I've backed-up my whole disk and tried a fresh installation many times yesterday. Here's the conclusion:

> 1. Fresh Installation with `NVMeFix` ver 1.0.2 alone won't work, even with `ssdt-nvme.aml` and `HackrNVMeFamily-10_12_6_sec2018-001.kext`.
> 2. Update 10.15.4 supplemental update with `NVMeFix` ver 1.0.2 alone --> Success.

thus, we couldn't do installation on PM981 in a normal manner unfortunately. We could only install macOS on PM981 in a indirect way (steps I wrote in the beginning of this issue). Due to I had my supported SSD returned, I used another way to install macOS to my PM981. Here's the steps:

> 1. Find a large enough external drive as you like such as an USB disk or a removable HDD (a fast drive is prefered).
> 2. Install macOS on VM machine. Create a VM machine and mount that external drive to VM machine. (you could google it how. no opencore EFI needed here).
> 3. Back up your external drive which containing macOS installed using paragon hard disk manager.
> 4. Restore that backup image to PM981.
> 5. Instert your bootable USB which containing opencore EFI to boot your system.

Lastly, there're few things I'd like to point out in your code:

> 1. config.plist and drivers inconsistency. Lack of TbtForcePower.efi files in drivers folder, however you forget to revmoe it from config.plist
> 2. I'd suggest you disable SIP in your install EFI because enabing hidpi needs SIP disabled frist.
> 3. In your install EFI configuration, I think you should set scan policy to 0 in order to see the macOS installation drive otherwise we could not see installation drive.

**Comment by antoniomcr96** [comment]
> I've backed-up my whole disk and tried a fresh installation many times yesterday. Here's the conclusion:
> 
> > 1. Fresh Installation with `NVMeFix` ver 1.0.2 alone won't work, even with `ssdt-nvme.aml` and `HackrNVMeFamily-10_12_6_sec2018-001.kext`.
Sorry, can you reach the installer with this drive or does it get stuck on loading? Thanks

**Comment by zacharysalvatore** [comment]
> > I've backed-up my whole disk and tried a fresh installation many times yesterday. Here's the conclusion:
> > 
> > 1. Fresh Installation with `NVMeFix` ver 1.0.2 alone won't work, even with `ssdt-nvme.aml` and `HackrNVMeFamily-10_12_6_sec2018-001.kext`.
> 
> Sorry, can you reach the installer with this drive or does it get stuck on loading? Thanks

Yes. I create the installer myself. First, I install win10 on PM981. Then, install macOS to your external drive on win10 in VMware (mount your physical removable HDD to vmare). Last, backup that removable HDD and restore it's contents to your PM981. Done.

**Comment by antoniomcr96** [comment]
> > > I've backed-up my whole disk and tried a fresh installation many times yesterday. Here's the conclusion:
> > > 
> > > 1. Fresh Installation with `NVMeFix` ver 1.0.2 alone won't work, even with `ssdt-nvme.aml` and `HackrNVMeFamily-10_12_6_sec2018-001.kext`.
> > 
> > 
> > Sorry, can you reach the installer with this drive or does it get stuck on loading? Thanks
> 
> Yes. I create the installer myself. First, I install win10 on PM981. Then, install macOS to your external drive on win10 in VMware (mount your physical removable HDD to vmare). Last, backup that removable HDD and restore it's contents to your PM981. Done.

Thanks for the prompt reply. I will try this method in the next days. 
Actually I wanted to ask you if you can’t fresh install because it get stuck on boot (before the installer loads). I have this problem and I don’t know if it’s the disk or something else

**Comment by tylernguyen** [comment]
@zacharysalvatore 
Thank you so much for your research and contribution! I will update the repo to reference this issue for PM981 installations. 

Also, I think you suggestions to EFI-install makes sense. I will make the proposed changes in the next commit. Thanks again.

**Comment by tylernguyen** [comment]
@07151129 I may be willing to get a PM981 so I can get to the bottom of this issue myself. What would you need from me to be able to create a fix?

**Comment by 07151129** [comment]
Dedicated machine and a kernel debugger, solid understanding of IOKit and xnu driver design principles, understanding of IONVMeFamily code, NVMe protocol, vfs

**Comment by ajhutton** [comment]
I have a PM981 and I have done the following steps:

1. made an installer from a real mac and put it on a spare m.2 sata drive
2. replaced PM981 with internal M.2 sata drive formatted with EFI partition, 10.15.4 installer and the rest free space
3. installed catalina to free space
4. reinserted PM981, placed sata drive in usb enclosure and used dd to copy the os X install partition (apfs) to an empty parition of equiv size on the PM981
5. setup rEFInd on the internal PM981 to be able to choose between Linux grub .efi bootloader file in other directory or the OC/OpenCore.efi file

I have attempted booting so far using:

- just NVMeFix kext (1.0.2, with latest Lilu)
- NVMeFix kext with the hackrnvme kext as well as the ssdt-nvme fix
- generated my own hackernvme kext with rehabman's tool and this patch applied https://github.com/RehabMan/patch-nvme/pull/54/files for 10.15.1 supposedly, tried that with nvmefix and ssdt-nvme to no avail.

I'm happy to test things out if anybody has any ideas.

**Comment by FlasHRender** [comment]
I can confirm @zacharysalvatore's method of booting macOS 10.15.4 on PM981 works. I haven't had 1 single issue so far. Process is long but worth it. 
![Screenshot 2020-05-02 at 3 14 04 PM](https://user-images.githubusercontent.com/5005743/80860773-b0a07200-8c87-11ea-904a-00af875b8884.png)

**Comment by alexdrean** [comment]
@tylernguyen I'd be willing to send you a PM981 if you are in North America so you can troubleshoot. Will gladly pay for shipping + return.

**Comment by Ranguvar** [comment]
I believe this is still broken, unfortunately.
Thank you @tylernguyen and especially @zacharysalvatore for the advice here.

I have an installed APFS macOS on a USB disk which I can use Paragon to clone to my PM981 and have tried multiple fresh clones from there.

I can usually boot the installed system using the EFI-install_USB, and it works very well.

However, I can still get it to kernel panic if I write a couple GB of data to the PM981 using dd as a test: `dd if=/dev/urandom of=<some_path_on_pm981_volume> bs=1048576 count=10240`

The kernel panic does reference NVMe explicitly.
[kernel_panic_writing_10gb_usb.txt](https://github.com/tylernguyen/x1c6-hackintosh/files/4644933/kernel_panic_writing_10gb_usb.txt)

Similarly, if I try to use EFI-OpenCore -- my DSDT is barely any different from yours tyler, looks like just a few addresses changed as I'm on 1.47 BIOS -- and I use the verbose -v to see what is going on, then about 80% of the time NVMe will fail before the system finishes booting.

![EFI-OpenCore stock failed boot](https://user-images.githubusercontent.com/309531/82229079-f734d400-98f7-11ea-8a07-6c81a791c1b1.jpg)

Sometimes the boot will work and everything works beautifully, until I write a bunch to the disk again.

I believe I tried moving NVMeFixup just after Lilu but it seemed Lilu would try to save nvram.plist and cause the NVMe kernel panic still.

I have tried using ssdt-nvme.aml and HackrNVMeFamily kext. What I did was load the Hackr kext first, before Lilu, and then NVMeFixup, then everything else, and loading ssdt-nvme first as well.

This still ended in a crashed boot, with an AppleNVMe Assert failed this time, bit different.

![EFI-OpenCore with ssdt-nvme.aml and HackrNVMeFamily](https://user-images.githubusercontent.com/309531/82229243-32cf9e00-98f8-11ea-977a-42343c131cd0.jpg)


I would really appreciate any ideas, happy to install debug versions and save logs, report to NVMeFixup, etc.

Thank you all!

Attached is the kernel panic achieved from EFI-install_USB booting the just-installed system from PM981 and then writing data with dd.
Also two screensh

**Comment by Ranguvar** [comment]
Further update, I believe PM981 should be marked as still broken @tylernguyen.
NVMeFix tickets are being closed as wontfix.

https://github.com/acidanthera/bugtracker/issues/843
https://github.com/acidanthera/bugtracker/issues/848

**Comment by zacharysalvatore** [comment]
@Ranguvar My hackintosh works very well so far. I've tried writing random data using dd successfully.
<img width="1440" alt="CleanShot 2020-05-19 at 10 59 09@2x" src="https://user-images.githubusercontent.com/14255685/82279922-3cbcd400-99c0-11ea-9c7a-9402e9e76af5.png">

**Comment by Ranguvar** [comment]
@zacharysalvatore Interesting, thank you.
You're also on an X1C6 type KH?
Would you mind sharing your EFI for me to play with?
I was about to give up and copy all data to another SSD.

**Comment by zacharysalvatore** [comment]
@Ranguvar Would love to. Here's the file.
https://www.dropbox.com/sh/9pirv8zi9unar47/AAChUJjf31NO-ZF2cInAqQSBa?dl=0

**Comment by Ranguvar** [comment]
@zacharysalvatore Thank you very much!!
Working perfectly so far.
I will look closer tomorrow, and if I can find out what the difference is I will report back.

@ajhutton you may wish to try this as well.

**Comment by zacharysalvatore** [comment]
@Ranguvar I'm glad it works fine for you. Do remind to replace SMBIOS Info with your own.

**Comment by Ranguvar** [comment]
Definitely. It will be scrubbed before I connect to the Internet at all.

You may wish to scrub it on here if other people download it.

**Comment by zacharysalvatore** [comment]
@Ranguvar THX. Already removed my own SMBIOS info from config.plist and uploaded.

**Comment by tylernguyen** [comment]
@zacharysalvatore Thank you again for helping out.
@Ranguvar Please stress test it as much as possible. Also, please check the difference between his EFI and yours. I want to know what's going on particularly.

**Comment by FlasHRender** [comment]
> @zacharysalvatore Interesting, thank you.
> You're also on an X1C6 type KH?
> Would you mind sharing your EFI for me to play with?
> I was about to give up and copy all data to another SSD.

![Screenshot 2020-05-20 at 12 05 28 AM](https://user-images.githubusercontent.com/5005743/82365053-bccd5300-9a2d-11ea-80a0-23a7dd7d0952.png)

Also I'm on a Zenbook and not a X1. But the drive is PM981. 



> @zacharysalvatore Thank you again for helping out.
> @Ranguvar Please stress test it as much as possible. Also, please check the difference between his EFI and yours. I want to know what's going on particularly.

Hi. I have been using PM981 as dd and haven't faced a single issue and have performed stress test and also written and read over 300 GB over the past few days. Everything seems to work just fine.

**Comment by arepson** [comment]
It's support to system update?

**Comment by tylernguyen** [comment]
> It's support to system update?

Good question. @Ranguvar @FlasHRender @zacharysalvatore Can you guys confirm if this installation method can survive a macOS update?

**Comment by Ranguvar** [comment]
I'm perhaps not the best to test as I've been having failures to boot - likely kernel panic, haven't had time to investigate.

Still, I tried updating from 10.15.4 to 10.15.5, PM981 and all. I left it to reboot itself and eventually came upon this error.

![71](https://user-images.githubusercontent.com/309531/83088245-2dddbd80-a061-11ea-9c50-2872b3e1698d.jpg)

I'm now trying to reboot again and it seems to be kicking back to the update installer. It now says 40+ minutes remaining, just as it did at one point before.

I don't expect this to work, but not I'm sure if it will be different for you folks unfortunately. Thanks to the beautiful and comprehensive work by @tylernguyen and @zacharysalvatore all the same, because having this nearly perfect did convince me for now to pick up a MacBook Pro, largely for the trackpad. I'll probably try this again on the 2230 NVMe drive I just got soon.

**Comment by tylernguyen** [comment]
@Ranguvar Good to have you here.

And yeah, seems like the PM981 will always be somewhat problematic, so users might be just better off with an aftermarket NVMe drive.

Regarding the touchpad, [VoodooSMBUS](https://github.com/VoodooSMBus/VoodooSMBus) should be getting an update soon that improves the touchpad performance on the x1c6.  You should watch for it and try it once it's released.

**Comment by zacharysalvatore** [comment]
Mine is stuck with the same error as @Ranguvar  right now.

**Comment by tylernguyen** [comment]
@zacharysalvatore Thank you for your input. I will update the repo with comments on this issue regarding the PM981 and make a recommendation for an after market NVMe instead.

**Comment by zacharysalvatore** [comment]
I did nothing except reset NVRAM and select update installer at bootloader screen then SUCCESS!

![IMG_8907](https://user-images.githubusercontent.com/14255685/83232832-5fb96600-a1c0-11ea-9c18-f759cc8b8691.jpg)
![IMG_8909](https://user-images.githubusercontent.com/14255685/83232834-5fb96600-a1c0-11ea-8c54-0b39477e92f4.jpg)
<img width="1440" alt="CleanShot 2020-05-29 at 15 15 15@2x" src="https://user-images.githubusercontent.com/14255685/83232835-5fb96600-a1c0-11ea-9667-ab07f0ca1c5b.png">

**Comment by GUNNERSx** [comment]
hi there... My first hackingtosh projet...
@zacharysalvatore i have the PM981 tried do fresh install no luck :(
I follow your tuto but have all ready the backup with paragon and nvme controller's ID.
But i don't understand how to 👉"add those aml and kext to your config.plist" 
Any help's welcome...

**Comment by zacharysalvatore** [comment]
@GUNNERSx Use OC config to do this.

**Comment by FlasHRender** [comment]
1) I would not suggest PM981 install for anyone who is doing this for the first time. 
2) PM981 installs are not stable and have sleep issues.
3) Just get a new drive or use windows, unless you are experienced enough to actually get everything working.

**Comment by gplast** [comment]
Hello @zacharysalvatore,

Can you please specify how exactly did you manage to backup the drive that you install mac os?  Unfortunately my work gave me a PM981 with windows installed and i'm doing everything that i can in order to avoid deleting windows on the drive. I even put the drive on different laptop just to confirm that it was actually the disk.

So my question is, i installed MacOS on a usb Drive and i would like to backup that and restore it on the internal drive. I copy the partition using MiniTool Partition but it seems that is not working, since i have problem booting into the drive.

Thank you very much for all the help!

**Comment by zacharysalvatore** [comment]
> Hello @zacharysalvatore,
> 
> 
> 
> Can you please specify how exactly did you manage to backup the drive that you install mac os?  Unfortunately my work gave me a PM981 with windows installed and i'm doing everything that i can in order to avoid deleting windows on the drive. I even put the drive on different laptop just to confirm that it was actually the disk.
> 
> 
> 
> So my question is, i installed MacOS on a usb Drive and i would like to backup that and restore it on the internal drive. I copy the partition using MiniTool Partition but it seems that is not working, since i have problem booting into the drive.
> 
> 
> 
> Thank you very much for all the help!
> 
> 

Installing on PM981 could be quite troublesome though it do come to success eventually. Running macOS on PM981 is quite stable, but it usually causes problems when updating system. So I bought a WD ssd once and for all. I’ll write a step by step tutorial and post here.

**Comment by FlasHRender** [comment]
As @zacharysalvatore mentioned its just better to get a cheap replacement for the drive. I got myself a Silicon Power 34A80 1TB drive with SMI SM2262EN and Intel flash. It works OOB and way lower power consumption and is much faster than PM981.

**Comment by gplast** [comment]
I completely agree with you, the only problem is that this is my work laptop, so i'm not allowed to open it (i already did that just to confirm that was an SSD error and it is) so i don't want to replace the drive, and i spend the last week trying everything just to find a workaround.

I tried to install it using VMware on a USB drive, then boot to linux and use dd to copy the drive into an empty partition, but it seems that is not booting from the drive, only when i have the USB connected is trying to boot but again it freezes at some point.

I think that i'm missing something when i'm cloning the drive, thats why i'm asking a clarification about this step :) 

If that was my personal laptop (i have a Mi Notebook pro and i actually replace my drive with a 960 Pro, re-paste it with liquid metal etc.) I would definitely replace the drive at once.

Thank you for your replies!

**Comment by antoniomcr96** [comment]
Managed to install! For some reason i5-8265u needs SSDT-AWAC to boot.
I used VirtualBox with a virtual disk linked to a physical drive (external USB drive). Then I booted with OpenCore from external drive to fix things like graphics, audio, usb and so on. Even though I'm not booting from the NVME PM981 itself I saw random kernel panic on boot related to "com.apple.iokit.IONVMeFamily". I took some pictures. I had 6 partition (EFI+Windows+Ubuntu+FutureHackintosh (HFS, empty)+Data1+Data2) on that drive, I deleted the last three and now I don't see kernel panic anymore.
I'm only using NvmeFix.kext. Do "SSDT-Nvme" and "HackrNVMeFamily-*" improve the situation?
Copying large files or executing stuff from PM981 doesn't seem to create problems.
Now I'm planning to use dd from linux to copy the partition to PM981 (is it the right way?). Can I use a FAT32 partition? dd will update the file system?
Another idea is to update the system to Big Sur using VirtualBox when public beta will be available to see if things will get better, who knows.

**Comment by Kaijun** [comment]
Hi all,

i'm using pm981(MZVLB512HAJQ-000L7) only with NVMeFix

BigSur installaer can recognize my ssd and partitions, but it always stuck at '14 minutes remaining' and then freeze.

should i use the recover method to install?

BTW, is the latesst NVMeFix already enough for the hack? or should i also have ssdt-nvme.aml and HackrNVMeFamily.kext in addition?

**Comment by antoniomcr96** [comment]
> Hi all,
> 
> i'm using pm981(MZVLB512HAJQ-000L7) only with NVMeFix

PM981 at the moment doesn’t work and hasn’t ever worked. I tried many times with Big Sur. I finally replaced the disk. 

You can choose:
1. Remove the NVMe drive and install Big Sur on an external usb drive (probably with a virtual machine). Then boot from it.
2. Replace the disk with something that surely works with macOS

**Comment by tylernguyen** [comment]
As @antoniomcr96 stated,

Though the process is possible without various workarounds. I don't really recommend it as it can be quite troublesome, buggy, and overall not very well supported by the community. I suggest you get a more compatible drive and resell your PM981.

**Comment by Kaijun** [comment]
> > Hi all,
> > i'm using pm981(MZVLB512HAJQ-000L7) only with NVMeFix
> 
> PM981 at the moment doesn’t work and hasn’t ever worked. I tried many times with Big Sur. I finally replaced the disk.
> 
> You can choose:
> 
> 1. Remove the NVMe drive and install Big Sur on an external usb drive (probably with a virtual machine). Then boot from it.
> 2. Replace the disk with something that surely works with macOS

@antoniomcr96 @tylernguyen 

for now, i have to use this shitty PM981 to build my hack.  😢 

as @antoniomcr96 did in comment https://github.com/tylernguyen/x1c6-hackintosh/issues/43#issuecomment-650735658 , I installed BigSur on my another hackintosh build and backup the disk with paragon software. then restore back to PM981 on windows.

However, it seems that opencore can not recognize the restored disk. do you know why?
I am using NVMeFix without any other Kext/DSDT, and  opencore can recognize the USB Installer indeed.

**Comment by antoniomcr96** [comment]
> However, it seems that opencore can not recognize the restored disk. do you know why?
> I am using NVMeFix without any other Kext/DSDT, and opencore can recognize the USB Installer indeed.

Honestly I can’t help you. I did exactly the same except for the fact that I didn’t create an intermediate image file, but instead I did a direct copy from a disk to the other one with paragon software in windows.

However, since I (and, like me, other users) have wasted a lot of time trying to make the disk work, it is honestly not worth it. The system will probably boot but you will have constant kps and slowdowns. It is a waste of time, at least in this moment.

Buy a cheap 256gb NVMe drive if you can (except Intel 600p, another drive that gives problems)

**Comment by alexdrean** [comment]
@Kaijun I really, really don't recommend going the PM981. You get it working and next thing you know it kernel panics at boot. Wasted a month trying every possible workaround... which always seems to work until it doesn't.
256/512/1024 GB SX6000 is $35/45/90 on Amazon. Will be well-spent money unless some hackintosh whizz can figure out what is wrong with this drive.

**Comment by Kaijun** [comment]
> @Kaijun I really, really don't recommend going the PM981 route. You get it working and next thing you know it kernel panics at boot. Wasted a month trying every possible workaround... which always seems to work until it doesn't.
> 256/512/1024 GB SX6000 is $35/45/90 on Amazon. Will be well-spent money unless some hackintosh whizz can figure out what is wrong between that drive and OS X.

thank you sir. i just bought a new SSD now all things work flawlessly. 

i also recommend people who are still struggling to make macos work on your shitty PM981, just buy a new NVMe SSD!

**Comment by xcheez1** [comment]
Where do I get ssdt-nvme and the kext?
