### ISSUE TITLE
plugin-type=1 doubt

### ISSUE THREAD

**Issue by zacharysalvatore** [tylernguyen/x1c6-hackintosh#45]
according to [Getting-Started-With-ACPI](https://khronokernel.github.io/Getting-Started-With-ACPI/Universal/plug.html) we need to replace the default `CUP0` to our `PR00` in [SSDT-PLUG](https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/AcpiSamples/SSDT-PLUG.dsl).
Our X1C6's DSDT shows that we need to replace `CUP0` to `_PR_.PR00`,  `\_PR.PR00` accordingly.
However your `SSDT-PLUG-_PR.PR00.aml` is different. I don't know which one is correct.
Weirdly, both amls will result plugin-type=1. 
Here's yours:
![Here's yours](https://user-images.githubusercontent.com/14255685/78679399-bd49d880-791c-11ea-8d6c-0f6ac31d8512.png)
Here's how it i thought it should be:
![Here's how it i thought it should be](https://user-images.githubusercontent.com/14255685/78679497-dd799780-791c-11ea-99bc-be8a292d0bdf.png)
![IORegistryExplorer 2020-04-07 at 22 01 59@2x](https://user-images.githubusercontent.com/14255685/78679515-e66a6900-791c-11ea-8bc7-850a9ad8c209.png)

**Comment by tylernguyen** [comment]
> Weirdly, both amls will result plugin-type=1.

**Both are correct patches. And both will set plugin-type=1.** 

As for their difference, you can refer back to [Getting Started with ACPI](https://khronokernel.github.io/Getting-Started-With-ACPI/ssdt-easy.html). My hotpatch is modified from the same source as SSDTTime, while the manual method is modifying its hotpatch from the sample of [OpenCorePkg](https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/AcpiSamples/SSDT-PLUG.dsl).

Again, they both work and there's nothing wrong or bad with either. 

**Feel free to use whichever one you like more.**

**Comment by tylernguyen** [comment]
Furthermore, the reason why my patch includes the DTGP method is to check UUID. Your hotpatch will work without the DTGP method. However, real Macs uses the DTGP method. And I think that's it better for our hotpatch to mimic real Mac DSDT.

**Comment by zacharysalvatore** [comment]
Thank you for your kind explanation.

**Comment by zacharysalvatore** [comment]
> Furthermore, the reason why my patch includes the DTGP method is to check UUID. Your hotpatch will work without the DTGP method. However, real Macs uses the DTGP method. And I think that's it better for our hotpatch to mimic real Mac DSDT to prevent possible problems down the line.

By the way, what’s this UUID? Do I need replace this with my systemuuid?

**Comment by tylernguyen** [comment]
@zacharysalvatore You do not need to modify it. That UUID comes from a real Mac, see various DTGP methods in
[MacBook.Pro-14.1.acpi.zip](https://github.com/tylernguyen/x1c6-hackintosh/files/4447862/MacBook.Pro-14.1.acpi.zip)
