### ISSUE TITLE
Hello, can you share the Bluetooth driver file of DW1560

### ISSUE THREAD

**Issue by johnzhaoican** [tylernguyen/x1c6-hackintosh#48]
Hello, can you share the Bluetooth driver file of DW1560?
E.g:
BrcmBluetoothInjector. Kext / BrcmFirmwareData.kext / BrcmPatchRAM3.kext / AirportBrcmFixup.kext / AirportBrcmFixup.kext
Thank you very much

**Comment by anhtutran37** [comment]
You can use Hackintool to download them

**Comment by tylernguyen** [comment]
@johnzhaoican 

These are their official repos:

https://github.com/acidanthera/BrcmPatchRAM
https://github.com/acidanthera/AirportBrcmFixup
https://github.com/acidanthera/BT4LEContinuityFixup

**Comment by johnzhaoican** [comment]
thanks guys
