### ISSUE TITLE
Carbon6 i5 tutorial

### ISSUE THREAD

**Issue by JackokieZhao** [tylernguyen/x1c6-hackintosh#51]
Could you please show me the right way to install the macos on a i5 computer with a wireless card DW1820A?
At first, I build a install media with the following method:
**[https://github.com/notthebee/macos_usb](url)**
Then, I put the Open-core EFI or Install-USB EFI in your github to the CLOVER partion.
However, it can't load the install process. 
So, I think that it might be the reasson for configure list, but I don't know how to reconfigure my config.plist.
Could you please help me? 
Thanks a lot.

**Comment by AutinMitra** [comment]
OpenCore should be at (USB) /EFI/OC

Also, if your SSD model is the PM981 (I believe the standard SSD for the machine), the installer will crash on your machine. 

I don't believe there is any difference for the configs between i5 and i7, other than regenerating CPUFriend for your i5.

**Comment by tylernguyen** [comment]
@JackokieZhao Just as @AutinMitra said, there should be no functional differences from the i5 and i7 model other than regenerating your own CPUFriendDataProvider.

Other than that, my project is fairly well documented so please take your time and read through these documentations:
https://github.com/tylernguyen/x1c6-hackintosh/tree/master/docs

Additionally, the DW1820A will need https://github.com/tylernguyen/x1c6-hackintosh/blob/master/patches/OpenCore%20Patches/Config-DW1820A.plist added to the current OpenCore EFI.
Be sure to also add the required kexts listed in the patch.

Regarding OpenCore configurations, please firstly familiarize yourself with general hackintosh installations and configuration procedures, here are some resources to do so:
https://dortania.github.io/vanilla-laptop-guide/
https://dortania.github.io/oc-laptop-guide/

I am more than willing to answer specific questions, but the rest is up to you.

**Comment by JackokieZhao** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Thanks for your answer.I have installed the Mac system on my carbon.However, there remains two problem I can’t resolve.The graphic card can’t work. The bottom of the screen is always black. I don’t know whether it’s the reason of 4K. And all the browser(Firefox, safari, chrome) is so slow….The other problem is the audio can’t work. I have add the layout_id 21 or 11 to the configure list. But it still can’t work.Thanks again for your help!
    
    
          
        
            
    
        font{
            line-height: 1.6;
        }
    
Best regards,Jackokie（Jiwei） Zhao-------------------------------------------------------------------------------------------Mobile: +86-13853203210Email: jackokie@qq.comURL: http://www.jackokie.comAddress: School of electronic science and engineering, Nanjing University，Xianlin Avenue Nanjing No. 163 Electronic Building (Panzhong to floor) 210093

        
    
     
    

    On 05/12/2020 11:37，Tyler Nguyen<notifications@github.com> wrote： 



@JackokieZhao Just as @AutinMitra said, there should be no functional differences from the i5 and i7 model other than regenerating your own CPUFriendDataProvider.
Other than that, my project is fairly well documented so please take your time and read through these documentations:
https://github.com/tylernguyen/x1c6-hackintosh/tree/master/docs
Additionally, the DW1820A will need https://github.com/tylernguyen/x1c6-hackintosh/blob/master/patches/OpenCore%20Patches/Config-DW1820A.plist added to the current OpenCore EFI.
Be sure to also add the required kexts listed in the patch.
Regarding OpenCore configurations, please firstly familiarize yourself with general hackintosh installations and configuration procedures, here are some resources to do so:
https://dortania.github.io/vanilla-laptop-guide/
https://dortania.github.io/oc-laptop-guide/
I am more than willing to answer specific questions, but the rest is up to you.

**Comment by tylernguyen** [comment]
>  Thanks for your answer.I have installed the Mac system on my carbon.However, there remains two problem I can’t resolve.The graphic card can’t work. The bottom of the screen is always black. I don’t know whether it’s the reason of 4K. And all the browser(Firefox, safari, chrome) is so slow….The other problem is the audio can’t work. I have add the layout_id 21 or 11 to the configure list. But it still can’t work.Thanks again for your help!

You need to check the specs of the graphics card and your audio layout. It maybe that your processor uses a different graphics chip than the UHD 620 my EFI folder is intended for. Similarly, my EFI is configured for ALC285 sound, you need to check if this is different from yours. Lastly, please make sure that your config.plist is configured properly, if you're using OpenCore, you can do so here:

https://opencore.slowgeek.com/
