### ISSUE TITLE
Before I start

### ISSUE THREAD

**Issue by chadharnav** [tylernguyen/x1c6-hackintosh#53]
Will this also work with the i7-8550U?

**Comment by AutinMitra** [comment]
Yup, worked perfectly fine for me

**Comment by chadharnav** [comment]
Does this guide contain the plist that is plug and play?

**Comment by AutinMitra** [comment]
Whatever config.plists here should work for your X1C6 , just follow the instructions in the README.MD

**Comment by chadharnav** [comment]
Got it
Just to make sure since I'm using the second slot next to the wifi card, I'm going to remove the windows ssd and tell you how it goes.

**Comment by tylernguyen** [comment]
**You should never use configs/patches you don't understand. Please review my docs carefully.**

Off the top of my head, you will need to generate your own CPUFriendDataProvider. However, there may be other differences I'm forgetting so, again, please review my documentation carefully.
