### ISSUE TITLE
Dual boot Win 10 and MacOS

### ISSUE THREAD

**Issue by ChipXinhDep** [tylernguyen/x1c6-hackintosh#57]
Dear Tyler, 
My X1C6 only have PM981 with 256Gb, so I think about getting 2nd drive in WAN slot. 
In that 2nd drive, I have to install MacOS right ? Because I read on some sites ppl said that they can't boot up Win 10 from 2nd drive in WAN slot.

**Comment by tylernguyen** [comment]
@ChipXinhDep 
You can definitely boot Win 10 from the drive in the WWAN slot, I have done it before just fine. You'll just need to select that drive when installing Win 10 and the `Windows Boot Manager` entry created will boot the WWAN drive.

Though if you are sticking with the PM981. I suggest you install macOS onto the WWAN drive instead and use the PM981 for Windows 10. As the PM981 has been know to be problematic in macOS, see https://github.com/tylernguyen/x1c6-hackintosh/issues/43

**Comment by parndt** [comment]
You can also dual boot macOS and Windows on the same SSD 😄 I got it working by giving the disk a GUID partition scheme and installing macOS to the first half of the SSD until it gets to the "set up macOS" phase, and then installing Windows in the free space on the second half, but with a 256GB SSD this doesn't give you much space for either. I did this with a 500GB SSD.

This dual booting isn't an easy installation, and I wouldn't recommend it if you can get a second SSD, and get it working happily.

**Comment by tylernguyen** [comment]
> You can also dual boot macOS and Windows on the same SSD 😄 I got it working by giving the disk a GUID partition scheme and installing macOS to the first half of the SSD until it gets to the "set up macOS" phase, and then installing Windows in the free space on the second half, but with a 256GB SSD this doesn't give you much space for either. I did this with a 500GB SSD.
> 
> This dual booting isn't an easy installation, and I wouldn't recommend it if you can get a second SSD, and get it working happily.

@parndt Just to clarify:
1. Start the macOS installation.
2. Start and finish Windows installation.
3. And then boot back into macOS and finish macOS installation?

**Comment by parndt** [comment]
@tylernguyen yep that's the process that should work; macOS wants to own the partitioning etc. 

What also worked for me was installing macOS onto half of the disk and then manually copying all of the Windows partitions from a working installation to the second half of the disk using `dd` in Linux. This can lead Windows to think it's broken every time it boots, which I never took the time to figure out, just mentioning it as a fallback if the steps you outlined don't work.

**Comment by Porco-Rosso** [comment]
I am currently dual-booting on a 1TB WD drive. If I recall correctly, what I did was:
1) install windows, shrink the partition.
2) Install OSX
3) Boot into a winPE style tool. I think I used [this(?)](https://www.easeus.com/partition-manager-software/free-mbr-repair-tool.html) to fix the windows boot record. 
4) Install rEFInd to handle dualbooting.

**Comment by parndt** [comment]
> Boot into a winPE style tool. I think I used [this(?)](https://www.easeus.com/partition-manager-software/free-mbr-repair-tool.html) to fix the windows boot record.

This is good info, thank you.

> Install rEFInd to handle dualbooting.

Currently I use my BIOS picker (as in F8 while booting) to choose which partition to boot from, as both partitions luckily show up as options.

**Comment by elnfnoosm** [comment]
> > Boot into a winPE style tool. I think I used [this(?)](https://www.easeus.com/partition-manager-software/free-mbr-repair-tool.html) to fix the windows boot record.
> 
> This is good info, thank you.
> 
> > Install rEFInd to handle dualbooting.
> 
> Currently I use my BIOS picker (as in function key while booting) to choose which partition to boot from, as both partitions luckily show up as options.

I also use BIOS picker, but have a problem---every time I press F12 or Enter when start, it will sound a alert beep(du---) aloud. How to close the beep?

**Comment by parndt** [comment]
> I also use BIOS picker, but have a problem---every time I press F12 or Enter when start, it will sound a alert beep(du---) aloud. How to close the beep?

does it do this when the mute (f1) is enabled?

**Comment by elnfnoosm** [comment]
> > I also use BIOS picker, but have a problem---every time I press F12 or Enter when start, it will sound a alert beep(du---) aloud. How to close the beep?
> 
> does it do this when the mute (f1) is enabled?

I guess you mean F1(mute),but this key only take effect after entering the system.
the alert beep occur at start when you press Enter key to enter BIOS, or press F12 to enter boot picker.

**Comment by elnfnoosm** [comment]
> > > I also use BIOS picker, but have a problem---every time I press F12 or Enter when start, it will sound a alert beep(du---) aloud. How to close the beep?
> > 
> > 
> > does it do this when the mute (f1) is enabled?
> 
> I guess you mean F1(mute),but this key only take effect after entering the system.
> the alert beep occur at start when you press Enter key to enter BIOS, or press F12 to enter boot picker.

update:
It's working!!!
you really help me solve a big confusion!
I press fn+f1 quickly after press power botton and the Lenovo just shows, and then the alert beep disappear!

**Comment by parndt** [comment]
>  I press fn+f1 quickly after press power botton and the Lenovo just shows, and then the alert beep disappear!

@elnfnoosm yep - that's what I meant - glad it helped you come up with a solution; the alert beep really irritates me too! Same with when booting a macbook, I try to make sure it's on mute so that loud chime doesn't sound. I'd say it's easier on the x1c6!

**Comment by ChipXinhDep** [comment]
> @ChipXinhDep
> You can definitely boot Win 10 from the drive in the WWAN slot, I have done it before just fine. You'll just need to select that drive when installing Win 10 and the `Windows Boot Manager` entry created will boot the WWAN drive.
> 
> Though if you are sticking with the PM981. I suggest you install macOS onto the WWAN drive instead and use the PM981 for Windows 10. As the PM981 has been know to be problematic in macOS, see #43

I used Lexar NM520 in WWAN slot, but it doesn't show up in Boot menu when I press F12. I installed Catalina 10.15.5 successfully, but still have to boot it up by USB because only USB and my P981 ssd show up in Boot menu. How to fix that ?

**Comment by tylernguyen** [comment]
@ChipXinhDep  A boot entry called `Mac OS X` should be created during macOS installation. If not, on the EFI of your drive, you can edit OpenCore to include Bootstrap protocols to force an `OpenCore` entry in the BIOS. See https://dortania.github.io/OpenCore-Desktop-Guide/post-install/multiboot/bootstrap.html

**Comment by guus202** [comment]
but what softwares do you need to download for win 11 dualboot

**Comment by Porco-Rosso** [comment]
https://www.rodsbooks.com/refind/
rEFInd has worked great for me in the past. It's like a pre-bootloader
