### ISSUE TITLE
Can‘t be installed on Hynix PC601 SSD

### ISSUE THREAD

**Issue by yantonglu** [tylernguyen/x1c6-hackintosh#59]
It seems to be a common problem of PC601. Kernel panic with info "IONVMeFamily(2.1)" will be caused when installing. Just like this https://www.reddit.com/r/hackintosh/comments/fb3zah/kernel_panic_during_installation_with_dell_xps_15/?utm_source=amp&utm_medium=&utm_content=post_body which model is XPS 15

**Comment by tylernguyen** [comment]
@yantonglu 

Could you try formatting the drive to 4K under Ubuntu and using the installation steps here: https://github.com/tylernguyen/x1c6-hackintosh/issues/43

**Comment by yantonglu** [comment]
Thank you. However, it seems that the unlucky XPS 15 user has tried 4k formatting under Ubuntu but still stuck before the installation  launch...
I have checked more information and come to PC601 SSD is incompatible with highly probability...
Thank you for reply.

**Comment by tylernguyen** [comment]
Is it possible for you to try the installation steps in that issue? It's a sort of a solution for the PM981 that I also thought to be incompatible. It would be great if you could confirm whether those steps work for the PC601 or not.

**Comment by yantonglu** [comment]
OK, I'll try it after I purchase another compatible SSD (SSD on my desktop is a pm981a, sigh....).
I question the solution, because I know the statement "pm981 is incompatible" is to say that something will go wrong at the GUI installation step, you at least launch the GUI installer (My bro has a 970 evo plus, and I tried to install and I success)... But the statement "PC601 is incompatible" means it will stuck before you see the GUI installer... I'm afraid that the same panic will happen after transfering installed macOS to PC601(before hacOS launch, it will run a piece of code if you add "-v")
Sorry for my messy wording... I need to improve my English...
Thank you

**Comment by zacharysalvatore** [comment]
@yantonglu you don’t need another compatible ssd to do it. You could install macOS on to an external USB stick under win10 using VMWare and mount it as a physical device.

**Comment by yantonglu** [comment]
OK, I'll try.

**Comment by tylernguyen** [comment]
> 
> 
> OK, I'll try it after I purchase another compatible SSD (SSD on my desktop is a pm981a, sigh....).
> I question the solution, because I know the statement "pm981 is incompatible" is to say that something will go wrong at the GUI installation step, you at least launch the GUI installer (My bro has a 970 evo plus, and I tried to install and I success)... But the statement "PC601 is incompatible" means it will stuck before you see the GUI installer... I'm afraid that the same panic will happen after transfering installed macOS to PC601(before hacOS launch, it will run a piece of code if you add "-v")
> Sorry for my messy wording... I need to improve my English...
> Thank you

I do not see why launching the installer GUI has anything to do with the drive. Internal drives should be untouched until they are selected to be installed on. If the installer GUI fails to launch, I'm more inclined to believe that it's the USB's fault, most likely the EFI.

**Comment by tylernguyen** [comment]
@yantonglu 
Additional, a sanity check for this would be to create an ACPI to disable the drive. If the installer GUI launches with the ACPI patch but fails to load without it. Then we could confirm that it is indeed the drive's fault that the installer GUI is not launching.

The patch would look something similar to ones used to disable NVIDIA dGPU. Though it would be the ACPI path of your Hynix PC601.

**Comment by yantonglu** [comment]
@zacharysalvatore 
Do you mean install hackintosh with VMware first, then mount a Windows partition and restore to it with Time Machine?
I haven't done this before, so I don't know details.

**Comment by yantonglu** [comment]
I made some progress.
I install macOS to a partition of my pc601（I made a 300M EFI partition in front of it）with Vmware，and it boot normally，so I put the EFI into the EFI partition and use Bootice add a boot entry.
Everything goes well until I reboot and try to boot the new boot entry. However，it displays “System has no boot entries...”
Help me，my friends，I think victory is in sight.
![image](https://user-images.githubusercontent.com/40975369/85942234-aaaed080-b95a-11ea-8e34-dc90a87ab063.jpeg)

**Comment by tylernguyen** [comment]
@yantonglu 
Please post your EFI.
Additionally, it looks like your EFI is not setup for `OpenCanopy`. Please change PickerMode to `Builtin`
Also, please adjust your ScanPolicy so boot entries show up.

**Comment by yantonglu** [comment]
@tylernguyen 
Actually I use your latest EFI (EFI-OpenCore/EFI).
I can't understand what I need to do... I know little about PickerMode or ScanPolicy...

**Comment by yantonglu** [comment]
@tylernguyen 
I will describe in more detail: I successfully added the boot entry with Bootice, and after reboot I choose it and presses Enter, but it reports the above error.

**Comment by tylernguyen** [comment]
The variables you need to configure are in ‘config.plist’

**Comment by yantonglu** [comment]
I change ScanPolicy to 0 then see the boot entry.
Apple logo displayed but when the progress bar reaches halfway it reboot, same for recovery mode.
I wonder why this time a bunch of code is not displayed... There must be a option in OpenCore, like "-v" in Clover.
Sorry to ask such a low question, but I am a rookie.

**Comment by yantonglu** [comment]
Unluckily，I boot with “-v” and see the same error.
![image](https://user-images.githubusercontent.com/40975369/85945164-72b18880-b96e-11ea-9740-191e68a4ec20.png)
Does this mean that everything I do is in vain？sigh...

**Comment by tylernguyen** [comment]
@yantonglu 
Per the PM981 installation method, you are not supposed to install directly onto the disk. You are supposed to restore a the backup image of an already installed onto your Hynix drive. Also, do you have "ssdt-nvme.aml" and "HackrNVMeFamily-10_12_6_sec2018-001.kext" when trying to boot that drive? Please read the PM981 issue thoroughly.

**Comment by yantonglu** [comment]
You mean there is deference between a backup fully installed macOS and my “a installed macOS + a EFI partition in front of it”？You should know I have successfully installed the macOS onto the partition by VMware，it has been installed fully and can be launched normally in VMware...
So I must use paragon to backup a fully installed macOS？I don’t know how to make it without a compatible ssd...
Thank you very much.

**Comment by yantonglu** [comment]
I added "ssdt-nvme.aml" and "HackrNVMeFamily-10_12_6_sec2018-001.kext", but it still reports the same error...

**Comment by tylernguyen** [comment]
> 
> 
> You mean there is deference between a backup fully installed macOS and my “a installed macOS + a EFI partition in front of it”？You should know I have successfully installed the macOS onto the partition by VMware，it has been installed fully and can be launched normally in VMware...
> So I must use paragon to backup a fully installed macOS？I don’t know how to make it without a compatible ssd...
> Thank you very much.

I'm not sure what you mean. Per issue #43 @zacharysalvatore used Paragon to backup and then restore that image onto the drive. What steps did you do differently?

**Comment by yantonglu** [comment]
@tylernguyen 
Can I make it without a external ssd? (only with Vmware)

**Comment by tylernguyen** [comment]
> 
> 
> @tylernguyen
> Can I make it without a external ssd? (only with Vmware)

It seems that one person got it working via the VMware method. See https://github.com/tylernguyen/x1c6-hackintosh/issues/43#issuecomment-650735658

However, using VMware seems like it would just add more layers to the problem, and we want to isolate problems to just the drive in question. So I think it's better for you to use @zacharysalvatore orignial method.

**Comment by yantonglu** [comment]
I made some progress.
Now the panic turns to "AppleIntelKBLGraphicFrameBuffer", sounds related to gpu.

**Comment by tylernguyen** [comment]
> I made some progress.
> 
> Now the panic turns to "AppleIntelKBLGraphicFrameBuffer", sounds related to gpu.

Which EFI are you using? Install or Main?

**Comment by yantonglu** [comment]
Main, but for a new installation, because if I use main to launch the macOS backup from paragon, its progress bar reach half then display a prohibition flag.
Should I change to Install EFI?

**Comment by yantonglu** [comment]
At last，I entry the GUI installer...
But there is no my ssd in the disk utility...
I think I will use this EFI to try backup method.
Thank you for help.

**Comment by yantonglu** [comment]
Now：
Install EFI or Main EFI + backup macOS = prohibition flag.
Install EFI + installation image = GUI installer but can’t  detect ssd.
If I add nvmegeneric.kext，GUI installer cannot be launched.

**Comment by tylernguyen** [comment]
@yantonglu 

Sorry. I'm quite confused. Why do you need to launch the installer? macOS should already be installed. You just need to restore it onto the PC601.

**Comment by yantonglu** [comment]
When I try to launch the restored macOS，it display a prohibition flag.

**Comment by tylernguyen** [comment]
> When I try to launch the restored macOS，it display a prohibition flag.

Ok, if it's the install EFI, it should be in verbose mode. Can you show the logs?

**Comment by tylernguyen** [comment]
Also, with the EFI:
Install OpenCore debug: https://github.com/acidanthera/OpenCorePkg/releases
Change debug target the 67
After each boot, an OC log should appear in the EFI parition now. Please also upload that.

**Comment by yantonglu** [comment]
panic(cpu 0 caller 0xffffff7f8a25b201): nvme: "Fatal error occurred. CSTS=0x1 US[1]=0x0 US[0]=0x0 VID=0x1c5c DID=0x1627
. FW Revision not available\n"com.apple./AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/IONVMeFamily/IONVMeFamily-470.100.17/IONVMeController.cpp:5326
Backtrace (CPU 0), Frame : Return Address
0xffffff920256b9f0 : 0xffffff800791f5cd mach_kernel : _handle_debugger_trap + 0x49d
0xffffff920256ba40 : 0xffffff8007a58b05 mach_kernel : _kdp_i386_trap + 0x155
0xffffff920256ba80 : 0xffffff8007a4a68e mach_kernel : _kernel_trap + 0x4ee
0xffffff920256bad0 : 0xffffff80078c5a40 mach_kernel : _return_from_trap + 0xe0
0xffffff920256baf0 : 0xffffff800791ec97 mach_kernel : _DebuggerTrapWithState + 0x17
0xffffff920256bbf0 : 0xffffff800791f087 mach_kernel : _panic_trap_to_debugger + 0x227
0xffffff920256bc40 : 0xffffff80080c27cc mach_kernel : _panic + 0x54
0xffffff920256bcb0 : 0xffffff7f8a25b201 com.apple.iokit.IONVMeFamily : __ZN16IONVMeController13FatalHandlingEv.cold.2
0xffffff920256bcc0 : 0xffffff7f8a246353 com.apple.iokit.IONVMeFamily : __ZN16IONVMeController13FatalHandlingEv + 0x183
0xffffff920256be20 : 0xffffff80080333e9 mach_kernel : __ZN18IOTimerEventSource15timeoutSignaledEPvS0_ + 0x89
0xffffff920256be90 : 0xffffff8008033309 mach_kernel : __ZN18IOTimerEventSource17timeoutAndReleaseEPvS0_ + 0x99
0xffffff920256bec0 : 0xffffff8007961565 mach_kernel : _thread_call_delayed_timer + 0xec5
0xffffff920256bf40 : 0xffffff8007961091 mach_kernel : _thread_call_delayed_timer + 0x9f1
0xffffff920256bfa0 : 0xffffff80078c513e mach_kernel : _call_continuation + 0x2e
      Kernel Extensions in backtrace:
         com.apple.iokit.IONVMeFamily(2.1)[1898DCFE-5C18-3D87-B9E7-DFC0D22FD7EE]com.apple.0xffffff7f8a238000-com.apple.driver.0xffffff7f8a27afff
            dependency: com.apple.driver.AppleMobileFileIntegrity(1.0.5)[E35D090D-DB9E-3DD0-9723-651FA730AA13]com.apple.0xffffff7f88a2e000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[BE052F4D-9B80-3FCD-B36D-BACB7DEE0DF2]com.apple.0xffffff7f88312000
            dependency: com.apple.driver.AppleEFINVRAM(2.1)[4E64E519-CD9C-3D03-8E62-1074E9AD54A7]com.apple.0xffffff7f8a1d6000
            dependency: com.apple.iokit.IOStorageFamily(2.1)[E13E9C61-F1F5-3A81-B1EF-65669C3CBDBF]com.apple.0xffffff7f88680000
            dependency: com.apple.iokit.IOReportFamily(47)[1FB49168-0280-3F04-A99A-F830C915E994]com.apple.0xffffff7f88249000

BSD process name corresponding to current thread: kernel_task
Boot args: npci=0x2000 dart=0 -no_compat_check -v brcmfx-driver=0 keepsyms=1 -hbfx-dump-nvram root-dmg=file:///Install%20macOS%20Catalina.app/Contents/SharedSupport/BaseSystem.dmg

Mac OS version:
19F101

Kernel version:
Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64
Kernel UUID: 54F1A78D-6F41-32BD-BFED-4381F9F6E2EF
Kernel slide:     0x0000000007600000
Kernel text base: 0xffffff8007800000
__HIB  text base: 0xffffff8007700000
System model name: MacBookPro14,1 (Mac-B4831CEBD52A0C4C)
System shutdown begun: NO
Panic diags file unavailable, panic occurred prior to initialization

System uptime in nanoseconds: 41308615606
last loaded kext at 6776732371: com.apple.driver.DiskImages.ReadWriteDiskImage	493.0.0 (addr 0xffffff7f8b2f3000, size 12288)
loaded kexts:

Looks like origin error...

**Comment by tylernguyen** [comment]
@yantonglu 

`dmg=file:///Install%20macOS%20Catalina.app/Contents/SharedSupport/BaseSystem.dmg`
You're booting the installer?

**Comment by yantonglu** [comment]
Ah，I think it is a installed macOS！I download it from a tutorial，so you mean actually it is a installer？
So I should change to a origin image？If so，can you provide me one？I have no Mac. Thank you.

**Comment by tylernguyen** [comment]
@yantonglu 
I do not have one. You need to create on yourself, per @zacharysalvatore 's post. Here are the steps again to be clear:
1. Install and setup macOS on another drive. Per the PM981 post, you can do this via VMware, please refer to that issue.
2. Backup and restore that drive onto your PC601
3. Add "ssdt-nvme.aml" and "HackrNVMeFamily-10_12_6_sec2018-001.kext" to your EFI (make sure to edit the aml with your proper nvme controller's ID) and boot the PC601 (which at this point, should already be restored to the installed macOS).

**Comment by yantonglu** [comment]
I know the steps.I have found some source.
Thank you very much.

**Comment by yantonglu** [comment]
I restored a true backup macOS and switched to hard disk boot.
Prohibition flag still.
And report dumped turns strange.

00:000 00:000 AAPL: [EB|#LOG:INIT] 2020-06-29T15:12:23
00:003 00:003 AAPL: [EB|#VERSION] boot.efi 422.120.8~3 (Official), built 2020-04-25T13:24:01-0700
00:006 00:002 AAPL: [EB|#BUILD] BUILD-INFO[298]:{"DisplayName":"boot.efi","DisplayVersion":"422.120.8~3","RecordUuid":"7F620F75-9798-4821-B304-A6B586390C25","BuildTime":"2020-04-25T13:24:01-0700","ProjectName":"efiboot","ProductName":"boot.efi","SourceVersion":"422.120.8","BuildVersion":"3","BuildConfiguration":"Release","BuildType":"Official"}
00:009 00:002 AAPL: [EB|#H:IS] 0
00:012 00:003 AAPL: [EB|#WL:MODE] 0
00:014 00:002 AAPL: [EB|#CONFIG:SRC] <default>
00:017 00:002 AAPL: [EB|#CONFIG| 0] boot-save-log : 0x0000000000000002 (0x0000000000000002 < 0xFFFFFFFFFFFFFFFF) <default>
00:020 00:003 AAPL: [EB|#CONFIG| 1] wake-save-log : 0x0000000000000002 (0x0000000000000002 < 0x0000000000000002) <default>
00:023 00:002 AAPL: [EB|#CONFIG| 2] console       : 0x0000000000000001 (0x0000000000000001 < 0x0000000000000001) <default>
00:026 00:002 AAPL: [EB|#CONFIG| 3] serial        : 0x0000000000000000 (0x0000000000000000 < 0x0000000000000000) <default>
00:029 00:002 AAPL: [EB|#CONFIG| 4] embed-log-dt  : 0x0000000000000000 (0x0000000000000000 < 0x0000000000000000) <default>
00:032 00:002 AAPL: [EB|#CONFIG| 5] timestamps    : 0x0000000000000000 (0x0000000000000000 < 0xFFFFFFFFFFFFFFFF) <default>
00:035 00:002 AAPL: [EB|#CONFIG| 6] log-level     : 0x0000000000000001 (0x0000000000000001 & 0x0000000000000001) <default>
00:038 00:002 AAPL: [EB|#CONFIG| 7] breakpoint    : 0x0000000000000000 (0x0000000000000000 & 0x0000000000000000) <default>
00:041 00:003 AAPL: [EB|#CONFIG| 8] kc-read-size  : 0x0000000000100000 (0x0000000000100000 < 0xFFFFFFFFFFFFFFFF) <default>
00:044 00:002 AAPL: [EB|#H:IS] 0
00:047 00:003 AAPL: [EB|#WL|0] 0x01 0x01   0 0x00
00:051 00:003 AAPL: [EB|#BRD:NV] Mac-B4831CEBD52A0C4C
00:054 00:002 AAPL: [EB|#WL|1] 0x01 0x01   2 0x00
00:057 00:003 AAPL: [EB|#B:RRVAR] 000000000000
00:061 00:003 AAPL: [EB|#B:MLBVAR] 
00:064 00:002 AAPL: [EB|`BST:IDT] {
00:077 00:013 AAPL: [EB|`BST:IDT] }
00:080 00:002 AAPL: [EB|#WL|2] 0x01 0x01   3 0x00
00:083 00:002 AAPL: [EB|#WL|3] 0x01 0x01   4 0x00
00:087 00:003 AAPL: [EB|#BRD:NV] Mac-B4831CEBD52A0C4C
00:090 00:002 AAPL: [EB|#WL|4] 0x01 0x01   5 0x00
00:093 00:003 AAPL: [EB|`H:CHK] BM: 0x0000000000000000
00:096 00:003 AAPL: [EB|`H:CHK] Err(0xE) @ GV boot-signature
00:099 00:003 AAPL: [EB|#WL|5] 0x01 0x01  23 0x0E
00:103 00:003 AAPL: [EB|`H:CPM] Err(0xE), (24, 24) @ GV Persistent-memory-note
00:108 00:004 AAPL: [EB|`SB:EN] Err(0xE) @ LocP 24B73556-2197-4702-82A8-3E1337DAFBF2
00:111 00:003 AAPL: [EB|#LIMG:DP] Acpi(PNP0A03,0)/Pci(1C|4)/Pci(0|0)/?[ 0x83 0x17 0x10 0x0 0x1 0x0 0x0 0x0 0xAC 0xE4 0x2E 0x81 0x70 0x53 0x43 0xA5 ]/HD(Part4,SigEF943D41-EDE8-4038-3FAD-DE99C1F4C640)/VenMedia(BE74FCF7-0B7C-49F3-9147-01F4042E6842)
00:115 00:003 AAPL: [EB|#LIMG:FP] \1DECE3B7-08E8-4229-9D91-7E99E9795266\System\Library\CoreServices\boot.efi
00:118 00:002 AAPL: [EB|#LIMG:OPT] (-v\0\0\u7470\u6C61)
00:123 00:004 AAPL: [EB|`OPT:LXF] 'LF (\\1DECE3B7-08E8-4229-9D91-7E99E9795266\\System\\Library\\CoreServices\\com.apple.Boot.plist)
00:125 00:002 AAPL: [EB|`LD:LF] FIO: 0, DIR: 1, P: \\1DECE3B7-08E8-4229-9D91-7E99E9795266\\System\\Library\\CoreServices\\com.apple.Boot.plist, DP: 0
00:129 00:003 AAPL: [EB|`LD:OFS] Err(0xE) @ OPEN (\\1DECE3B7-08E8-4229-9D91-7E99E9795266\\System\\Library\\CoreServices\\com.apple.Boot.plist)
00:131 00:002 AAPL: [EB|`OPT:LXF] Err(0xE) @ 'LF
00:134 00:002 AAPL: [EB|`OPT:LXF] 'LF (Library\\Preferences\\SystemConfiguration\\com.apple.Boot.plist)
00:137 00:002 AAPL: [EB|`LD:LF] FIO: 0, DIR: 1, P: Library\\Preferences\\SystemConfiguration\\com.apple.Boot.plist, DP: 0
00:141 00:003 AAPL: [EB:#KF] ()
00:144 00:002 AAPL: [EB|#MBA:CL] (-v)
00:147 00:002 AAPL: [EB|#MBA:NV] (keepsyms=1 -v)
00:150 00:002 AAPL: [EB|#MBA:KF] ()
00:153 00:002 AAPL: [EB|#MBA:OUT] (-v keepsyms=1)
00:156 00:003 AAPL: [EB|#LOG:VERBOSE] 2020-06-29T15:12:23
00:159 00:002 AAPL: [EB|#OPT:BM] 0x84102
00:161 00:002 AAPL: [EB|`OPT:LXF] 'LF (\\1DECE3B7-08E8-4229-9D91-7E99E9795266\\System\\Library\\CoreServices\\PlatformSupport.plist)
00:164 00:002 AAPL: [EB|`LD:LF] FIO: 0, DIR: 1, P: \\1DECE3B7-08E8-4229-9D91-7E99E9795266\\System\\Library\\CoreServices\\PlatformSupport.plist, DP: 0
00:168 00:003 AAPL: [EB|#B:VAw]
00:171 00:003 AAPL: [EB|`P:DCCPR] Err(0xE) @ GV AAPL,CoProcessorReboot
00:174 00:003 AAPL: [EB|#P:MPI] N
00:177 00:003 AAPL: [EB|`CS:CSKSD] {
00:181 00:003 AAPL: [EB|`CS:CSKSD] Err(0xE) @ GV 8D63D4FE-BD3C-4AAD-881D-86FD974BC1DF:boot-info-payload
00:184 00:002 AAPL: [EB|#WL|6] 0x01 0x01   6 0x0E
00:187 00:002 AAPL: [EB|`CS:LFC] {
00:190 00:002 AAPL: [EB|`LD:LF] FIO: 0, DIR: 1, P: System\\Library\\Caches\\com.apple.corestorage\\EncryptedRoot.plist.wipekey, DP: 0
00:196 00:006 AAPL: [EB|`FS:AGSVH] Err(0xE) @ LocHB 59D76AE4-37E3-55A7-B460-EF13D46E6020
00:199 00:003 AAPL: [EB|`G:CS] } Ok(0)
00:203 00:004 AAPL: [EB|`LD:LF] FIO: 0, DIR: 1, P: <null string>, DP: 1
00:208 00:004 AAPL: [EB|`B:SBS] SZ: 617016
00:219 00:011 AAPL: [EB|#B:SHA] 86334d2de1b82c43d7871bf0ac2cf748e2f786c0
00:223 00:004 AAPL: [EB|`WL:PWLFNV] Err(0xE) @ GV wake-failure
00:227 00:003 AAPL: [EB|`WL:DT] Err(0xE) @ WL:PWLFNV
00:231 00:003 AAPL: [EB|`WL:PWLFRTC] ! @ RTC:R
00:234 00:003 AAPL: [EB|`WL:DT] Err(0xE) @ WL:PWLFRTC
00:238 00:003 AAPL: [EB|`FS:AGSVH] Err(0xE) @ 'AGU.0
00:243 00:004 AAPL: [EB|`LD:LKC] BPDK -> (System\Library\PrelinkedKernels\prelinkedkernel.development)
00:250 00:006 AAPL: [EB|`LD:OFS] Err(0xE) @ OPEN (System\\Library\\PrelinkedKernels\\prelinkedkernel.development)
00:255 00:004 AAPL: [EB|`LD:LKC] BPDK,!R -> (System\Library\PrelinkedKernels\prelinkedkernel)
02:332 02:077 AAPL: [EB|`LD:LKFS] } Ok(0)
02:336 00:003 AAPL: [EB|`LD:LKC] } Ok(0)
02:340 00:004 AAPL: [EB|#FWFM] 0xFF1FFF3F
02:344 00:003 AAPL: [EB|#FWFT] 0xFD0FF536
02:348 00:003 AAPL: [EB|#CSR:IN] 0x00000040
02:351 00:003 AAPL: [EB|#CSR:OUT] 0x00000040
02:355 00:003 AAPL: [EB|`BST:FBS] {
02:359 00:004 AAPL: [EB|#GIP:PHS.1] Boot 1
02:363 00:004 AAPL: [EB|#GIP:PCT] 0x0
02:367 00:003 AAPL: [EB|#GIP:PHS.2] Boot 1
02:370 00:003 AAPL: [EB|`BST:FBS] BA.ADSZ: 0
02:374 00:003 AAPL: [EB|`BST:FBS] BA.KSDSZ: 0
02:379 00:004 AAPL: [EB|`B:WFDW] Err(0xE), 0 @ LocHB 71B4903C-14EC-42C4-BDC6-CE1449930E49
02:383 00:003 AAPL: [EB|#LOG:DT] 2020-06-29T15:12:25
02:387 00:004 AAPL: [EB|#LOG:EXITBS:START] 2020-06-29T15:12:25

**Comment by tylernguyen** [comment]
@yantonglu This is with the nvme kext and aml patch added? Also, remember that the aml needs to be modified to your nvme path.

**Comment by yantonglu** [comment]
Yes，I have finished everything.

**Comment by tylernguyen** [comment]
Those look like OpenCore logs. Could you show the verbose logs also?

**Comment by yantonglu** [comment]
@tylernguyen 
I found a very shocking fact: my x1c6 has no AHCI option in BIOS, and accroding to Windows device manager, there is not SATA AHCI Controller...
I heard that if the system is not running under AHCI model, the ssd will be invisible in disk utility...

**Comment by yantonglu** [comment]
I can't dump the report so I shot the panic:

![7EDE17F9C9BACB922AAB99446DCB90F6](https://user-images.githubusercontent.com/40975369/85996669-1e280f00-ba3b-11ea-8e53-f65fc0264398.png)

**Comment by tylernguyen** [comment]
@yantonglu 
Could you share a zip of the EFI you used to get that error?

**Comment by yantonglu** [comment]
I have changed my ssd to 970 eve plus and successfully install...
Thank you for your great help!

**Comment by yantonglu** [comment]
There is a small question: is it normal that the graphic memory is only 1536M?

**Comment by tylernguyen** [comment]
> There is a small question: is it normal that the graphic memory is only 1536M?

Yeah, it’s completely normal.

**Comment by way2ezee** [comment]
Hey @yantonglu, will you please help me if you have got this working? I have same SSD and completely lost in between of this long thread. Can you please sum up things for me, it will be a great help?

**Comment by yantonglu** [comment]
@way2ezee Actually I never solve the problem, and now I switched to a true MacBook Pro, so I lost not only the hackintosh device but also the skill, haha. Sorry for I can not help you.
