### ISSUE TITLE
HDMI fix does not work

### ISSUE THREAD

**Issue by lihjacky** [tylernguyen/x1c6-hackintosh#6]
Hello, In the very last steps, the HDMI audio fix is not working. Once I plug the HDMI cable, the laptop restart at once. I have tried your config.plist and also tried the config_patches.plist. Moreover, I also follow the guide in https://www.tonymacx86.com/threads/guide-intel-igpu-hdmi-dp-audio-all-sandy-bridge-kaby-lake-and-likely-later.189495/. And it still reboots every time.

Do you have any ideas to fix the HDMI audio and reboots in X1c6?

ps. I found the HDAU device in X1c 6gen is not B0D3 but B0D4

**Comment by tylernguyen** [comment]
You must override EDID to completely fix the HDMI issue. I'm currently testing out a few different DisplayOverride configurations and will update the repo with the appropriate files as soon as possible. Please bear with me.

**Comment by jeremylan** [comment]
Hi
I had the same problem and the best solution I could find was to install the HiDpi script:

https://github.com/xzhih/one-key-hidpi

and then patch the resulting EDID with the usual method using Darwin Dumper and FixEDID.
All details here:

https://www.tonymacx86.com/threads/hidpi-resolution.268187/#post-1885447

I get a really nice HiDpi resolution and full external monitor support via HDMI.
The only issue is on sleep, where the resolution gets lost on wake up.
Hope it helps.

**Comment by jeremylan** [comment]
Hi @tylernguyen 
No probs, thank you very much for publishing your guide, it was useful to me.
I attached my DisplayOverride folder, hope it helps.
Thanks

[DisplayVendorID-30e4.zip](https://github.com/tylernguyen/x1c6-hackintosh/files/2753544/DisplayVendorID-30e4.zip)

**Comment by swsjack** [comment]
Hi,
 Any update for exact method or step to follow to make HDMI output to work. My X1 carbon still reboot every time I connect HDMI cable. Please help..

**Comment by tylernguyen** [comment]
> Hi,
> Any update for exact method or step to follow to make HDMI output to work. My X1 carbon still reboot every time I connect HDMI cable. Please help..

@swsjack Please try again using my OpenCore configurations. The issue has been fixed on my machine.
