### ISSUE TITLE
Speaker seemed to be broken

### ISSUE THREAD

**Issue by yantonglu** [tylernguyen/x1c6-hackintosh#61]
When I just installed it yesterday, everything is normal, but today without changing the efi, the speaker cannot make sound normally under macOS. Whenever it should make a sound, it is replaced by a pop sound.  Under Windows, it can sound but is accompanied by popping sounds.  I reinstalled macOS but it didn‘t work.

**Comment by tylernguyen** [comment]
@yantonglu 
Per the **issue template**, please include logs if possible. In this case, logs of AppleALC and Lilu. Otherwise, please include a copy of your EFI.

In addition, have you installed the ALCPlugFix patch included in this repo?

**Comment by yantonglu** [comment]
It is back to normal itself today.
