### ISSUE TITLE
GPU

### ISSUE THREAD

**Issue by JackokieZhao** [tylernguyen/x1c6-hackintosh#64]
The computer runs slowly. I think that it might be the reason of igpu configuration.

Notice:
1. The cpu of my laptop is i5, which is different with that of you.
2. I have replaced my screen with another 4K one for the damage of water in.
 
Here is the system screenshot:

!
![image](https://user-images.githubusercontent.com/19789205/87615960-83bc1100-c746-11ea-9be8-1a94df336709.png)
[image](https://user-images.githubusercontent.com/19789205/87615913-60916180-c746-11ea-8446-b029d6a6860c.png)
![image](https://user-images.githubusercontent.com/19789205/87615935-7141d780-c746-11ea-865e-4552e0469044.png)
![image](https://user-images.githubusercontent.com/19789205/87615943-76068b80-c746-11ea-96c5-38de4e125bb8.png)
![image](https://user-images.githubusercontent.com/19789205/87615947-7acb3f80-c746-11ea-8dfe-b15c264eb642.png)

Wishing for your instruction. Thank you so much.
I would appreciate it  if you can help me to resolve the problem.

**Comment by tylernguyen** [comment]
@JackokieZhao 
What do you mean by "the computer runs slowly"?
Also, have you generated your own CPUFriendDataProvider for your cpu?

**Comment by JackokieZhao** [comment]
I just means that the graphical interface is always stuck, and the response to the mouse is so slow / lagging. On the other hand, the memory occupance is high(reached 70%) when i open two or three windows.

I have generated the CpuFriendDataProvider and replace corresponding files in kexts directory.

Otherwise, what I have changed is only related to the DW1820A.

**Comment by benbender** [comment]
Your Machine is propably not 6th Gen X1. 0x3EA9 Device-ID for your GPU is Coffee-Lake, not Kaby Lake. That's presumably why your gfx-config isn't working. Use macbookpro15,1/15,2 as plattform-id, a matching framebuffer-id and general config.

**Comment by tylernguyen** [comment]
@benbender ` i5-8250U` is Kaby Lake. And it's in accordance with [docs/references/x1c6-Platform_Specifications.pdf](https://github.com/tylernguyen/x1c6-hackintosh/blob/master/docs/references/x1c6-Platform_Specifications.pdf)

Though @benbender is right @JackokieZhao 

You are likely injecting the wrong platform ID as `0x3EA9` is Coffee-Lake, usually meant for `UHD 630` not `UHD 620`. Post your EFI.

**Comment by benbender** [comment]
Hmm, okay - thats really strange:

according to intel, the device-id for the 8250u should be 0x5917:
https://ark.intel.com/content/www/us/en/ark/products/124967/intel-core-i5-8250u-processor-6m-cache-up-to-3-40-ghz.html

according to the WEG-Docs, 3EA9 needs a coffee lake-Framebuffer:
https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md

I think my initial statement is correct, that, if the data shown above is correct, at least platform-id and framebuffer/framebuffer-id should be changed...

**Comment by JackokieZhao** [comment]
> @benbender ` i5-8250U` is Kaby Lake. And it's in accordance with [docs/references/x1c6-Platform_Specifications.pdf](https://github.com/tylernguyen/x1c6-hackintosh/blob/master/docs/references/x1c6-Platform_Specifications.pdf)
> 
> Though @benbender is right @JackokieZhao
> 
> You are likely injecting the wrong platform ID as `0x3EA9` is Coffee-Lake, usually meant for `UHD 630` not `UHD 620`. Post your EFI.

I think it might be the original reason.
I haven't change some parameters for the gpu parameters, but it still can't work(stop at the apple).
If I delete the AAPL device, I can login in the macos.
Is there any advance for me ?
In addition, I have set the cpu basic frequency as 1.5GHz. Is this the reason for fast power consuming?
The fan is always running and the keyboard is so hot, which might reach or overpass 50 degrees...

Here is my efi,
https://drive.google.com/file/d/1aWxjew7swFOq8QO1wm4tsRQs5DjquBqm/view?usp=sharing

This is your graphic configuration which I have removed in my efi for the sucessful login in the macos.
<key>PciRoot(0x0)/Pci(0x2,0x0)</key>
			<dict>
				<key>AAPL,ig-platform-id</key>
				<data>
				BAAnWQ==
				</data>
				<key>device-id</key>
				<data>
				FlkAAA==
				</data>
				<key>framebuffer-con1-enable</key>
				<data>
				AQAAAA==
				</data>
				<key>framebuffer-con1-type</key>
				<data>
				AAgAAA==
				</data>
				<key>framebuffer-patch-enable</key>
				<data>
				AQAAAA==
				</data>
			</dict>

**Comment by JackokieZhao** [comment]
> Hmm, okay - thats really strange:
> 
> according to intel, the device-id for the 8250u should be 0x5917 (like ours):
> https://ark.intel.com/content/www/us/en/ark/products/124967/intel-core-i5-8250u-processor-6m-cache-up-to-3-40-ghz.html
> 
> according to the WEG-Docs, 3EA9 needs a coffee lake-Framebuffer:
> https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md
> 
> I think my initial statement is correct, that, if the data shown above is correct, at least platform-id and framebuffer/framebuffer-id should be changed...

Is there any advice for the modification? I'm a rookie in this area. And my EFI has been post before. 
Thanks! 
Online waiting...

**Comment by benbender** [comment]
At least your platform-info is missing essentials. That may be the root of your problem. See here: https://dortania.github.io/vanilla-laptop-guide/OpenCore/config-laptop.plist/coffee-lake.html#platforminfo

**Comment by JackokieZhao** [comment]
> At least your platform-info is missing essentials. That may be the root of your problem. See here: https://dortania.github.io/vanilla-laptop-guide/OpenCore/config-laptop.plist/coffee-lake.html#platforminfo

Could I past the device-id and AAP values into the corresponding item in xcode? Or should I covert these values to other format?
![image](https://user-images.githubusercontent.com/19789205/87707452-b6f8b180-c7d3-11ea-87e3-34aae04da910.png)

**Comment by benbender** [comment]
Try to read and understand:
https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md

And:
https://www.tonymacx86.com/threads/guide-general-framebuffer-patching-guide-hdmi-black-screen-problem.269149/

But as the values are for concrete options, they are correct and can be pasted.

**Comment by tylernguyen** [comment]
@JackokieZhao Is that framebuffer `0x3EA9` native or is that being injected by you?

**Comment by tylernguyen** [comment]
Also @JackokieZhao try this `config.plist`
[config.plist.zip](https://github.com/tylernguyen/x1c6-hackintosh/files/4942190/config.plist.zip)

I disabled 4k output kernel patches and injected basic HD620 graphics properties

**Comment by JackokieZhao** [comment]
> @JackokieZhao Is that framebuffer `0x3EA9` native or is that being injected by you?

I'm sorry. I just copy your config.list contens for the framebuffer.

**Comment by JackokieZhao** [comment]
> Also @JackokieZhao try this `config.plist`
> [config.plist.zip](https://github.com/tylernguyen/x1c6-hackintosh/files/4942190/config.plist.zip)
> 
> I disabled 4k output kernel patches and injected basic HD620 graphics properties

It still can't work after replacing my config.list with that of your supply. At first, the computer will entering the login graphic, and the process bar will stop while approaching 70%. And then the screen will be lighter than before and it will make the mac sound when I tap the keyboard.
However, when I delete the gpu configure in your config.list, the computer will be able to enter the macos.

Maybe it be the reason of gpu injection, which disturb me for so long a time.

**Comment by benbender** [comment]
Did you fix your platforminfo? Before this is fixed and virtualsmc gets initialized properly, anything else will be pointless.

**Comment by JackokieZhao** [comment]
> Did you fix your platforminfo? Before this is fixed and virtualsmc gets initialized properly, anything else will be pointless.
> 
> Edit: To be clear: I'm talking about the platforminfo of your hackintosh, not the "ig-platform-id"-property of the GPU. Those are the informations needed by virtualsmc, the emulated system management controller, to know which mac-model it should emulate. See the link I pasted.

Did you means that I choose the wrong model to emulate? My cpu is i5-8250u(Coffee Lake), and gpu is uhd620. 
As you have mentioned, I changed the device-id to 165900000 according to [https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md](url)
In addation, it should be 9B3E0000 according to [https://dortania.github.io/vanilla-laptop-guide/OpenCore/config-laptop.plist/coffee-lake.html#platforminfo](url)
I have tried both of them. However, it still can't work. 
According to intel website [https://ark.intel.com/content/www/us/en/ark/products/124967/intel-core-i5-8250u-processor-6m-cache-up-to-3-40-ghz.html](url), the device-id is 0x5917. 
Maybe, I emulated the wrong mac as you said. 
I have tried about twenty or thirty times for generating platforminto with "GenSMBOIS.command", but none of them could fit for both the apple and appleserial... website requirements. 
Could you please tell me how to change the platforminfo?   Or told me how to solve the problem?

**Comment by JackokieZhao** [comment]
> Did you fix your platforminfo? Before this is fixed and virtualsmc gets initialized properly, anything else will be pointless.
> 
> Edit: To be clear: I'm talking about the platforminfo of your hackintosh, not the "ig-platform-id"-property of the GPU. Those are the informations needed by virtualsmc, the emulated system management controller, to know which mac-model it should emulate. See the link I pasted.
![image](https://user-images.githubusercontent.com/19789205/87876082-3078e580-ca08-11ea-9987-d2b5a854468b.png)
![image](https://user-images.githubusercontent.com/19789205/87876126-79309e80-ca08-11ea-85d3-7e5d7ce74a08.png)
So sorry that i'm a stupid rookie.

**Comment by benbender** [comment]
a) Please update Hackintool to the latest version: https://github.com/headkaze/Hackintool/releases/tag/3.4.2 because I can't interpret those values in the screenshots as I don't speak chinese(?). If you use the latest version I can look them up on my local version.

b) With fixed plattform-id try the following framebuffer-settings and report back:

````
				<key>AAPL,ig-platform-id</key>
				<data>
				CQAWWQ==
				</data>
				<key>device-id</key>
				<data>
				FlkAAA==
				</data>
				<key>framebuffer-fbmem</key>
				<data>
				AACQAA==
				</data>
				<key>framebuffer-patch-enable</key>
				<data>
				AQAAAA==
				</data>
				<key>framebuffer-stolenmem</key>
				<data>
				AAAwAQ==
				</data>
````

These values are fairly minimal for 0x5917. If it's successfull you should see "Intel HD Graphics 620 1536MB" or similar in "About this mac"

**Comment by JackokieZhao** [comment]
I'm so said it still be stucked in the apple figure...
[config.txt](https://github.com/tylernguyen/x1c6-hackintosh/files/4944018/config.txt)

This is my config.plist, which has been replaced with your gpu configure.
Maybe, it's the reason for 4K screen? I really don't know.
This is another [git,](https://github.com/zhtengw/EFI-for-X1C6-hackintosh/blob/master/OpenCore/EFI/OC/Config.plist), in which whose cpu is the same with the of my laptop. 
However, it still can't work when I use his platforminfo and gpu configure.
Everything will be OK if I delete the gpu configure.
Here is the system info of my laptop.
![image](https://user-images.githubusercontent.com/19789205/87879796-755c4680-ca1f-11ea-8ac8-ef0388eff64a.png)
![image](https://user-images.githubusercontent.com/19789205/87879810-89a04380-ca1f-11ea-8eab-2e8d340294d2.png)
![image](https://user-images.githubusercontent.com/19789205/87879834-ae94b680-ca1f-11ea-8a0c-2669bea85a51.png)
![image](https://user-images.githubusercontent.com/19789205/87879861-c704d100-ca1f-11ea-9d66-b99f1631ca5c.png)

![image](https://user-images.githubusercontent.com/19789205/87879885-e6036300-ca1f-11ea-95aa-1f0a2519f423.png)
![image](https://user-images.githubusercontent.com/19789205/87879895-00d5d780-ca20-11ea-84dd-a385a4797a3b.png)

**Comment by benbender** [comment]
Please use "debug=0x100 -v" in boot-args and report back with an error/image of the stack trace when booting fails.

**Comment by JackokieZhao** [comment]
> Please use "debug=0x100 -v" in boot-args and report back with an error/image of the stack trace when booting fails.

![IMG_20200720_093811](https://user-images.githubusercontent.com/19789205/88196612-fca1f800-cc73-11ea-9805-a3d0789be349.jpg)

**Comment by benbender** [comment]
@JackokieZhao The relevant output (crash/stacktrace) is missing. Please wait until it crashes and take a picture of the bottom part with error-message and stacktrace.

**Comment by tylernguyen** [comment]
@JackokieZhao 
I am still quite baffled by this issue. Why would a Kaby Lake R natively inject a Coffee Lake framebuffer? You must be injecting that somewhere in your config.

Please check your 'config.plist' and make sure that your kexts are up to date.

**Comment by JackokieZhao** [comment]
> @JackokieZhao
> I am still quite baffled by this issue. Why would a Kaby Lake R natively inject a Coffee Lake framebuffer? You must be injecting that somewhere in your config.
> 
> Please check your 'config.plist' and make sure that your kexts are up to date.

I have tried severial times for different combination, but it still can't work. The config.plist is some of what I have tried.
I really don't know how to solve this problem. Maybe, the cpu is a little special....

**Comment by tylernguyen** [comment]
> > @JackokieZhao
> > I am still quite baffled by this issue. Why would a Kaby Lake R natively inject a Coffee Lake framebuffer? You must be injecting that somewhere in your config.
> > Please check your 'config.plist' and make sure that your kexts are up to date.
> 
> I have tried severial times for different combination, but it still can't work. The config.plist is some of what I have tried.
> I really don't know how to solve this problem. Maybe, the cpu is a little special....

Try it again a fresh copy of `EFI-OpenCore` from my repo. If that doesn't work still, try a clean install.

**Comment by tylernguyen** [comment]
This repo has worked for others with an i5 without anything special so I'm confident that it's something wrong yours spherically. Though I am leaning towards software more than hardware.

**Comment by JackokieZhao** [comment]
> This repo has worked for others with an i5 without anything special so I'm confident that it's something wrong with yours specifically. Though I am leaning towards software more than hardware.

Thanks for your answer and help. 
I think it also the reason of myself. However, the new 4K screen in my laptop is different from that of others. I don't know whether it's another reason.
I'll try it again with your instructions, but a clean install may be so expensive.... Anything, thanks for your help.
----------------------------------------------------------------------------------------------------------------------------------------
This is another git [https://github.com/zhtengw/EFI-for-X1C6-hackintosh/blob/master/OpenCore/EFI/OC/Config.plist](url) 
I have only copied his GPU configure into your config.list. Unfortunately, the same disturbing end...

**Comment by tylernguyen** [comment]
@JackokieZhao 

Plug in an external display. If you have graphics acceleration problems on the external display too, it is a hackintosh issue.

If you only have graphics acceleration problem your laptop display, then is most likely the fault of your replacement screen.

**Comment by JackokieZhao** [comment]
I have tried this git https://github.com/zhtengw/EFI-for-X1C6-hackintosh/blob/master/OpenCore/EFI/OC/Config.plist
It appears the same phenomenon as yours config.plist.
Namely, the screen is black, but it will make the same sound as the lockscreen interface when I press the Enter key.

**Comment by tylernguyen** [comment]
> I have tried this git https://github.com/zhtengw/EFI-for-X1C6-hackintosh/blob/master/OpenCore/EFI/OC/Config.plist
> 
> It appears the same phenomenon as yours config.plist.
> 
> Namely, the screen is black, but it will make the same sound as the lockscreen interface when I press the Enter key. 

As I said, you need to isolate the problem with an external display. Plug it pre-boot. HDMI hotplug will not work without a proper EDID patch.

**Comment by tylernguyen** [comment]
@JackokieZhao 

I will close this issue on suspicion that it is because of your aftermarket replacement screen. Feel free to come back once you've isolated the problem.
