### ISSUE TITLE
Intel Wireless

### ISSUE THREAD

**Issue by tylernguyen** [tylernguyen/x1c6-hackintosh#67]
Native WiFi/Bluetooth is nice and all but it's increasing becoming a bottleneck . I also never use Handoff.
Luckily, [OpenIntelWireless](https://github.com/OpenIntelWireless) is in active development.

Personally, I am going to purchase an `ax200` card and do some testing.

Some warnings, the project, though stable for Bluetooth, is still in very early alpha for wireless functions and can be clunky to use.

If anyone has Intel wireless cards laying around, or even the stock one that came with this machine, check out the project and do some testing if you can.

**Comment by 1Revenger1** [comment]
It's become a lot more usable imo in the last week or so when paired with HeliPort. It's still limited to 80211n and below (no ac support yet) and doesn't support some security protocols like WPA2 Enterprise. But it's def usable now if your at home.

**Comment by H15teve** [comment]
Update: airportitwlm has supported Handoff, location, etc. It's approaching native BCMcards' experience.

**Comment by 1Revenger1** [comment]
It does require a seperate kext for each macOS version since the IO80211 headers change - but it's working well on my X1 (Extreme, not Carbon)
What I've done is set AirportItlwm-Cat.kext (I manually renamed them) to MinKernel 19.0.0 and MaxKernel 19.99.99, with Big Sur being MinKernel 20.0.0. You don't need to specify both Min and Max kernel. Here's whats in my config:

**Comment by benbender** [comment]
Sample-config can be found here: https://github.com/benbender/x1c6-hackintosh/blob/experimental/optional/Config-WIFI-Intel.plist

**Comment by tylernguyen** [comment]
VHT80 & VHT160 support is currently being worked on.

At which point, I will likely make the switch to something like an AX200.

Once 2.0.0 is stable, I will make the change permanently on my setup and the repo.
