### ISSUE TITLE
unable to get audio working

### ISSUE THREAD

**Issue by harshach** [tylernguyen/x1c6-hackintosh#7]
hi @tylernguyen 
   I've installed mojave but no luck trying to get audio working.
Installing VoodooHDA does work but it causes kernel panics and reboot through command + r mode which also negatively affects battery life. 
I tried installing using AppleKLC kext and modifying config.plist but since this board has realtek ALC3286 codec and doesn't look its supported https://github.com/acidanthera/AppleALC/wiki/Supported-codecs.
Any pointers on how did you made it work.
Thanks.

**Comment by tylernguyen** [comment]
Hello @harshach 

Which laptop model do you have? You should be able to find this info in the BIOS

**Comment by harshach** [comment]
hi @tylernguyen exactly same model as yours listed in the rEADME

**Comment by tylernguyen** [comment]
@harshach Hi, if it's the same model, try audio layout 11 with AppleALC installed. Change your clover config file under Devices --> Properties -->  PciRoot(0)/Pci(0x1f,3) -->  "#layout-id" --> "layout-id = 11"

**Comment by Romsky** [comment]
Can you tell me why there are so many useless Data is in config.plist which you can't use on X1 Carbon?

On my Device all is working, and I removed many entries you used.
- Why nv_disable=1 (X1 Carbon does not have any Nvidia GPU)
- Why so many  Data in "Device Properties"? related to ATI and Nvidia? X1 Carbon does not have any AMD or Nvidia Hardware. 

Maybe I miss something, so please tell me why using this datas...

**Comment by tylernguyen** [comment]
> @tylernguyen thanks for the reply. But this didn't help either
> 
> ![image](https://user-images.githubusercontent.com/38649/51071131-171bff80-1601-11e9-9264-71ebc1cdf42a.png)

@harshach This is what it should look like ![audio help](https://ucbc86154ade91244ac57126675e.previews.dropboxusercontent.com/p/thumb/AASOoEL049FlssYiu_S2T6WLsav4sUJ1vJxnpSiopKoWD2eKUOwbJBgZiSrT6CIJVyS-1mxcU_09A7L_PWEaYvqUVfpFIWXi0byhsK2KWcGG8cLJMOIekl5Bu-49MimIHsQYjphS-cXAizeg4xEnfvECCEILDmH9jAtgoQK1q4h4HWGvKZwIuz3qbsPuDezEH5pCFTpyDGJ7mB8rQ0lsR83O9Fhne1TgWr4CtMqZboWhTu6bGHUCwzQIEGknGCTlz24thpiBjNtdNd6yp9xN7SFIjc_PKRDsJfgVT1VS6nlzHyY0z1j85yyraMArzEguRHbIPv-mbec7x6tTTfcwHffX-pS4Df9eKo4mb2qztN6Hkw/p.png?size=2048x1536&size_mode=3)

**Comment by e92335i** [comment]
> > @tylernguyen thanks for the reply. But this didn't help either
> > ![image](https://user-images.githubusercontent.com/38649/51071131-171bff80-1601-11e9-9264-71ebc1cdf42a.png)
> 
> @harshach This is what it should look like ![audio help](https://camo.githubusercontent.com/68200be634398b9b41bfa6063ad8b9036892de035cf98a99684551473f7bfea9/68747470733a2f2f756362633836313534616465393132343461633537313236363735652e70726576696577732e64726f70626f7875736572636f6e74656e742e636f6d2f702f7468756d622f4141534f6f454c303439466c73735969755f53325436574c7361763473554a31764a786e7053696f704b6f574432654b554f77624a42675a695372543643494a5679532d316d7863555f303941374c5f5057456159767155566670464957586930627968734b324b5763474738634c4a4d4f49656b6c3542752d34394d696d49487351596a7068532d635841697a65673478456e667645434345494c446d48396a4174676f514b3171346834485747764b5a7749757a33716273507544657a45483570434654707944474a376d42387251306c735238334f3946686e6531546757723443744d715a626f57685475366247485543777a514945476b6e4743546c7a323474687069426a4e74644e6436797039784e375346496a635f504b5244734a66675654315653366e6c7a487959307a316a3835797972614d41727a4567755248624950762d6d626563377836745454666377486666582d705334446639654b6f346d6232717a744e36486b772f702e706e673f73697a653d3230343878313533362673697a655f6d6f64653d33)

Hi. Can you repost this image please.
I have the same exact computer and used your latest post EFI and have the same issue. No audio working on the onboard audio. Thanks
