### ISSUE TITLE
BIOS mod 1.49 - Thinkpad active protection sensor diagnostics start

### ISSUE THREAD

**Issue by Porco-Rosso** [tylernguyen/x1c6-hackintosh#71]
**Describe the bug**
bootloop with modded 1.49 BIOS mod

**To Reproduce**
1. Upgrade to BIOS firmware 1.49
2. Copy, mod and flash BIOS as detailed
3. Attempt boot

**Expected behavior**
Expect to boot into normal MacOS

**Info**
So I am currently on BIOS 1.49, I attempted to flash the bios to unlock it and enable advanced settings such as undervolting.
The first problem occurred when I attempted to boot. I get into the BIOS settings, and can see the advanced features available. I assumed this meant the flash was successful.

 However once I try to boot, instead of being greeted with the normal ReFind bootloader, I get a flash on the screen that says: `Thinkpad active protection sensor diagnostics start` and enter a bootloop. Something went wrong somewhere.
I then reflashed my backup of the 1.49 BIOS. I was scared when I was greeted with the message: `Bad CRC of security settings in EFI variable`. Thankfully, I was able to boot into MacOS when I disabled under chip security check under security tab, although I saw `Thinkpad active protection sensor diagnostics start` flash before the bootloader appeared

Has anyone been able to use 1.49? Should I disable security check on the modded BIOS? Should I attempt to roll back to 1.46, which as I understand is confirmed to be working? Is this somehow tied to the face I did not use the modded config.plist yet? I doubt so because I didn't even get to a bootloader. Some input would be appreciated.

**Comment by zacharysalvatore** [comment]
I'm currently using version 1.49-1.20 (2020-6-10 updates)mod. It works without problems.

**Comment by benbender** [comment]
@Porco-Rosso Are you sure the dump of the 1.49-bios via SPI-Flasher was correct? Maybe a bad connection of the flasher? I always recommend to do 2 separate dumps (with reseating the clip in between) and do a diff on the two dumps to be sure they are the same.

**Comment by zacharysalvatore** [comment]
@benbender oh, there's a thing I'd like to know. I accidentally deleted my bios dump, is it safe to just install an official one for an update?

**Comment by benbender** [comment]
I see no reason why not, but never did it so can't say for sure.

**Comment by Porco-Rosso** [comment]
Hi @benbender, yes I dumped the Bios twice and checked they were equivalent. I don't think there is an issue there. If the BIOS image/flash was corrupt, I don't think I would be able to load the BIOS settings at all right?

@zacharysalvatore could you share your Bios patches .txt ? Maybe I commented out something I wasn't supposed too. I also did replace all, with a hex editor to change the line, like in the docs.

It wouldn't work to use someone else's BIOS image right?

**Comment by benbender** [comment]
@Porco-Rosso it might work if the image is also a dump and the exact same hw. But I don't see the point to be honest if you are able to boot up atm.

**Comment by Porco-Rosso** [comment]
After repatching and reflashing I still encountered the same error. Luckily, I was eventually able to boot, by setting `Startup>CSM Support YES`
Next I played around with some of the BIOS settings. I and was not able to boot with DVMT Pre-Allocated 64M, so I stayed with 32M (what does this setting do?). Likewise undervolting as indicated in the guide didn't work on my config despite being I think identical to tylernguyen. I haven't had time to play around with what values I can support but got it to work with Processor -80, GT and Uncore at -40.
Finally, after getting a booting BIOS config, I tried to boot with the config.plist for the modded BIOS, but couldn't get it to work, it hangs on the login loading bar about 2/3rds of the way. I suspect something is wrong in my config file, would appreciate if someone could take a glance.
[config_modded-notworking.plist.zip](https://github.com/tylernguyen/x1c6-hackintosh/files/5138881/config_modded-notworking.plist.zip)

**Comment by benbender** [comment]
Are you sure, you don't have a problem with refind? Btw, why are you using it anyways?

I can't say what's up with your machine, but I can say you this:
- CSM disables parts of UEFI and enables an old-style bios compatibility layer. It shouldn't be used or needed with opencore.
- DVMT Pre-Alloc sets the initial amount of videoram for the GPU and is expected to be at least 64mb for OSX. That's one of the main reasons for the bios-patch because you can't adjust it without the patch. Thats also the reason you get stuck on booting OSX. Your framebuffer is crashing because of the 32MB DVMT.
- I would reset the bios to all its defaults and stay away from things like undervoltung until you got the basics stable.

It sounds like you have a problem with your GPU's initialization or management engine. But that's a wild guess and if you did the patch right and it's known to work with that bios, I have no real Idea.

**Comment by Porco-Rosso** [comment]
I am using rEFInd in order to support dual booting (MacOS/Windows). With CSM mode off, I can only boot into windows directly through the windows bootloader. 
I think at this point my modded BIOS is correct and not corrupted. I will try resetting the BIOS settings and seeing if I can get it to boot that way with only the recommended changes. 

Thank you for letting me know about DVMT and CSM, I now know what is the culprit for the inability to launch MacOS, and will try to experiment around that.

**Comment by benbender** [comment]
You don't need refind for dual-booting. Opencore dual-boots fine. Something with your installation/boot-setup seems weird. I would suggest a complete reinstall from the ground up following this repo and those guides using UEFI + opencore completely:

- https://github.com/dortania/OpenCore-Multiboot
- https://dortania.github.io/OpenCore-Install-Guide/
- https://dortania.github.io/OpenCore-Post-Install/

**Comment by parndt** [comment]
Just to chime in that by simply cloning this repo with no modifications, and with BIOS 1.49 mod enabled, I can boot happily with 64MB DVMT etc (this is required for external 4K support).

**Comment by Porco-Rosso** [comment]
@parndt have you applied a EDID patch or used [one-key-hidpi ](https://github.com/xzhih/one-key-hidpi)?

In any case, I think my initial issue has been resolved, so I will be closing this. Might reopen if something emerges as I explore tweaking the bios/config.

**Comment by benbender** [comment]
@Porco-Rosso for hidpi you are usually need at least 64mb dvmt (via patched Bios or patched AppleIntelKBLGraphics.kext). If you just lower your stolenmem, higher resolutions will not fit into memory and usually aren't available.

**Comment by parndt** [comment]
@Porco-Rosso For the internal LCD I might have used one-key-hidpi, because I can't get it to be anything but a 2560x1600 display otherwise (it's the 2560x1440 panel).
