### ISSUE TITLE
I have a question about dual booting using wwan ssd

### ISSUE THREAD

**Issue by korjwl1** [tylernguyen/x1c6-hackintosh#76]
I successfully installed hackintosh on the wwan ssd, and using the opencore booting usb, I could get into it. 
I also mounted EFI folder and copy pasted your Boot and OC folder in it.
However, if I try to boot without a usb, the only thing my thinkpad recognize is the PM981.
I formatted my PM981, reinstalled hackintosh on the WWAN SSD, and then reinstalled Windows on the PM981.
Typing F12 only shows me windows booting manager and NVME: Samsung.... (PM981).
I wonder how did you dual boot hackintosh on the WWAN SSD.

Specification
Thinkpad X1 C6 with I7-8550U, 2k HDR panel
NVME SSD: PM981
WWAN SSD: Revuahn NX1142 SSD (Almost same one as HP EX900)

**Comment by benbender** [comment]
@korjwl1 Wild guess and unchecked, but my first candidate would be OC scan-policy: https://dortania.github.io/OpenCore-Post-Install/universal/security/scanpolicy.html

**Comment by tylernguyen** [comment]
@korjwl1 If you install macOS on the WWAN drive, it should have created a boot entry during install. Alternatively, you may install rEFInd on your main drive to boot into Windows or OpenCore.
