### ISSUE TITLE
config_unmoddedBIOS.plist is much smaller than config.plist

### ISSUE THREAD

**Issue by jeremylan** [tylernguyen/x1c6-hackintosh#77]
**Describe the bug**
Hi, it looks like the file `config_unmoddedBIOS.plist` is incomplete. The modded `config.plist` is 39k, where the unmodded one is only 2k.
Thanks

**Comment by benbender** [comment]
`config_unmoddedBIOS.plist` is indeed incomplete as it consists only of the missing part needed for those without patched bios. Simply add those parts from `config_unmoddedBIOS.plist` to `config.plist`. And don't forget to close the issue :)

**Comment by jeremylan** [comment]
@benbender thank you for the quick reply.
I understand thanks. The documentation though is not clear at all, it is implying it's either one or the other rather than a merge so maybe it should be clearly stated. Thanks again.

**Comment by benbender** [comment]
I See your point, but it's not my repo. I guess, best would be if you suggest some changes to this as a merge request to this repo. Sharing is caring :) Alternatively you could open a separate Issue about the documentation problem. 

// cc @tylernguyen

**Comment by tylernguyen** [comment]
@jeremylan @benbender 
**I'll change the doc**. Originally, I was intending to maintain 2 separate config files but I found this solution easier. Thanks for the notice.

**Comment by jeremylan** [comment]
No problem, thank you so much for documenting all this. I really appreciate your time.
