### ISSUE TITLE
Add AppleBacklightSmoother kext

### ISSUE THREAD

**Issue by velaar** [tylernguyen/x1c6-hackintosh#79]
A nice little kext that removes steps from X1C6/UHD620 brightness control. Way better experience.

Available [here](https://github.com/hieplpvip/AppleBacklightSmoother)
Tested working for both buttons and slider on the latest repo setup. 

Will need a new SSDT-PNLF

**Comment by tylernguyen** [comment]
Noted. I will implement this on the next commit, which will likely be the last commit before Big Sur.

**Comment by tylernguyen** [comment]
Implemented as of 644688d
