### ISSUE TITLE
Can you tell me why there are so many useless Data is in config.plist which you can't use on X1 Carbon?

### ISSUE THREAD

**Issue by tylernguyen** [tylernguyen/x1c6-hackintosh#8]
Can you tell me why there are so many useless Data is in config.plist which you can't use on X1 Carbon?

On my Device all is working, and I removed many entries you used.
- Why nv_disable=1 (X1 Carbon does not have any Nvidia GPU)
- Why so many  Data in "Device Properties"? related to ATI and Nvidia? X1 Carbon does not have any ATI or Nvidia Hardware. 

Maybe I miss something, so please tell me why using this datas...

_Originally posted by @Romsky in https://github.com/tylernguyen/x1c6-hackintosh/issues/7#issuecomment-455339352_

**Comment by tylernguyen** [comment]
@Romsky

I modify the clover config based upon rehabman's repository since he updates it often with new patches. Since the entries he has do not affect the laptop's functionality as far as I know. I have no need to remove them.

**Comment by Romsky** [comment]
yeah, you are right, its not effecting, but for me I like a clean config. Who knows, maybe some things will cause problems in future.

Just one question, is 2 Finger swipe (in Safari) working on your device? On my one, 3 Finger works etc, but I miss 2 finger swipe.

Greets

**Comment by tylernguyen** [comment]
@Romsky  If you're talking about scrolling with two fingers, that works for me. I'm not sure about other gestures since I do not use them. But what I can tell you is that VoodooPS2 turns multi-finger gestures into keyboard inputs so you might have to manually create the shortcut/action.
