### ISSUE TITLE
Command and ALT keys are swapped

### ISSUE THREAD

**Issue by jeremylan** [tylernguyen/x1c6-hackintosh#81]
I use a very similar `config.plist` and ACPI patches and everything seems to work well, excluding this weird issue.

The Command Key (usually mapped to the Windows key on my laptop's keyboard) and the Alt key are swapped. This does not happen in Clover (I am moving to OC 0.62 but still can boot in Clover) or on the external keyboard. I can't see any ACPI patch or anything else that would cause this.

Thanks

**Comment by benbender** [comment]
See https://github.com/tylernguyen/x1c6-hackintosh/blob/5eeea6037e2127cdb0867eee7df2613e6356fb7c/patches/SSDT-Keyboard.dsl#L314

**Comment by tylernguyen** [comment]
@jeremylan 

As @benbender stated, the current patch is mapped to what I prefer on my own setup. You're welcomed to edit the keyboard ACPI patch according to your own preference. Alternatively, you may find https://karabiner-elements.pqrs.org/ easier to use and contain more features.

**Comment by jeremylan** [comment]
@tylernguyen @benbender thanks guys, sorry I totally missed this

**Comment by benbender** [comment]
no problem. have fun!
