### ISSUE TITLE
Fix accesses to 16byte-EC-field HWAC

### ISSUE THREAD

**Issue by benbender** [tylernguyen/x1c6-hackintosh#82]
**Describe the bug**
Please check if you have accesses to \_SB.PCI0.LPCB.EC.HWAC in _OWAK() and/or _L17() of your DSDT. 

I think you have and these accesses needs to be patched as it crashes in OWAK() on wakeup and might be the root of some of the bugs described here. 

Method + patch for the issue here: https://github.com/benbender/x1c6-hackintosh/blob/experimental/SSDT-HWAC.dsl

**To Reproduce**
Sleep + Wakeup, check `sudo dmesg` or `syslog` for ACPI-errors when accessing the HWAC-field...

Edit: It might be hard to see actual logs of this bug. See my SSDT for an explanation.

**Comment by tylernguyen** [comment]
Issue confirmed.

Is there any reason why you wanted to split this off? I was planning on implementing the new battery patch which should include this.

**Comment by benbender** [comment]
No reason other than to point on the issue. As I said before, Im astonished that nobody on different repos noticed that severe bug and want to change that

**Comment by tylernguyen** [comment]
Implemented as of 644688d
