### ISSUE TITLE
YogaSMC

### ISSUE THREAD

**Issue by tylernguyen** [tylernguyen/x1c6-hackintosh#87]
[YogaSMC](https://github.com/zhen-zen/YogaSMC) is progressing quickly thanks to the great @zhen-zen

This issue thread will serve as a placeholder for the project: its features, bug, and application as it relates to the x1c6 machine.

**The repo is already setup for YogaSMC with `SSDT-EC` and the kext. All you need to do is to install the app and preference panel to make adjustments.**

Currently, I have confirmed the following working:

- Fn Key handling (now repo default over ThinkpadAssisstant)
- Charge threshold
- LED control and LED state syncing after sleep
- DYTC Performance mode
- Fan Control

Not-working

- DYTC Quiet Mode
~~- Fan Control~~

Additionally, YogaSMC is built automatically with each commit, so update as you test 👍 

Feel free to chime in.

EDIT: As of v1.30, Fan control now works

**Comment by benbender** [comment]
`DYTC Quiet Mode` isn't supported on the x1c6. So it's a UI- or HW-issue. Depends on your viewpoint :)

**Comment by KirisameMarisaa** [comment]
I‘ve tested YogaSMC several weeks ago, with version 1.2.1 Release. 
The fan cannot be controlled, but you can see readings of fan speed inside of the panel. However, the digit seems to be static. Perhaps @Zhen-zhen haven't implemented fan-speed automatic refreshing. 

Looking forward for full support of fan control&reading. The X1 Carbon will perform way better with its fan ON when doing extensive works or running benchmarks XD

**Comment by buyddy** [comment]
The FNLock seems to be reversed. When it is off Fn keys are in actions instead of F1, F2, is there a way to change it?

Also I realize now in IntelPowerGadget my min frequency won't go below 0.9GHz anymore. The same CPUDataProivder let me go down to 0.6Ghz/0.5Ghz. I am wondering if I need to regenerate it?

**Comment by buyddy** [comment]
<img width="662" alt="Screen Shot 2020-11-05 at 2 07 32 PM" src="https://user-images.githubusercontent.com/64387298/98304424-91133a80-1f85-11eb-89ea-49a16874d130.png">
@tylernguyen  Do you have the same issue?

**Comment by tylernguyen** [comment]
> <img width="662" alt="Screen Shot 2020-11-05 at 2 07 32 PM" src="https://user-images.githubusercontent.com/64387298/98304424-91133a80-1f85-11eb-89ea-49a16874d130.png">
> 
> @tylernguyen  Do you have the same issue?

- Fan speed is WIP
- Charge threshold will not be read. It must be set.

**Comment by buyddy** [comment]
@tylernguyen are you able to enter numbers? I can't seem to enter anything.
Also do you have the issue of wake up from sleep and the Mute Botton is on (and there is no sound)?

**Comment by tylernguyen** [comment]
> @tylernguyen are you able to enter numbers? I can't seem to enter anything.
> 
> Also do you have the issue of wake up from sleep and the Mute Botton is on (and there is no sound)?

- My charge threshold works normally.
- I have not observed that issue.

I'm on the latest commit build from the actions tab. Are you guys on the release version?

**Comment by zhen-zen** [comment]
Actually fan control is available for debug binaries...

**Comment by buyddy** [comment]
> > @tylernguyen are you able to enter numbers? I can't seem to enter anything.
> > Also do you have the issue of wake up from sleep and the Mute Botton is on (and there is no sound)?
> 
> * My charge threshold works normally.
> * I have not observed that issue.
> 
> I'm on the latest commit build from the actions tab. Are you guys on the release version?

I see. This could be the problem. I am on the released version.

**Comment by buyddy** [comment]
@tylernguyen I still have the issue of waking up and Mute Botton is on with LED on. The sound is not working until I adjust the volume using the Volume UP and Down. This was not the case in the past. Do you have this issue?

**Comment by tylernguyen** [comment]
@buyddy 

Try turning off Mute in LED automation.

**Comment by buyddy** [comment]
> @buyddy
> 
> Try turning off Mute in LED automation.

That seems to be the issue. What is the use of that LED automation?

**Comment by benbender** [comment]
@buyddy Its intended use is to persist the state of the corresponding function to be retained after sleep. So if you've muted your mic before sleeping the notebook it is also muted afterwards. But you are right, see the same issue. Pls open a bug at the repo of YogaSMC so it can be tracked and solved there.

**Comment by KirisameMarisaa** [comment]
YogaSMC 1.30 introduced formal fan control via YogaSMCNC. to achieve it, we need to install YogaSMC, YogaSMCNC, YogaSMCPrefpane and patch EC read/write for YogaSMC. (see /YogaSMC/SSDTSample/SSDT-ECRW.aml)

after that, you can access fan ctrl via menubar icon. 

<img width="313" alt="image" src="https://user-images.githubusercontent.com/60131395/99200791-67a6aa00-27e2-11eb-81dd-d348aa55a192.png">


I patched it by replacing RE1B and RECB method in the battery patch SSDT with the one in the SSDT-ECRW.dsl. The fan ctrl & battery monitoring function works properly, but it seems to break the sleep again: Wake from Normal Sleep [CDNVA] : due to PWRB/UserActivity Assertion.

**Comment by benbender** [comment]
@KirisameMarisaa the patches are here: https://github.com/tylernguyen/x1c6-hackintosh/blob/master/patches/SSDT-EC.dsl and are unrelated to sleep.

**Comment by tylernguyen** [comment]
@KirisameMarisaa 

Just as @benbender stated, YogaSMC dependecies are already implemented by default in the repo.

In addition, your sleep seems normal. I believe PWRB is you pressing the power button to wake the machine up.

**Comment by KirisameMarisaa** [comment]
> @KirisameMarisaa
> 
> Just as @benbender stated, YogaSMC dependecies are already implemented by default in the repo (You do not need to anything else other than installing the app and the pref panel). YogaSMC is also unrelated to sleep.
> 
> In addition, your sleep seems normal. I believe PWRB is you pressing the power button to wake the machine up. It seems to sleep fine in between the time of entering sleep and you pressing the power button, I presume?

No, it doesn't. as shown in the screenshot, abnormal wake reason 'RTC/UserActivity' kept on waking the machine. I've moved on the latest EFI patch you uploaded now, and are doing further testing.

**Comment by KirisameMarisaa** [comment]
> > @KirisameMarisaa
> > Just as @benbender stated, YogaSMC dependecies are already implemented by default in the repo (You do not need to anything else other than installing the app and the pref panel). YogaSMC is also unrelated to sleep.
> > In addition, your sleep seems normal. I believe PWRB is you pressing the power button to wake the machine up. It seems to sleep fine in between the time of entering sleep and you pressing the power button, I presume?
> 
> No, it doesn't. as shown in the screenshot, abnormal wake reason 'RTC/UserActivity' kept on waking the machine. I've moved on the latest EFI patch you uploaded now, and are doing further testing.

UPDATE: I noticed that with your latest EFI, CPU Package Power cannot go less than 1.7w. Is it related to the TB3 patch? I also noticed that the USB-C ports cannot identify USB-3/3.1 devices. Do I need to flash TB3 chip with the custom firmware in order to get proper power management?

**Comment by tylernguyen** [comment]
@KirisameMarisaa 

RTC wakes are normal, even in real Macs, see https://osxdaily.com/2010/07/17/why-mac-wakes-from-sleep/

You can also try the changes detailed in https://github.com/tylernguyen/x1c6-hackintosh/blob/master/docs/3_README-other.md

As I have stated before, your sleep looks to be functioning fine. As you can you see, it wakes periodically for macOS related tasks. If you have another reasons to believe otherwise, please create a separate issue and refrain from going off topic within this one.

**Comment by tylernguyen** [comment]
> > > @KirisameMarisaa
> > > Just as @benbender stated, YogaSMC dependecies are already implemented by default in the repo (You do not need to anything else other than installing the app and the pref panel). YogaSMC is also unrelated to sleep.
> > > In addition, your sleep seems normal. I believe PWRB is you pressing the power button to wake the machine up. It seems to sleep fine in between the time of entering sleep and you pressing the power button, I presume?
> > 
> > 
> > No, it doesn't. as shown in the screenshot, abnormal wake reason 'RTC/UserActivity' kept on waking the machine. I've moved on the latest EFI patch you uploaded now, and are doing further testing.
> 
> UPDATE: I noticed that with your latest EFI, CPU Package Power cannot go less than 1.7w. Is it related to the TB3 patch? I also noticed that the USB-C ports cannot identify USB-3/3.1 devices. Do I need to flash TB3 chip with the custom firmware in order to get proper power management?

Again, please refrain from going off-topic within this issue.

As detailed within README.md, 3.1 hotplug is still work-in-progress Also as detailed in 1_README-HardwareandBIOS, currently, cpu storms when BIOS assisst is not enabled, you have to choose between hotplug and power for now.

**Comment by KirisameMarisaa** [comment]
> > > > @KirisameMarisaa
> > > > Just as @benbender stated, YogaSMC dependecies are already implemented by default in the repo (You do not need to anything else other than installing the app and the pref panel). YogaSMC is also unrelated to sleep.
> > > > In addition, your sleep seems normal. I believe PWRB is you pressing the power button to wake the machine up. It seems to sleep fine in between the time of entering sleep and you pressing the power button, I presume?
> > > 
> > > 
> > > No, it doesn't. as shown in the screenshot, abnormal wake reason 'RTC/UserActivity' kept on waking the machine. I've moved on the latest EFI patch you uploaded now, and are doing further testing.
> > 
> > 
> > UPDATE: I noticed that with your latest EFI, CPU Package Power cannot go less than 1.7w. Is it related to the TB3 patch? I also noticed that the USB-C ports cannot identify USB-3/3.1 devices. Do I need to flash TB3 chip with the custom firmware in order to get proper power management?
> 
> Again, please refrain from going off-topic within this issue.
> 
> As detailed within README.md, USB 3.1 hotplug is still work-in-progress Also as detailed in 1_README-HardwareandBIOS, currently, cpu storms when BIOS assisst is not enabled, you have to choose between tb3 hotplug and power for now.

ok, I've deleted all off-topic replies.

**Comment by tylernguyen** [comment]
As of YogaSMC 1.4.1

I consider YogaSMC implementation within this repo stable. Any issues you have with the repo's implementation should be a separate issue while bugs with the project itself should be opened on the project's repo.
