### ISSUE TITLE
Waking up causes reboot

### ISSUE THREAD

**Issue by lubixxx96** [tylernguyen/x1c6-hackintosh#89]
**Describe the bug**
Hi Tyler,
After the latest changes, I am no longer able to put my X1C6 (identical hw specs as yours btw) to sleep. Waking up causes cold boot with one weird side effect: My keyboard's not working. I need to manually reset via pwr button one more time to get it back.
I use your EFI folder without any additional changes, it has been always working for me just like that.
Also modded bios, with default setting and changed only what you listed in the 1_README-HARDWAREandBIOS
I've tried both "Windows 10" and "Linux" sleep options form bios and 0,3 and 25 hibernatemodes in pmset, no difference.

Here is the log from pmset":

Time stamp                Domain              	Message                                                                    	Duration  	Delay     
==========                ======              	=======                                                                    	========  	=====     
UUID: BA3850A9-D3A0-4E8E-9A8C-FF94DC621D6A
2020-11-04 07:34:23 +0100 Sleep               	Entering Sleep state due to 'Software Sleep pid=186': Using AC (Charge:99%)           
2020-11-04 07:34:26 +0100 PM Client Acks      	Delays to Sleep notifications: [com.apple.apsd is slow(3015 ms)]           
2020-11-04 07:35:55 +0100 ShutdownCause       	SMC shutdown cause: 5: Software initiated shutdown                         	          
2020-11-04 07:35:57 +0100 HibernateStats      	hibmode=0 standbydelaylow=0 standbydelayhigh=0                             	          0         	
Sleep/Wakes since boot at 2020-11-04 07:27:46 +0100 :0   Dark Wake Count in this sleep cycle:2

Time stamp                Domain              	Message                                                                    	Duration  	Delay     
==========                ======              	=======                                                                    	========  	=====     
UUID: Unknown UUID
2020-11-04 07:35:57 +0100 Sleep               	Entering Sleep state due to '': Using AC (Charge:0%)           
2020-11-04 07:35:57 +0100 Failure             	Failure during wake: 0x00000023 : Failure while halting boot CPU panic     	          
Sleep/Wakes since boot at 2020-11-04 07:27:46 +0100 :0   Dark Wake Count in this sleep cycle:2

**Comment by tylernguyen** [comment]
@lubixxx96 

Did you do a clean update the newest EFI?

If not, could you please provider a copy of your EFI?

**Comment by lubixxx96** [comment]
Sure, I did clean update.
Here is EFI folder:
https://drive.google.com/file/d/1RxhOcZG4o74hv8841ezx2rU3necVEJYR/view?usp=sharing

here are pmset settings:
Currently in use:
 hibernatemode        3
 halfdim              1
 lidwake              1
 womp                 0
 networkoversleep     0
 sleep                0 (sleep prevented by mds_stores, coreaudiod, coreaudiod, coreaudiod)
 ttyskeepawake        1
 disksleep            10
 hibernatefile        /var/vm/sleepimage
 gpuswitch            2
 displaysleep         15 (display sleep prevented by zoom.us)

I will try the legacy battery patch.

**Comment by benbender** [comment]
@lubixxx96 

First: please stay on hibernatemode 3 to have a testing-ground.

Then a few questions:
- Do you have any devices attached while going to sleep? 
- Catalina or Big Sur?
- Unpatched or patched Bios?
- Does the system come up with a message about the crash which gives you a stacktrace? If yes please be sure to have `keepsyms=1`in boot-args and paste the stacktrace.

**Comment by lubixxx96** [comment]
- I do have USB-C dock, which also powers the notebook. A few usbs, hdmi screen and ethernet connected to the dock too.
- Catalina
- patched bios, currently with Windows 10 sleep mode and bios assisted thunderbolt
- I put keepsyms=1 in the boot-args, but the notebook does not show any information when the issue happend

When I put notebook to sleep, the light on the power button first blink quickly, similar or same as when you attach the AC cable to the notebook, and then it stats pulsating. When I hit the button to wake the notebook, it will start booting, not waking up.
It shows the message that my PC was not shut down correctly etc...

**Comment by Charlyo** [comment]
@lubixxx96 do you have any kind of undervolt?

**Comment by lubixxx96** [comment]
> @lubixxx96 do you have any kind of undervolt?

Not in the BIOS, only via VoltageShift. It does not caused any issues so far...

**Comment by Charlyo** [comment]
Remove the undervolt and try to sleep again.

**Comment by benbender** [comment]
> * I do have USB-C dock, which also powers the notebook. A few usbs, hdmi screen and ethernet connected to the dock too.

Remove every device connected before going to sleep. Check if the issue persists.

> * patched bios, currently with Windows 10 sleep mode and bios assisted thunderbolt

Any other, noteable changes in bios?

> * I put keepsyms=1 in the boot-args, but the notebook does not show any information when the issue happend
> When I put notebook to sleep, the light on the power button first blink quickly, similar or same as when you attach the AC cable to the notebook, and then it stats pulsating. When I hit the button to wake the notebook, it will start booting, not waking up.
> It shows the message that my PC was not shut down correctly etc...

And the message dont have a "report"-button to send/look at the stacktrace?

One unanswered question: is it reproduceable on any sleep?

Besides that: It seems to be related to your specific config as f.e. neither me nor tyler have those issues. Strategy should be to try to remove moving parts (remove attached devices, remove undervolt, reset bios etc) one by one and see what changes the behaviour.

**Comment by lubixxx96** [comment]
- tried to remove all devices, no difference
- no other changes, just what Tyler mentioned in his readme
- is does happen every single time I want to put notebook to sleep.

- I've tried to update to Big Sur, now the behavior changed...to worse. The led wont stop blinking, fan does not stop. Black screen. I have to kill it by holding power button. Again tried to remove all devices, switch back to Linux sleep mode. No difference.

UUID: Unknown UUID
2020-11-04 16:11:30 +0100 Sleep               	Entering Sleep state due to '': Using AC (Charge:0%)           
2020-11-04 16:11:30 +0100 Failure             	Failure during wake: 0x2FE995C900000028 : Informing clients about completed changes to system caps  	          
Sleep/Wakes since boot at 2020-11-04 15:59:41 +0100 :0   Dark Wake Count in this sleep cycle:0

**Comment by lubixxx96** [comment]
Update:

With hibernatemode 3 and linux bios option, sleep works
with hibernatemode 25, the led wont stop blinking and fan wont stop, but when I kill it by holding the power button and then start again, it will recover, which I never experienced on Mac. I can see Bios message, and then it will boot mac but exactly where I left it. Like good old windows hibernate.

**Comment by benbender** [comment]
@lubixxx96 Please update to the latest version and hibernatemode 25 should work. I fixed it a few hours after @tylernguyen push. 

@tylernguyen For reference: `keepsyms=1 -hbfx-dump-nvram rtcfx_exclude=80-AB` is the problem.

**Comment by lubixxx96** [comment]
It works now.
I updated to the latest commit and its working now. Even with 25 hibernatemode and Windows 10 set in bios.

Thank you guys!
