### ISSUE TITLE
Automatic Reboot with ThunderboltDisplay

### ISSUE THREAD

**Issue by Romsky** [tylernguyen/x1c6-hackintosh#9]
Ive tested this config now with my new Display. If I connect this with the x1 Carbon over Thunderbolt the System reboots immediately after connect to display. Its a LG 34WK95U display. Is this because we spoof other GPU (with Lilucpu=9) or is this a bug in the Thunderbolt fix?

**Comment by tylernguyen** [comment]
Hello @Romsky 

Currently, I'm still in the process of investigating the HDMI issue, I suspect that these two issues may be connected. I don't have an eta for when this may be fixed but I will update the repo as soon as I can.

**Comment by fbartolini** [comment]
I get the same thing using a usb-c monitor as well. 
I can power via that port, I can plug a usb-c pen drive in it. but if I plug my usb-c monitor cable it panics immediately. 
Have you tried plugging it on the second port? I understand both are TB3 ports.

**Comment by nickwong680** [comment]
Yep, second port works fine.
It is annoying that it will reboot automatic if I accidentally plug my usb-c monitor cable into the usb-c charging port.

**Comment by Hochiss** [comment]
the 1st TB3/USB-C port( close to hinge) doesn't work with ext. monitor, only the 2nd one works. I am desperately in find a solution and reason as well.

**Comment by tylernguyen** [comment]
@Romsky @fbartolini @MrNickWong @Hochiss Hello everyone, I'm sorry for being late but I finally seem to have resolved this issue. Please try my latest EFI-OpenCore folder and let me know your results!
