### ISSUE TITLE
Native Power Management doesn't work after latest update

### ISSUE THREAD

**Issue by H15teve** [tylernguyen/x1c6-hackintosh#92]
Model: 8550U, WQHD-HDR Screen, BIOS modded
Updated to the latest commit, and there are 2 items remained in Energy Saver menu. I tried reseting SSDT-PLUG.aml to last version and managed to recover the native power management.

**Comment by tylernguyen** [comment]
Thanks for noticing!

Fix as of 3cc241d

Please test the new EFI and let me know.
