### ISSUE TITLE
Can not Boot Windows Via Opencore0.6

### ISSUE THREAD

**Issue by HsunGong** [tylernguyen/x1c6-hackintosh#94]
## Boot Windows stuck in the `loading` button.

I choose the Windows boot option and find that it can not boot.

No error message was found even if I turn opencore-debug on.

* 1, Appearance:

The loader icon just stuck there, and no `Windows Logo` has been shown.

![IMG_20201101_072132](https://user-images.githubusercontent.com/32933986/98352068-82e21e80-2058-11eb-9284-5799ae14a14f.jpg)

* 2, plist:

[config.plist.txt](https://github.com/tylernguyen/x1c6-hackintosh/files/5500291/config.plist.txt)

* 3, info:

MACOS 10.15.6
Opencore 0.6.2
Windows 10 1907
Disk WD

**Comment by tylernguyen** [comment]
@HsunGong 

Per 3_README-other.md

It can be quite troublesome to boot Windows with OpenCore, due to the nature of the bootloader and ACPI patches. 

I recommend you to boot using the laptop's boot manager or use something like rEFInd
