### ISSUE TITLE
trackpoint optimization

### ISSUE THREAD

**Issue by lucas-www** [tylernguyen/x1c6-hackintosh#96]
First of all, thank you so much for your awesome project.  @tylernguyen @benbender 
My most commonly used and most convenient trackpoint has poor accuracy in macOS and inaccurate positioning. This makes me feel very bad. Could you help optimize it? Trackpoint works quite well in windows10, and it is better than macOS a lot.
OS version: catalina 10.15.7
Hardware: x1 carbon 6th

**Comment by notthebee** [comment]
Hi Lucas, 

Personally, setting a flat acceleration profile for the mouse made my trackpoint feel much more precise.
Open the Terminal and type:
`defaults write .GlobalPreferences com.apple.mouse.scaling -1`
Reboot and you should notice the difference.

**Comment by benbender** [comment]
@lucas-www I'm not noticing any kind of inaccuracy with the trackpoint - in the sense from bad translation between finger and cursor. Besides that its, afaik, quite configureable (I'm fine with the defaults) and things like speed & acclerationcurves are highly subjective.

If there is "inaccuracy" in a buggy sense for you, I'm sure @1Revenger1 can help as he is the author and put quite a lot of effort in optimizing the experience.

**Comment by velaar** [comment]
If I remember correctly, there were 2 different tracepoint models used in X1C6. There might be a case where it doesn't work properly with one of them. In my case 20KH I have no issues with it as well.

**Comment by benbender** [comment]
@velaar thats interesting. 
@lucas-www could you provide a dump with https://github.com/vulgo/IORegistryExplorer so we can compare. If it's indeed another model, a bug at VoodooRMI should be opened.

**Comment by velaar** [comment]
@benbender 
Archlinux wiki alludes to it [here](https://wiki.archlinux.org/index.php/Lenovo_ThinkPad_X1_Carbon_(Gen_6)#TrackPoint_and_Touchpad_issues). 

> Note: Some models of the 6th generation X1 Carbon seem to have issues with the TrackPoint and Touchpad working at the same time. 
So there is an idea of different in different models.

**Comment by 1Revenger1** [comment]
If you do end up opening a bug report for VoodooRMI, can you please provide a log from boot up and use the debug version of VoodooRMI? It should give quite a few details about setting up the trackpoint.

**Comment by lucas-www** [comment]
> Hi Lucas,
> 
> Personally, setting a flat acceleration profile for the mouse made my trackpoint feel much more precise.
> Open the Terminal and type:
> `defaults write .GlobalPreferences com.apple.mouse.scaling -1`
> Reboot and you should notice the difference.

Thank you for you suggestion, I tried your settings,trackpoint speed become slow than trackpad obviously and Inaccurate positioning.

**Comment by lucas-www** [comment]
After many attempts to compare with trackpad’s pointer, The trackpoint pointer is slightly inaccurate, which seems to be a problem of trackpoint acceleration,Especially when you need to select text accurately, moving the trackpoint gently will make it difficult to accurately locate the character boundaries. The speed of the trackpoint will change a lot when you gently slide the trackpoint. Adjusting the speed of the trackpoint is useless.
Trackpad has no such problem and can select text very accurately.

**Comment by tylernguyen** [comment]
@lucas-www 

Please provide a dump of your device with https://github.com/vulgo/IORegistryExplorer

**Comment by lucas-www** [comment]
> @lucas-www
> 
> Please provide a dump of your device with https://github.com/vulgo/IORegistryExplorer
@tylernguyen I dump all device information for reference in the below link, thanks again.
[https://github.com/lucas-www/info/blob/main/Lucas_x1c6.ioreg](url)

**Comment by lucas-www** [comment]
> @lucas-www
> 
> Please provide a dump of your device with https://github.com/vulgo/IORegistryExplorer

I also dumped my device information by AIDA64 from windows10.
aida64 report, https://github.com/lucas-www/info/blob/main/Report.htm

**Comment by lucas-www** [comment]
TrackPoint is the soul of Thinkpad, isn't it? So I hope it becomes better, thanks.

**Comment by notthebee** [comment]
> Thank you for you suggestion, I tried your settings,trackpoint speed become slow than trackpad obviously and still Inaccurate positioning.

Not sure what you mean by "obviously". The command simply disables cursor acceleration which makes cursor movement more accurate. The trackpoint speed can be changed in the VoodooRMI's Info.plist. Specifically `TrackpointMultiplier`. Personally I have it set to 10.

**Comment by lucas-www** [comment]
![image](https://user-images.githubusercontent.com/68903281/98792703-d8943d80-2441-11eb-9421-d20d8a70e327.png)
these are my settings. better than before, but not perfect.

**Comment by tylernguyen** [comment]
@lucas-www 

As others have stated, trackpoint is currently being handled by `VoodooRMI`. You may tweak mouse settings as well as `VoodooRMI`'s Info.plist for a more desirable experience. Addtionally, @notthebee 's recommendation should have made a noticeable difference.

I will now close this issue as it's more a or less a matter of personal preference as to how you prefer your trackpoint to behave. And if it is indeed a kext issue, please provide a log from boot up and use the debug version of VoodooRMI to create an issue at `VoodooRMI` so @1Revenger1 can address it.

**Comment by davidohne** [comment]
Is your trackpad working fine with Ventura? Mine works, well "ok". Drag and drop of files isn't working at all. I'm coming from an T480s and the elan trackpad feels not that good but drag and drop is possible. With the X1C6 drag and drop is nearly impossible. I'm using all the kexts from the repo and I was just wondering if the trackpad/touchpad behaves the same on your side? It seems that all of this is a Synaptics problem. ELAN touchpads seem to work better.. I'm thinking about putting a x1c7 trackpad into the c6 but I don't know if it will fit...
