### ISSUE TITLE
Keyboard Legacy not working

### ISSUE THREAD

**Issue by buyddy** [tylernguyen/x1c6-hackintosh#98]
I am testing without yogasmc at the moment, it seems that just simply switching back to keyboard legacy and adding the patches won't enable Thinkpad assistant's function keys. I even disabled ssdt-EC, still not luck. Resetting NVRM does not help too. is there another ssdt/kext that did something to the keyboard layout?

**Comment by buyddy** [comment]
<img width="974" alt="Screen Shot 2020-11-09 at 9 21 29 AM" src="https://user-images.githubusercontent.com/64387298/98560270-33287080-226d-11eb-823c-49057bb042b4.png">
<img width="978" alt="Screen Shot 2020-11-09 at 9 22 08 AM" src="https://user-images.githubusercontent.com/64387298/98560292-37548e00-226d-11eb-9040-ae498a7cb2db.png">
My ssdt and patch now. The SSDT-Keyboard is actually SSDT-Keyboard-Legacy

**Comment by tylernguyen** [comment]
@buyddy 

Keep the ACPI renames and try this patch https://github.com/tylernguyen/x1c6-hackintosh/blob/5eeea6037e2127cdb0867eee7df2613e6356fb7c/patches/SSDT-Keyboard.dsl

**Comment by tylernguyen** [comment]
@buyddy 

I forgot to mention. You would need to disable `BrightnessKeys.kext`. Try this before trying the patch from the old commit.

**Comment by buyddy** [comment]
> @buyddy
> 
> I forgot to mention. You would need to disable `BrightnessKeys.kext`. Try this before trying the patch from the old commit.

I disabled BrightnessKeys.kext, does not seem to make a difference. Also using the old ACPI does not seem to make a difference as well. Should I keep ssdt-EC or disable it?

**Comment by benbender** [comment]
Check for ACPI-Errors with `log show --last boot|grep -i AE_` and check with MACIASL if your renames are correctly applied. To do this open your running DSDT MACIASL (https://github.com/acidanthera/MaciASL) and search f.e. for XQ64.

If the SSDT loads (which I suspect to be the problem) and your renames are applied it should work.

**Comment by buyddy** [comment]
> Check for ACPI-Errors with `log show --last boot|grep -i AE_` and check with MacIASL if your renames are correctly applied. To do this open your running DSDT in MacIASL (https://github.com/acidanthera/MaciASL) and search f.e. for XQ64.
> 
> If the SSDT loads (which I suspect to be the problem) and your renames are applied it should work.

It turned out that it is the DSDT that needs to be patched not the SSDT. Put the wrong signature. Also I missed patching _Q74 and if one of the key has a conflict, the whole SSDT won’t load.

**Comment by buyddy** [comment]
By the way, the legacy patching will also have the problem that if booted on mute, the Sound volume icon will have a reversed status as the Mute button. And worse than Yogasmc, try to mute and unmute will cause system crash and reboot.

**Comment by tylernguyen** [comment]
> 
> 
> By the way, the legacy patching will also have the problem that if booted on mute, the Sound volume icon will have a reversed status as the Mute button. And worse than Yogasmc, try to mute and unmute will cause system crash and reboot.

That used to be patched with https://github.com/tylernguyen/x1c6-hackintosh/blob/5eeea6037e2127cdb0867eee7df2613e6356fb7c/patches/SSDT-LED.dsl

But yeah, there's a reason why `YogaSMC` is preferred. It works in a more native way.

Regarding the Mute issue on YogaSMC, you can create a PR like https://github.com/zhen-zen/YogaSMC/blob/master/YogaSMCUtils/ScriptHelper.swift#L58

**Comment by benbender** [comment]
@buyddy Every slight failure in a SSDT will prevent it from loading - so nothing special here. Checking for ACPI-errors should always be your first case of business 👍

**Comment by buyddy** [comment]
@tylernguyen SSDT-LED from previous distribution won't work with the new release. Because in the new SSDT-Sleep, method _TTS has been defined already. So SSDT-LED won't load. Took me a while to figure out. But it is an easy fix, just to combine the two _TTS methods into SSDT-Sleep. By the way, the mute on boot issue is not going to be fixed by this. Maybe it is a better idea to try YogaSMC.

**Comment by tylernguyen** [comment]
> @tylernguyen SSDT-LED from previous distribution won't work with the new release. Because in the new SSDT-Sleep, method _TTS has been defined already. So SSDT-LED won't load. Took me a while to figure out. But it is an easy fix, just to combine the two _TTS methods into SSDT-Sleep. By the way, the mute on boot issue is not going to be fixed by this. Maybe it is a better idea to try YogaSMC.

Yup, hence why it is the legacy method. I'll remove it completely on the next release.

**Comment by benbender** [comment]
@buyddy If I may ask: what are you actually trying to achieve and why?
