### ISSUE TITLE
Auto restart after shutdown

### ISSUE THREAD

**Issue by lucas-www** [tylernguyen/x1c6-hackintosh#99]
Shutdown becomes restart,when I clicked 'Shut Down' from left top menu, pc got to reboot but shutdown.
catalina 10.15.7 with latest update. hardware infomation in the same repository.
https://github.com/lucas-www/info/blob/main/config.plist

**Comment by lucas-www** [comment]
When I use the power adapter, the shutdown will automatically restart,But the last version will not be like this,Does anyone have the same problem as me

**Comment by tylernguyen** [comment]
@lucas-www 

I'm in the middle of pushing out a big update. Please hang tight for about 1-2 days.

**Comment by tylernguyen** [comment]
@lucas-www 

Could you try it now with the newest EFI?

**Comment by lucas-www** [comment]
After updating to your latest update, This problem disappeared, thank you for your perfect work, you can close this issue now. @tylernguyen

**Comment by benbender** [comment]
@lucas-www you can close issues yourself you opened in the first place.
